### ISSUE TITLE
Override the default admin route

### ISSUE THREAD

**Issue by mojoblanco** [thedevdojo/voyager#101]
I woud like to change the default admin route.

Currently i get to the admin by visiting localhost:8000/admin
I would like to change the route to something like localhost:8000/super

Do i have to go into the route file of voyager and manually edit it or there is a better way I can override it?

**Comment by fletch3555** [comment]
Currently those routes are static and unchangeable (at least without making changes under `/vendor`). There is another open issue(that I created actually) that is asking for the routes to be configurable, but no action has been taken on it yet.

**Comment by FergusInLondon** [comment]
An obvious first action here would be to:
1. Refactor the [routes.php](https://github.com/the-control-group/voyager/blob/master/src/routes.php) file, and make use of the framework features (i.e [Route Prefixing](https://laravel.com/docs/5.3/routing#route-group-prefixes)) rather than relying upon identation.
2. Take a config value (i.e via `env()`?) for the top most route group.

In all honesty, that's like a 15 minute task - but I've never used this package, and I'd be uncertain as to whether it would break anything elsewhere. I don't know if the templates are using hardcoded URLs, but sadly the lack of [named routes](https://laravel.com/docs/5.3/routing#named-routes) suggests to me that they wont be using Laravel's `route()` method, and thus any changes to the routes will break the UI.

**Comment by marktopper** [comment]
This is now possible.
