### ISSUE TITLE
Admin access

### ISSUE THREAD

**Issue by robertnicjoo** [thedevdojo/voyager#1040]
- Laravel Version: 5.4
- Voyager Version: 11
- PHP Version: 5.6.25
- Database Driver & Version: 5.7.14

### Description:
I just installed voyager for first time, when i try to open URL/admin I get `Sorry, the page you are looking for could not be found.` error!

Any idea?

### Steps To Reproduce:

I just saw my _web.php_ file seems nothing added to this file!
```
<?php

Route::get('/', function () {
    return view('welcome');
});
```

**Comment by sarath-c-sandwich** [comment]
Did you install Laravel Voyager?
```
php artisan voyager:install
```
Then create an Admin account:
```
php artisan voyager:admin your@email.com --create
```

**Comment by robertnicjoo** [comment]
@uchsarath already i did those.

**Comment by lednhatkhanh** [comment]
Same error here, laravel 5.4, tried every steps.

**Comment by fletch3555** [comment]
This issue is a bit old, so let me know if it's already resolved and I'll close it.

It looks like `artisan voyager:install` didn't complete properly.  Please try it again and pay close attention to see if any errors are displayed.  Also, please tell us what version of voyager you're running.  There have been significant changes between 0.11.4 and 0.11.9

**Comment by naseem1amjad** [comment]
I had the same issue and what I did is set db_engine (of mysql) to "InnoDB" from "MyISAM" and it worked. Hope this helps.
