### ISSUE TITLE
Category Column is Null

### ISSUE THREAD

**Issue by kvlknctk** [thedevdojo/voyager#1051]
- Laravel Version: 5.4
- Voyager Version: 0.11.8
- PHP Version: 5.6
- Database Driver & Version:

### Description:
I tried normaly Post add and select with dropdowns own category. But its not changed.

**Comment by ghost** [comment]
+1, I can not save category in posts.

**Comment by nubinter** [comment]
Bump, got the same issue.

**Comment by nubinter** [comment]
Got it, the cause is category_id's default bread is a checkbox while in editor it is a select option.
So, go to bread setting and change the type into dropdown.

**Comment by kvlknctk** [comment]
@nubinter good but not best way.

**Comment by fletch3555** [comment]
@kvlknctk, @nubinter's suggestion is the correct solution.  It sounds like there was an issue when you installed voyager when "BREAD" values were created in the DB.  These were created with the incorrect field type (Checkbox, or NULL since Checkbox is the default selection).  Relation types need to be `select_dropdown` (or `select_multiple` for a many2many relationship).
