### ISSUE TITLE
[Bug] Admin Sub Menu Items Not Workign

### ISSUE THREAD

**Issue by marktopper** [thedevdojo/voyager#107]
When using the menu builder on the admin menu to create a sub menu.

Then it can not open the sub menu on the admin panel.

**Comment by handiwijoyo** [comment]
PR #74 fixed this issue, but only for 2 level menu

**Comment by akazorg** [comment]
I created PR #74 working with 2nd levels only because I needed that fix right away.

If we take a look at [src/Models/Menu.php](src/Models/Menu.php), we realize that views are hard coded on the model, so I guess most of the code will change. I'm sure @tnylea have plans for this?

I also noticed that some of the menu items (Tools and Settings) are coded at [src/views/master.blade.php](src/views/master.blade.php), if we moved this to the database, we would be able to manage this items using the Menu Builder.

**Comment by marktopper** [comment]
@akaZorg: We could indeed move the menu items from the view to the database. It just requires that 2nd levels works first.

Also I think it would come in handy if the menu where build using views instead, that makes it way more customizable. I do not know if @tnylea have any plans so far.

**Comment by akazorg** [comment]
Hello, (sry about delay).
2nd levels are working at the moment, just from the 3rd + is not. I would advance more work on that, but I need confirmation from project maintainer - hey @tnylea, are you alive? :dancing_men: any plans for the menu?

I noticed you post issue #108 regarding views, we should do it indeed!

**Comment by marktopper** [comment]
This works now, but only for 2nd level menus.

Let's keep this open until more levels are supported.

I might try to solve this somehow in the near future.
