### ISSUE TITLE
User picture lost, can't create folder /storage/users/default.png

### ISSUE THREAD

**Issue by vanloc0301** [thedevdojo/voyager#1111]
- Laravel Version: 5.4
- Voyager Version: v0.11.9
- PHP Version: 7.1.3
- Database Driver & Version: MariaDB 10.1.22 

### Description:
When I reinstall my OS and run Voyager project again.
The profile picture is lost. 
I can't find folder ```/storage/users```.

Have only three folders in ```/storage``` is: ```app```, ```framework```, ```logs```.

**Comment by GlezSosa** [comment]
You have to create a symbolic link from /storage/app/public to /public/storage.

You can run this command to do it:
`php artisan storage:link`
Otherwise, you can use this (always in UNIX): 
`ln -s /path/to/laravel/storage/app/public /path/to/laravel/public/storage`

Make sure your apache has this feature enabled.

**Comment by vanloc0301** [comment]
Thanks @GlezSosa
