### ISSUE TITLE
pdf and voyager

### ISSUE THREAD

**Issue by luismareze** [thedevdojo/voyager#1118]
Laravel Version: 5.4
Voyager Version: v0.11.9
PHP Version: 7.1.3
Database Driver & Version: MariaDB 10.1.22
Description:

I would like to work with pdf, basically I need to export all the browse's data.
Is there any recommendation to work with?
Thanks

**Comment by nunomsh** [comment]
You can use TCPDF or DOMPDF. If you plan to use pdf templates, I suggest to install FPDI.

**Comment by endrureza** [comment]
@luismareze since voyager dashboard browse table using datatable, you can tweak it's script. First download the plugin for datatable though, here you may take a look at these 

https://datatables.net/extensions/buttons/examples/initialisation/export.html

no need TCPDF at all, since he just wants to export the browse table content.

**Comment by fletch3555** [comment]
Closing as the question has been answered

**Comment by robertkingkira** [comment]
> @luismareze since voyager dashboard browse table using datatable, you can tweak it's script. First download the plugin for datatable though, here you may take a look at these
> 
> https://datatables.net/extensions/buttons/examples/initialisation/export.html
> 
> no need TCPDF at all, since he just wants to export the browse table content.

Could you please give more details about how to do this ? I'm also trying to add a Download PDF button to my Orders page table from Voyager Admin Dashboard 
![voyager-pdf](https://user-images.githubusercontent.com/46875103/77866343-e5597d80-7232-11ea-8205-31cf1ae07d71.png)
