### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by malutanpetronel** [thedevdojo/voyager#1163]
I was able to install it on an existing Laravel site...
What is supposed to do ?
I've thought that maybe the pages I am created in admin to be shown on front ? Did not found a word on how to do that ?! Please ilumminate me

**Comment by sarath-c-sandwich** [comment]
what is your laravel version? I think normally 5.3 and 5.4 is recommended to use for Voyager.

**Comment by malutanpetronel** [comment]
I was able as I said to use it with laravel and output a menu on the home page 

{{ menu('Meniu-general') }}

pointing to a created page in the admin but I do not see the point of using the admin beside having the breads... thought pages are thing sto be shown as blog on a frontend ?

**Comment by endrureza** [comment]
@malutanpetronel well, you may take a look at @marktopper gist here 

https://gist.github.com/marktopper/ad3f8048a1a7bf55a5fcc747745d92ec

**Comment by fletch3555** [comment]
Pages are included as an example of something Voyager can do.  Voyager in and of itself is not a CMS, and therefore doesn't touch your frontend site (blog or otherwise).  Voyager gives you a simplistic admin interface for configuring/managing your site.  It can be used for authoring content if you choose to set it up that way.
