### ISSUE TITLE
TinyMCE stripping tags

### ISSUE THREAD

**Issue by AurelDragut** [thedevdojo/voyager#1191]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.10
- PHP Version: 5.6
- Database Driver & Version: Mysql 5.6.35

### Description:
TinyMCE strips some tags/tags attributes when i add content to page's body by using the source code button

### Steps To Reproduce:
Add a page and add its content as html using the source code option

**Comment by eddielee394** [comment]
TinyMCE is rife with tag stripping issues.  In my case, when using icon tags, tinymce will strip them if they're empty.  Probably the same issue going on with other tags as well.  Workaround is to avoid using any empty tags.  
So in the case of the `<i>` tag usage,  instead of using:  
`<i class="fa fa-check"></i>`
Add a comment in between the tags and they won't be stripped. 
`<i class="fa fa-check"><!-- Icon --></i>`

**Comment by AurelDragut** [comment]
Yeah, @eddielee394, that is also annoying. We should have a better control over all of those "features"...

**Comment by eddielee394** [comment]
It's not really a Voyager issue, as much as it is a known issue with TinyMCE.  A permanent fix would be to publish the Voyager assets & modify the `public/assets/voyager/js/voyager_tinymce.js` file to allow whatever tags you need in the content configuration.  Here's an example of how I included `<i>` (icon) tags: 
```
//...voyager_tinymce.js

extended_valid_elements : 'input[id|name|value|type|class|style|required|placeholder|autocomplete|onclick],i[class|style]',

```
Where `i[class|style]` allows the `<i>` tag and `[class|style]` allows the `class` and `style` attributes within the tag.  

Just be aware that certain tags are stripped intentionally as a security precaution.  So be aware of the potential security impact that will be occur as a result of whatever tags you allow.

**Comment by fletch3555** [comment]
Not a Voyager issue.  Workaround provided by @eddielee394
