### ISSUE TITLE
how to create a download option and print option in laravel voyager on my websites from voyageradmin pannel

### ISSUE THREAD

**Issue by aamirkhan37557** [thedevdojo/voyager#1192]
how to create a download option and print option in laravel voyager on my websites from voyageradmin pannel- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by endrureza** [comment]
@aamirkhan37557 please fill the provided format for asking an issue. Fill with your system description, fill description with your problem.

**Comment by aamirkhan37557** [comment]
i want to create an option on my school websites to dwonload the pdf or doc or excel ....in laravel voyager i have created a column and name it attachements and given its type as file now i want to display this file on my school website and want the clients or students to download it

**Comment by fletch3555** [comment]
This isn't an issue with Voyager.  Voyager's purpose is to make it easy for you to create/edit content for your site through the BREAD system.  What you're looking to do is to make use of the models on the front-end of your site, which can be done with basic Laravel functionality.  For that, I'll direct you toward the Laravel documentation.

If you need further assistance, you're welcome to join our Slack group and post questions in the #help channel, and someone may be able/willing to help you figure it out.  Your best bet is to join one of the Laravel support channels (Slack or otherwise) for assistance.
