### ISSUE TITLE
Request Feature: Dashboard Data Entry Form Grid

### ISSUE THREAD

**Issue by sarath-c-sandwich** [thedevdojo/voyager#1208]
## Description.
It's just an idea, it will be good if we can create grid column for data entry form in the admin dashboard. By drag & Drop into the column grid.
Some field like  First Name & Last time. Normally information is so short, both fields should display in the same line.

Thanks,
![admin-form](https://cloud.githubusercontent.com/assets/1330852/25561584/cd0549de-2d99-11e7-95f9-b4d78e6b1654.png)

**Comment by fletch3555** [comment]
This sounds like the purpose of the view, which can already be overridden.  I don't see how this would be done. Any possible solution I can think of would be very clunky.

I recommend against this feature and instead suggest just overriding the view.  However, if someone else wants to try to think up something I haven't, I'm more than willing to take a look.

**Comment by akazorg** [comment]
@fletch3555, I understand your concerns about this, but the UI/UX doesn't feel right this way.
For instance, when using a table with many fields, some of this fields are small and by using the full screen width, it causes the user to scroll the window too much.

The solution we have atm, is to create a custom view, and this can turn to be really time consuming.  If we imagine a big database, with many fields.

I think about this many times, and don't mind on try something.

**Draft Idea**

We create templates with defined sections where BREAD items are placed, and use JSON for save the mapping of Section <--> BREAD item.

Since fields are shown differently on (Read, Edit, View), we have to specify the template and section mapping for every action we want to use (Read, Edit, View). This can work optionally, being enable only if JSON is defined.

For mapping the Section <-> BREAD item, we could implement that on each BREAD view, using a simple drag-and-drop effect. We can also restrict access using a permission.

Any considerations, ideas?

**Comment by fletch3555** [comment]
I completely understand your concerns about UX and scrolling, but try to think about it from Voyager's perspective. How are you going to know what fields make sense to be next to each other. You could end up with something like this:

| first name     | age            |
| date of birth | last name |

As you mentioned, yes, you could build a "form builder" into Voyager, but that would be fairly complex functionality (aka more moving parts, more points of failure, more things to break).  Do we really need it when users are free to override the view anyway.

While I appreciate the suggestion, I think we have to hold off on it for now.

**Comment by sarath-c-sandwich** [comment]
Basically, we don't need to start with Drag & Drop, but we can just offer option to add CSS class to any field, so then it would be easier for developer to add that.
eg:  col-sm-6 on the first_name and col-sm-6 on the last_name.

**Comment by akazorg** [comment]
Hello!
Following your example @fletch3555, it would be great to have Voyager determining where to place fields, automatically, but imho that's impossible without user intervention.

I can't think on another solution besides using some sort of "form builder" with drag-and-drop. This would definitely require some work, and can be complex.
I also don't consider this a priority on the system, maybe later, if we need to spend much time creating custom views.


@uchsarath I had a thought on that idea, but how would we handle columns, multi rows, and/or a mix of different number of columns and rows?

**Example**
| first name | last name |
| email | phone | date of birth |
| rich text box |
| optionA | optionB | optionC | optionD |

**Comment by sarath-c-sandwich** [comment]
That's okay, it's just request only. I don't think it's the most important part as the modules work properly well. 

What if we store those information as json data into a **new column** of each table ?
eg:  order column
```
{ "order": 1, "column: left" }  
// order should be row number and column should be storing on left or right. 
```
Or we can put those information in Optional Details as JSON data in BREAD
If 2 fields has the same order_id that should be on the same row, then we can check if it's on the left or right. :)

**Comment by akazorg** [comment]
Hello. This feature is really great, but honestly, it requires a lot of work.

I had the same idea of storing that information on the JSON, but having that type of condition, doesn't sound like a clean solution (please, don't take me wrong, it's just my opinion).

Let's keep in touch. I hope we come up with a solution for this meanwhile.

**Comment by pjeutr** [comment]
In my opinion these thing shouldn't be in the BREAD admin, only things to make data presentable into an input field  (conversion / validation / relations), nothing with layout.
Otherwise I think things will clutter up and become unclear / overcomplicated
I see voyager as a scaffolding thing, to whip out an backend quickly.
If you want something else in presentation, just like @fletch3555 said copy the view and edit.

just my 2 cents

**Comment by fletch3555** [comment]
I'm going to close this for now.  We may revisit it later
