### ISSUE TITLE
Please add "tag" field to post

### ISSUE THREAD

**Issue by minhphuc429** [thedevdojo/voyager#1237]
- Laravel Version: 5.4.22
- Voyager Version: 0.11.10
- PHP Version: 7.1
- Database Driver & Version:

### Description:
add tag to post like wordpress

**Comment by fletch3555** [comment]
Voyager is intended to be a Admin tool for managing your site, not a CMS.  It provides the functionality needed to add this functionality yourself.  The `Posts` and `Pages` models that it currently ships with are there as examples, not as finished products.  Due to this, I must deny your request.  We will not be expanding the "CMS-like" functionality of Voyager.

As a side note, there was talk a while ago about someone building a CMS using Voyager, but I haven't heard anything in a while, so I don't know the current status.
