### ISSUE TITLE
BREAD 500 error - 1.5 mil rows.limit sql query!

### ISSUE THREAD

**Issue by Fed0t** [thedevdojo/voyager#127]
I create BREAD for a table with 1.500.000 rows and when i load (/admin/locations/) and i get 500 Internal Server Error.
Is there limit rows to display in sql query to set it lower?

Note:
I also create BREAD for a small table...and works very well!

**Comment by Fed0t** [comment]
I open VoyagerBreadController@index and i change "::all();" to "::take(100)->get();" and it works...but now i need to implement the limit.

**Comment by tnylea** [comment]
When adding BREAD to a table we need to allow the ability to have the results paginated and then we can select how many you want to paginate each page by. Definitely going to add this down the road.

Feel free to make a PR for this feature otherwise it's on the list 👍 
Added this to the voyager bug list to be implemented here: https://github.com/the-control-group/voyager/projects/1

Thanks a ton.
