### ISSUE TITLE
Erro on relationship when table name has _(underscore)

### ISSUE THREAD

**Issue by joefreire** [thedevdojo/voyager#1304]
I break my head to find this bug but when you have a relationship and your table has undescore like
salles_table

this give a problem

BreadRelationshipParser on line  32
$method = camel_case($item->field);

the solution is only remove camel or do other if check has underscores

**Comment by joefreire** [comment]
need take of camel_case on views too

**Comment by lancepioch** [comment]
Labels: possible bug

**Comment by fletch3555** [comment]
@joefreire, I know this is really late, but I don't see how that code could cause your issue.  `camel_case()` will convert a string TO camelcase, so `table_name` becomes `tableName`.  Per [laravel conventions](http://www.laravelbestpractices.com/#table_and_field_naming) (not an official link, but it's the closest I could find at quick glance), table names SHOULD be snake-case (with underscores), so that camel_case() call needs to be there to convert it to the method name.

Please re-verify this now that 1.0 has been released.  If it's still an issue, we can reopen it.
