### ISSUE TITLE
Watermarks

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#1307]
- Laravel Version: 5.4
- Voyager Version: 0.11.12
- PHP Version: 7
- Database Driver & Version: mysql

### Description:
Hi! Is there any fynctionality to set watermarks on image?

**Comment by nunomsh** [comment]
As far as I know none..
You can create some script that will generate the images+watermark, or you can do it with .htaccess
I prefer the second one, because it keeps the original image, and if you need to replace the watermark or images, you don't need to generate them again.
What this does is before it shows the image from the folder, apache will run the script that add the watermark, and show the image with watermark

**Comment by mustafa-ramax** [comment]
I think you can use Intervention Image library, its very easy to integrate with laravel,
Take a look to this link:

http://image.intervention.io/getting_started/installation

**Comment by fletch3555** [comment]
Intervention is already included as a dependency of Voyager. It's how we resize the images on upload.  You're free to add your own image modification configuration in the bread config for that field. All intervention values are(or at least should be) supported.  Please see our docs for instructions on where to put the config, and intervention docs for what to use.

I haven't looked into whether intervention actually supports this, but that's an intervention issue, not a Voyager one, so I'm going to close this.
