### ISSUE TITLE
Multiple Roles for Users

### ISSUE THREAD

**Issue by nunomsh** [thedevdojo/voyager#1346]
- Laravel Version: 5.4
- Voyager Version:0.11.12
- PHP Version:
- Database Driver & Version:

### Description:
Is there an option to add multiple roles for the same user? Currently it only allows to assign one role for   ##user.
Would be nice to allow multiple roles for the same user, and inherited the higher permissions, so a manager can do all the things user can, and admin can do all the manager things, and so on.
Probably set some permission levels to the role, or dependency tree, so we can identify the level for each role and it's inherited permission

**Comment by akazorg** [comment]
Hi @nunomsh, multi roles is not implemented, but there is some work in progress.
Thanks.

**Comment by judgej** [comment]
This is an absolute must. ACL systems are designed with the assumption that users will be members of one or more roles. Making a user a customer, for example, should *never* preclude them from being a supplier too. Whatever ACL package you are using, will almost certainly support multiple roles out of the box, making this fix a UI issue. [Just one example](https://github.com/Zizaco/entrust#user-relation-to-roles) - it's a solved problem with packages that do the heavy lifting.

Edit: however, I have just spotted the `role_id` in the users table, and that makes me very sad, as it adds a massive restriction on an otherwise excellent package :-( All decent ACL libraries for Laravel use a `roles_users` table for a many-to-many. Laravel Eloquent also pluralises the pivot tables by default, such as `permissions_roles` (also in alphabetical order).

**Comment by fletch3555** [comment]
Voyager's RBAC system does not have the concept of a hierarchical role system, so there's no way to "inherit" permissions.  This would be a significant undertaking, with many requirements to be fleshed out, which is why it's not currently there.  Adding multiple roles is easy.  Adding multiple roles with multiple permissions that need to be resolved is much more significant.

I don't disagree that it's a strongly desired feature, but we have to maintain "stability" at the top of our priority list, and we're not there yet.

**Comment by judgej** [comment]
Yes I agree *hierarchical* roles is another level again, and a pretty difficult thing to do efficiently in a relational database.
