### ISSUE TITLE
app.css used, but probably shouldn't be

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [thedevdojo/voyager#135]
The artisan install command tries to write a public/css/app.css file, but if that file already exists, the Voyager version is not written.

Recommend moving to a different name, say something like voyager.css as it's less likely to collide with app.css.

**Comment by ChrisThompsonTLDR** [comment]
I'd also recommend moving to using [asset()](https://laravel.com/docs/5.3/helpers#method-asset)

**Comment by tnylea** [comment]
All assets written to the app will be stored inside of the public/vendor/tcg/voyager/assets folder :)

If we moved to asset() and the site was on https:// wouldn't asset() still serve up the site via http:// instead of https://, for this case I would think using relative URL's would be better, unless there's something I'm missing. Let me know :) Thanks.

**Comment by ChrisThompsonTLDR** [comment]
`asset()` uses the app.url config param I believe.

```
Generate a URL for an asset using the current scheme of the request (HTTP or HTTPS):
```
