### ISSUE TITLE
menus.index route doesn't exist

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [thedevdojo/voyager#136]
It's referenced in `master.blade.php` but it's not in `routes.php` and not listed in `php artisan route:list`.

**Comment by maiorano84** [comment]
Check your `data_types` schema. There should be a `menus` option in there, if you didn't remove it.

**Comment by ChrisThompsonTLDR** [comment]
You're saying a seed file creates the menus.index?  Can you point me to which seed file does that?  I'm not seeing it.

**Comment by maiorano84** [comment]
It's a little more convoluted than that, but yes, that's the gist.

The Menu option is generated as a part of the BREAD Builder data types seed:

https://github.com/the-control-group/voyager/blob/master/publishable/database/seeds/DataTypesTableSeeder.php#L72

The `routes.php` file then iterates through this table and generates a resource for each one:

https://github.com/the-control-group/voyager/blob/master/src/routes.php#L17

If the record doesn't exist, then that particular route will fail, as no resource was generated during the above loop.

I'm currently in the process of starting a new branch the aims to separate the Menu Builder from Voyager itself so that it can act as its own component. Personally, I think that configuration matters should be kept out of the database, as we can run into issues exactly like this.

**Comment by ChrisThompsonTLDR** [comment]
Let me know if I can help.  We are very interested in using this project and have multiple installs of Laravel.  Some in sub directories, some at root levels.

I ran the seeders, but am still having issues.  All routes that are db powered end up `NotFoundHttpException in RouteCollection.php line 161:`

**Comment by maiorano84** [comment]
I'm only a contributor, not the author. @tnylea has been pretty good about doing a lot of the PRs, if you want to put in your own Pull Request.

**Comment by tnylea** [comment]
@ChrisThompsonTLDR the menus.index will map to the following route:

```
foreach(TCG\Voyager\Models\DataType::all() as $dataTypes):
    Route::resource($dataTypes->slug, 'VoyagerBreadController');
endforeach;
```

'Menu', 'Page', 'Post' are all considered a DataType. When a new data type is created from a table it then gets looped in the above functionality and will create the routes for that data type.

So, 'menu' must be in the database to be able to access that route. And that is actually how the admin menu is built by displaying the Menu from the Menu Data Type.

![screen shot 2016-11-10 at 1 23 19 pm](https://cloud.githubusercontent.com/assets/601261/20194860/f7700402-a748-11e6-9e7c-c193237c28c3.png)

Let me know if that helps clear things up.

So, have you tried running the following:

`php artisan db:seed --class=VoyagerDatabaseSeeder`?
Do you see the menus row inside of the data_types table? Let me know 👍

**Comment by ChrisThompsonTLDR** [comment]
Ya, I ran the seeder (which doesn't appear to abide by the `voyager.routes.prefix`) and modified the slug to match the url path I need.  I just get 404's, route not found.

**Comment by marktopper** [comment]
@ChrisThompsonTLDR, do you still have an issue here?

**Comment by fletch3555** [comment]
Closing as inactive.  @ChrisThompsonTLDR, please let us know if this is still an issue and we can reopen it.
