### ISSUE TITLE
(Possible) Option to add prefix to Voyager Tables

### ISSUE THREAD

**Issue by tnylea** [thedevdojo/voyager#1447]
Possible feature for version 1.0. Give users the option to add prefixes to all voyager tables. Allow them to change the prefix they would like to use, by default it would be `voyager_`

**Comment by harimayco** [comment]
+1 I really need this feature.

**Comment by ghost** [comment]
Hi, will this highly needed feature finally be part of the 1.0 release ? We do want to use Voyager in our company but we can't because of table name conflicts, and workarounds don't seem reliable enough in case of update. Thanks !

**Comment by fletch3555** [comment]
Voyager already provides a number of ways to change table names.  The only thing that would be guaranteed not to work is the `voyager:install` artisan command.  You're welcome to run the steps individually, making necessary changes along the way. You can find the code here: https://github.com/the-control-group/voyager/blob/master/src/Commands/InstallCommand.php#L68-L122

**Comment by ghost** [comment]
Thanks for your answer fletch. This is indeed one of the known workarounds, but it unfortunately doesn't solve the fundamental problem : Voyager uses tables names that are common to most of applications, which might make it come into conflict with most of existing databases. As the 1.0 version will surely introduce breaking changes, I guess that adding a default `voyager_` prefix shouldn't be a problem. Thanks for your help anyway !

**Comment by fletch3555** [comment]
The issue is a bit more complex than that though.

Assume we add that prefix.  Do we add it to all tables(users, posts, etc) or just the required ones(data_types, menus, etc)?  If we add it to all, what happens when someone wants to make use of the Users table for their app (since we already use App\User model by default anyway)?  Do we add it to all new tables created by Voyager? Do we update existing tables when we add BREAD to them?

I could go on and on with these unanswered questions. I'm hesitant to add table prefixes to anything other than the required tables, but I know that doesn't solve your problem.

My preferred approach would be to leave it as-is, because that's significantly easier to configure (no need for separate database configuration or Anything like that), and most people are adding this package before building out their app, as opposed to adding it to an existing, fully-built one.  I certainly acknowledge that it's a problem for some users, but the solutions all seem either more complex or they impact more users.

**Comment by ghost** [comment]
Just adding the prefix to the core tables would be great.

**Comment by lancepioch** [comment]
Labels: feature, discussion

**Comment by wanghanlin** [comment]
I think we don't need to force adding a prefix to table names or make the prefix default, we can have a config to turn it on, that would be helpful for users trying to add voyager in an existing project and avoid table name conflicts.

**Comment by handiwijoyo** [comment]
I propose to add an option `--table-prefix` to `voyager:install` 

Example:
```
php artisan voyager:install --table-prefix=voyager_
```

I can work on this if you guys agree on it.

**Comment by fletch3555** [comment]
There are issues with that as I said previously.  The app shouldn't care whether there's a prefix. The prefix should be handled completely transparently through the database connection config.  This leads to the solution of adding a new database config, specifically for Voyager, which I'm okay with, but complicates the install significantly.

I think the best solution is to document an alternate install process.  Leave the current method as-is for "new" apps, and document a manual step-by-step process for pre-existing apps while also pointing out likely failure points and how to resolve them (i.e. when running migrations, you may already have a `posts` table, so you should modify the published migration to be an "update table" instead of "create table")

**Comment by handiwijoyo** [comment]
The problem with that is the `voyager:install` command issue a `migrate` command which didn't allow developer to edit the migration file beforehand.

**Comment by fletch3555** [comment]
Yes, which is why `voyager:install`, being the "existing" method, would be left as-is and only encouraged for "NEW" apps.  Adding Voyager to existing apps would be instructed to follow the step-by-step directions

**Comment by geea-develop** [comment]
anyone forked and solved this?

**Comment by ElieSauveterre** [comment]
@geea-develop I started something. [`ElieSauveterre/voyager`](https://github.com/ElieSauveterre/voyager/tree/prefix_tables)
It's not the best solution, I added a prefix to all tables, but it's not an options you can add to `voyager:install`.
Also, I'm using [`Zizaco/entrust`](https://github.com/Zizaco/entrust) and I haven't figured out what to do with the user model. Both entrust and voyager have methods like "hasRole/can/attachRole...".  I'm thinking to add another user model for Voyager.

**Comment by omid-dashing** [comment]
Hi Voyagers,
We love your software but without this table name prefix feature we cannot use it.
Any updates on this feature deployment?

**Comment by SteamWind** [comment]
You could do something like:
```php
Schema::table((this.bPrefixUser ? this.prefixVoyager : '').'users', function ($table) { [...]
```
Where bPrefixUser is a boolean to determine if you need the prefix or not, where prefixVoyager is the global user defined prefix...

Or you define the table name somewhere else with something like:
```php
$user_table = ($this->bPrefixUser ? $this->prefixVoyager : '').'users'
```
then:
```php
Schema::table($this->user_table, function ($table) { [...]
```
Put it everywhere you need to call those table.

You could then ask the user if he want to define a prefix for the tables and if yes, ask for every tables where he need it.

What do you think about something like that @fletch3555 ?
Could it be a solution?

**Comment by mandofever78** [comment]
Anybody making any progress here?

**Comment by AlexStack** [comment]
+1 add it to all tables created by Voyager, Voyager may create a voyager_users table for only admin usage.
For the normal existed users table, we can add a BREAD to manage it or add a BREAD by default after installation.

**Comment by SteamWind** [comment]
For now, the best solution I found was to change my table names with a prefix and mention it in every Models...
In my case I share the user table with voyager but you manage it as you want...

**Comment by tnylea** [comment]
This will be made easier in version 2.0. Currently adding items to the v2.0 planning project: https://github.com/the-control-group/voyager/projects/6 👍

**Comment by klimis** [comment]
Another workaround that worked for me was to extend the Voyager models and use a different db connection. This way i use a different schema just for voygaer to keep it completely separated from my applications' db
