### ISSUE TITLE
Is it possible to add Rest API option to BREAD?

### ISSUE THREAD

**Issue by yusufiga** [thedevdojo/voyager#1553]
Hi, first of all this project is literally brilliant! Love it. 

I'm an Android developer so I was looking something to make my job easier when I need admin panel. Since I'm not a backend developer most of the time it's really painful to create admin panel for me. Luckily I found this project.

BREAD is amazing! I really love it, and it would be really awesome if you could add also Rest API option to BREAD. So mobile app developers like me can easily use it in our mobile projects.

Thanks in advance!

**Comment by fletch3555** [comment]
We're glad you're enjoying our project.

Voyager is intended to be an admin panel. What you're looking for is simply a different way of connecting to the data (via a backend api instead of directly loading data from the models), which is not admin functionality.

We've considered adding api functionality a few times, but nobody has been able to come up with a valid/reasonable admin-specific use-case for it. Without that use-case, it is very unlikely we will be adding that feature.

With that said, for the time being at least, you'll have to build your own api. Laravel makes it pretty easy.

**Comment by amansatija** [comment]
there is a very basic use case for it ....
as in the what if the front end client is just a data consuming device ...and the backend is where the data gets fed into the system from ... for such an app ... voyager is great fit for backend , how ever it doesn't provide an api wrapper which frontend devices can consume , and so i m working on making one , would u guys be interested in a pull request for the same ?

**Comment by fletch3555** [comment]
My previous comment debunks that argument already.  "Backend" can be defined in so many ways.  We consider Voyager to be an "admin" tool. It's just another data consumer, with the database (via laravel) being the true "backend" for your app.  Following that definition, having Voyager be the api "host" just doesn't make sense, as it just doesn't fit well with Voyager's purpose.  Instead, you need to build the API into laravel(in parallel to Voyager and your "front end", if you want to think about it that way).

Regardless of your definition, this has been closed for over a year, and I stand by my previous statements.  If you wish to discuss it further, I would be happy to, but in slack.

**Comment by Cmrickels** [comment]
I'll say this this. Im currently in an agency setting and each project demands an admin panel with the final product for the customer to edit data that goes into their platform. For apps that demand any true front end, we use VUE or React. I would love to bring voyager in an use it as a backend admin panel that helps scaffold out my backend for consumption via the front end. Only problem is I'd have to build an api layer on top of my Laravel app to make that possible. Strapi and a few other Node.js headless CMS and admin panels are doing it. It's a great concept and Voyager will need it to stay relevant in this atmosphere. Modern applications are not monolithic anymore. Lets get with the program guys. I want to use this on countless projects a year. Strapis not nearly as clean as laravel.

**Comment by sudoanand** [comment]
As @Cmrickels  said, let's stay relevant to the atmosphere. Websites need frontend along with the admin panel and the front-end needs APIs to communicate with the data that "admin" created. 

My other argument is that the Voyager is not really for "admins", it's being marketed to "Developers" as a tool to develop an admin panel, and the developers need these APIs along with the admin panel (like every time) then why not add this?

The problem here is not the missing feature but your unwillingness to add the feature. Let us know if you change your mind, one of us from the community will create a pull request.

PS: Voyager is awesome and a little more of awesomeness does not harm.

**Comment by yusufiga** [comment]
Despite I liked Voyager, due to my project requirements I searched for another project and found [cockpit](https://github.com/agentejo/cockpit) which fits my requirements. It's not developed on top of Laravel but it's easy to use and learn.

**Comment by fletch3555** [comment]
It's an architectural decision we've made.  Voyager doesn't (natively) build the pages for your frontend (like a CMS would), so why should it host your API as well? As I said above, it's intended to be an admin panel, and just another interface into the database, not the intermediary between your frontend and backend.

Having said that, Laravel makes it insanely easy to build out a REST API, and Voyager runs on top of Laravel, so why not just build it?

Anyway, this has been asked and answered many times.  If you'd like to continue the discussion, please join the slack group and ask there
