### ISSUE TITLE
Problem update page setting

### ISSUE THREAD

**Issue by pedami** [thedevdojo/voyager#1567]
- Laravel Version: last
- Voyager Version: last
- PHP Version: 5.6
- Database Driver & Version: last

### Description:
Hi, I installed the latest version of voyager using composer and combined with the current master of github, because with the master alone I never managed to run the panel translations correctly to other languages.
The case is that since I have updated everything seems to work correctly except for the settings page, when clicking, I throw the permission error denied, I have reviewed the permissions of the admin role and all are correct.
What can it be?
And when will the multiligual stable version be ready?

Thank you, you are doing a great job.

### Steps To Reproduce:
1. Click update setting

![image](https://user-images.githubusercontent.com/6138775/29410458-d04b0734-8350-11e7-90e6-9c087d781497.png)

**Comment by fletch3555** [comment]
The issue is because the `visit_settings` permission does not exist.  All you have to do is add `visit_settings` to the `permissions` table, then assign it to your user's role.

That's a change that was merged into `master` with a recent pull request.  `master` is very much unstable at this point while we prepare it for the laravel 5.5 release and our own 1.0 release, so we strongly advise against working with it for now.

**Comment by pedami** [comment]
@fletch3555 Thanks
I waited for the next update.
