### ISSUE TITLE
Images not shown on hosting

### ISSUE THREAD

**Issue by saldanac** [thedevdojo/voyager#1724]
- Laravel Version: 5.3
- Voyager Version: 0.11.14
- PHP Version: 5.6
- Database Driver & Version:

### Description:

i set up a voyager project on production as a subdomain example : http://subdomain.web.com/public/

on .env APP_URL is http://subdomain.web.com/public/

http://subdomain.web.com/storage/.../.../img.jpg ---- image not appear

can anyone help me please

### Steps To Reproduce:

install laravel voyager on godaddy as a subdomain

**Comment by davodavodavo3** [comment]
Are you run php artisan storage:link?

**Comment by saldanac** [comment]
yes I did.... My laravel app is running like http://subdomain.web.com/public/ but images not loading :(

**Comment by saldanac** [comment]
everythings is working fine...only images not loading properly

**Comment by saldanac** [comment]
![1](https://user-images.githubusercontent.com/21126731/30517185-7920be44-9b25-11e7-85c7-37125124f142.JPG)

what green background on storage folder means?

**Comment by fletch3555** [comment]
@saldanac, the issue is with your configuration.  It's not recommended to have laravel installed so the public directory is under the web root (to find out why, try visiting http://subdomain.web.com/.env).  If you insist on doing it that way, you need to update the storage path in `config/filesystem.php`.  the path `/storage/{...}/img.jpg` is referring to `/public/storage/...`, not `/storage/...`

Also, the green background is dependent on the terminal/shell you're using, but likely means that it's "world"-writable (https://unix.stackexchange.com/a/94505)

**Comment by saldanac** [comment]
thanks for u answers but still i can't see the imgs... can u  help me pls? :(

**Comment by saldanac** [comment]
Thank you I have done a wrong configuration...now I have laravel installed on root directory and public folder on public_html/subdomain ... now working fine. of course Its my first time uploading a laravel project on a shared hosting 💃 Thank you for your help.

**Comment by ghost** [comment]
pls help me

**Comment by ghost** [comment]
i tried file system and app url
