### ISSUE TITLE
admin panel not working

### ISSUE THREAD

**Issue by jitender-negi97** [thedevdojo/voyager#1733]
- Laravel Version: 5.5.
- Voyager Version: 0.11
- PHP Version:7
- Database Driver & Version:mysql

### Description:
hii
my voyager panel is showing fine but after clicking on the any option like menu bulider or user it shows the following error:
Type error: Argument 1 passed to TCG\Voyager\Policies\BasePolicy::browse() must implement interface TCG\Voyager\Contracts\User, instance of App\User given, called in C:\xampp\htdocs\admin\vendor\laravel\framework\src\Illuminate\Auth\Access\Gate.php on line 466

kindly help me to resolve this issue

**Comment by saldanac** [comment]
i think probably voyager is not for 5.5 laravel yet

**Comment by mxmtsk** [comment]
If you wanna use Voyager with Laravel 5.5, you should use the `dev-master` of Voyager in your project. First paragraph in the ReadMe explains it

**Comment by jitender-negi97** [comment]
i have installed voyager using dev-master 
but still the same problem occured

**Comment by fletch3555** [comment]
Couple issues:

1. Voyager v0.11.* does not support Laravel 5.5
2. It looks like you upgraded to dev-master from 0.11.*.  One of the new requirements is that your `App\User` model extend `TCG\Voyager\Models\User`  This is done by `artisan voyager:install`, which you likely didn't run since it's an upgrade, so you have to do it manually.
