### ISSUE TITLE
How to query relationship created with Voyager

### ISSUE THREAD

**Issue by Brotzka** [thedevdojo/voyager#1848]
- Laravel Version: 5.5
- Voyager Version: 1.0.2
- PHP Version: 7.1
- Database Driver & Version:

### Description:
I'm looking for a way to query a relationship within a custom controller. The realtionship is working in Voyager (via BREAD) but I don't know how to query it. Do I have to create the methods for my Models the way I have to do it without Voyager or is there an other way? Do I have to implement some Traits or extend some special Voyager-Default-Model? Can't find something about it in the documentation..

Theoretically it could not work the default way because there are no relationship-methods in the models.

````
// Not working, returns NULL
$product_category = ProductCategory::find(3);
$products = $product_category->products;
````

Thanks for help!

**Comment by Enyelber** [comment]
I have a similar case, I have a roll called teacher and I have users alk that assigns that roll.
Now I am creating a table called course where you must indicate which teacher has assigned that course.
I made the relationship from voyager and perfectly brings me all users but I need to filter and that only brings me those who have assigned the teacher roll, I can not see where to do it, with the new version.

**Comment by fletch3555** [comment]
You need to do it the laravel/eloquent way, with methods on your model classes.  Laravel doesn't give us an easy way to enumerate these relations, so that's how we ended up at the relationship builder UI that we have now.  This UI is specific for Voyager though, so you should still be adding those methods to use the normal way in your site/app.
