### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by marcio-machado-k** [thedevdojo/voyager#1855]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: 5.7.19

### Description:

Return invalid argument for a foreach, when trying to delete a record with a file field, but no file is present.

### Steps To Reproduce:

Create a record with a file field, but don't upload any file.
Delete that record from the admin interface.

You will get an invalid argument on the foreach.
<img width="1133" alt="screen shot 2017-09-24 at 21 59 36" src="https://user-images.githubusercontent.com/31821073/30786832-fafd7084-a173-11e7-8063-28eaf1fd07d9.png">

It seems that it goes to the foreach without verifying if a file is really present first?

**Comment by fletch3555** [comment]
Looks to me like it's failing after running `json_decode`, meaning the issue is likely that `$data->{$row->field}` doesn't exist.  `$row->field` should exist since it's not complaining about `$data->[NULL]`, meaning whatever `$row->field` holds doesn't exist as a property on `$data`.

My guess is that either:

1. you deleted a field and didn't update the appropriate BREAD entry (should only happen if you delete the DB column from outside of Voyager)
2. you didn't follow Laravel naming conventions when creating the field
3. the BREAD configuration for that type is holding something other than JSON data (so json_decode isn't running properly)
3. Voyager has a bug related to this

1-3 need to be checked before we can consider 4.  Please edit that file under vendor and add `dd($row->field, $data)` right before line 377, then try again and see what the values are.  You can post the values here and I'll take a look as well.

Thanks!

**Comment by mdelally** [comment]
@fletch3555 and I worked through this issue a little bit as I was having it on my end, as well. This issue is occurring because the `VoyagerBreadController`'s `cleanup()` method expects the file field to have an array of JSON 'objects' containing a 'download_link' & 'original_name' keys.

My particular occurrence was because I was setting my respective file column as a single, non-encoded string. To get around this in my own implementation (because uploading the file in the BREAD view will store the reference properly), I just handled and stored the file in my own `JobApplicationsController` similarly to how Voyager does.

```
$resume = $request->file('resume_file')->store('public/resumes');

$file = [];

array_push($file, [
    'download_link' => str_replace('public/', '', $resume),
    'original_name' => $request->file('resume_file')->getClientOriginalName(),
]);

$application->resume_file = json_encode($file);
```

Not sure if your implementation is for the front-end like mine, but storing the file reference in the table like above allows me to delete the record from within in Voyager with no error on `foreach()`.

**Comment by danord24** [comment]
I've just came across this issue and beleive i've found a fix for it. Apologies if this is digging up an old post, but it doesn't seem to be resolved.

I have a Resources table which has a column called "asset" which is a Voyager type of "file". Just like OP, if i create a new resource and leave the asset blank, it gets saved as NULL in the DB.

The output of $row->field == "asset" and the output of $data->{$row->field} is NULL. All I did was put an isset check before the second foreach loop.

`if(isset($data->{$row->field})) {

    foreach (json_decode($data->{$row->field}) as $file) {
        $this->deleteFileIfExists($file->download_link);
    }

}`

This allows me to delete / bulk delete rows without a file and a mix of rows with and without images without any errors.

I think my scenario covers points 1 and 2. With point 3 its true that its not JSON, but that's only because its saved as NULL.

A way around this would be to add required validation on the rows so that you have to upload a file etc, but i believe there is currently an issue where if you already have a file uploaded, but then don't change it when editing, the validation message shows, meaning you have to upload a file each time you edit something.

**Comment by neogeneris** [comment]
Hi, guys, I'm new with Voyager and have same bug

I think I repaired the class  MultipleImage  in a simple way add if($files) before foreach  

`

       public function handle()
       {

        $filesPath = [];
        $files = $this->request->file($this->row->field);


        if($files) foreach ($files as $file) {
            $image = Image::make($file);

            $resize_width = null;
            $resize_height = null;

        //  ...
        return json_encode($filesPath);
        }
     }
`

**Comment by droftage** [comment]
` 
// Delete Files
        foreach ($dataType->deleteRows->where('type', 'file') as $row) {
            if(empty(json_decode($data->{$row->field}))){
                continue;
            }
            foreach (json_decode($data->{$row->field}) as $file) {
                $this->deleteFileIfExists($file->download_link);
            }
        }
`

**Comment by droftage** [comment]
` 
 // Delete Files
        foreach ($dataType->deleteRows->where('type', 'file') as $row) {
            if(empty(json_decode($data->{$row->field}))){
                continue;
            }
            foreach (json_decode($data->{$row->field}) as $file) {
                $this->deleteFileIfExists($file->download_link);
            }
        }
`
I think this solve your problem.

**Comment by 4unkur** [comment]
Same issue here. I added column `video` and made it nullable. In BREAD editor, I made this field type of `file`. Created a BREAD item (FAQ entry in my case) and tried to delete it.  
I didn't upload a file to that entry that's why it holds `null`

**Comment by Benoit1980** [comment]
Yes same problem for me, when I set the column to file I get the same error as the other people above but when I set the column to image or multiple images, the mass and single deletion works fine.

**Comment by skyArony** [comment]
![image](https://user-images.githubusercontent.com/16434647/45996783-fcfcf680-c0cf-11e8-8e4e-a0e47067c988.png)

It can be solve by disable the delete checkbox，but will result the file can't be delete in disk.

**Comment by skyArony** [comment]
![image](https://user-images.githubusercontent.com/16434647/45997277-a1cc0380-c0d1-11e8-8800-29dcdf59086d.png)

It can be solve by disable the delete CheckBox ，but it will result the file still exist in the disk
