### ISSUE TITLE
Hide/Show fields by user

### ISSUE THREAD

**Issue by bedoz** [thedevdojo/voyager#1893]
- Laravel Version: 5.5.13
- Voyager Version: 1.0.4
- PHP Version: 7.1.0

### Question:
Hi Everyone,
There is a way to hide some fields for some users?
The only way i found is overriding views with additional custom checks.
Any other suggestion?

Thank you very much.
Alex

**Comment by fletch3555** [comment]
You will need to add the checks yourself in overridden views.  I recommend adding permissions to control this instead of checking the roles directly.  If you create permissions (e.g. `edit_name_user`), it will automatically be checked by `@can('edit_name', Auth::user())`.  The key is that the permission name MUST end with the model's BREAD "name"
