### ISSUE TITLE
api_token on register

### ISSUE THREAD

**Issue by aemaddin** [thedevdojo/voyager#1903]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version:7.1
- Database Driver & Version:mysql  Ver 14.14 Distrib 5.7.19

### Description:
When i create an api_token into users table to authenticate api requests, then when i create a new admin user from terminal that error is shown 

`[Doctrine\DBAL\Driver\PDOException]                                                  
  SQLSTATE[HY000]: General error: 1364 Field 'api_token' doesn't have a default value `

i tried to add `str_random(60)` into register controller, but the same error happened.

### Steps To Reproduce:
before install voyager
-insert `$table->string('api_token',60)->unique();` into /Database/Migration/...create_users_table.php
-install voyager
-create admin user

**Comment by fletch3555** [comment]
What do you mean by "create new admin user from terminal"? The `artisan voyager:admin` command?

The error means the code isn't providing a value for the `api_token` field and the database doesn't have a 'default' set.  You can either set a default in the database (either manually or by adding `->default(VALUE)` to your migration), or override everywhere a User is created.  I strongly recommend against the latter, since you don't have full control over all of Voyager's code (without modifying vendor code).  The command doesn't expect you to add fields to the User table, and can't possibly predict all cases.  Additionally, it's not intended to be used for day-to-day tasks, and should only be used for the initial admin user and/or troubleshooting permissions issues.  As long as you can log in, you can always create additional users through Voyager's UI, including setting the Role to admin, which would be my suggested approach.
