### ISSUE TITLE
Laravel Spark with Voyager

### ISSUE THREAD

**Issue by raphaelat** [thedevdojo/voyager#1906]
- Laravel Version: 5.5.13
- Voyager Version: 1.0.4
- Laravel Spark Version: 5.0.1
- PHP Version: 7.1
- Database Driver & Version: MySQL 14.14 Distrib 5.7.19

### Description:

I'm trying to use voyager along with Laravel Spark, so I tried to install it. I'm getting an error that can be solved by extending Voyager's voyagerUser. But when I do it I lose all the features Spark have.

 How can I solve it? I wanted to use both so I can create a front-end for the app all using Voyager, and a paid area for my users.

<img width="1679" alt="whoops__there_was_an_error__and_new_issue_ _the-control-group_voyager" src="https://user-images.githubusercontent.com/29602633/31005384-d39cf614-a4ce-11e7-9188-29193f67a40b.png">

### Steps To Reproduce:

 1. Install Spark using spark-installer
 2. Configure database and migrate
 3. Install Voyager and create a user via Spark, grant admin rights through the console.
 4. Try logging into voyager's admin panel.

**Comment by fletch3555** [comment]
First things first... We cannot test every package for compatibility, so there will ALWAYS be issues somewhere.  Since Spark isn't free/open source, we will likely not be testing it for compatibility.

Now, for your issue, it's actually fairly simple.  If you read the error, it tells you that your User model (`App\User`) must use the `TCG\Voyager\Contracts\User` interface.  This can be achieved easiest by extending the `TCG\Voyager\Models\User` model class.  Alternatively, you can add the interface as well as the `TCG\Voyager\Traits\VoyagerUser` trait to provide default implementations for interface methods (which you are then free to override if needed).
