### ISSUE TITLE
Issue with has many relationship in new voyager

### ISSUE THREAD

**Issue by faghihi** [thedevdojo/voyager#1943]
- Laravel Version: 5.5.0
- Voyager Version: ^1.0
- PHP Version:7.0
- Database Driver & Version: mysql 

### Description:
I am trying to add a has many relationship 
one model named company and one table named company_jobs 
in company_jobs i have a column named company_id 
so i added the relationship this way but when i am trying to save a new company instance I get the error that company_id doesn't exist in field list but it shouldn't be any way because company has not any company_id 

I thought this is gone in new laravel version but do we still need to make a useless column in table for a relationship any way ?!!

**Comment by faghihi** [comment]
@marktopper  can you please help me dealing with this problem ?!

**Comment by faghihi** [comment]
@fletch3555 
thanks for the reply 
the schema is exactly like what you said
`public function companyId()
    {
        return $this->belongsTo('App\Company','company_id');
    }`
this is the code of relationship inside companyjob model. 
i used the new voyager relationship add and faced the problem i told you

**Comment by faghihi** [comment]
@fletch3555 this is the error produced by submiting a null value for company jobs relaton inside company bread
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'company_id' in 'field list' (SQL: insert into `companies` (`name`, `phone`, `website`, `email`, `address`, `story`, `mission`, `image`, `size`, `company_id`, `updated_at`, `created_at`) values (qadas, asda, asdasd, asdasd, asdasd, asdasda, asdasd, companies/October2017/template-9-pdf.jpg, 1, , 2017-10-10 17:34:47, 2017-10-10 17:34:47))
```

and this is the relationship inside company model 
```
public function jobs()
    {
        return $this->hasMany('App\CompanyJob','company_id');
    }
```

**Comment by fletch3555** [comment]
The relationship builder functionality does not make use of model methods, so those methods *shouldn't* be the issue.  However, I'm curious... you've named your relationship method `companyId()`, which is also the field name on that table, correct?  I think this may be conflicting/confusing eloquent.  Try renaming the method to just `company()`

**Comment by faghihi** [comment]
I changed the name still nothing changed 
I think it is a bug because it shouldn't even try to save something name company_id in company table because of that relationship

**Comment by fletch3555** [comment]
I agree that it shouldn't, but I don't think it's a bug because we don't have tons of devs complaining about it.  This leads me to believe it's your configuration until proven otherwise.

**Comment by pirocoptero** [comment]
@fletch3555 i have the same bug. 

I have a table called compras that has many compras_detalhes. When i try to create a new compras it says compra_id inside compras_detalhes is null. But offcourse is null, because im creating a compras before add details in compras_detalhes. I need all fields of compras_detalhes inside the compras. 

Can you help me please?

![captura de tela 2017-10-11 as 14 50 59](https://user-images.githubusercontent.com/4484855/31457697-ed7f9f22-ae93-11e7-8ebe-5d2e2c188065.png)

![captura de tela 2017-10-11 as 14 52 06](https://user-images.githubusercontent.com/4484855/31457714-f7c2b55a-ae93-11e7-8fe0-262e6d8c1d47.png)

**Comment by pirocoptero** [comment]
In first print the line that say "Which column from the Compras_detalhes is used to reference the USER" actually is not USER, is Compra, voyager is changing the word only, this is not influencing anything.

**Comment by fletch3555** [comment]
@pirocoptero, we're aware of the issue where the table name is wrong in the box.  That's being handled elsewhere.

For the issue your previous comment, the error message indicates that your table `compra_detalhes` doesn't exist.  I'm guessing what's happening is that you're simply not following laravel conventions (table name is `plural_plural` instead of `singular_plural`), so laravel tries to find it and fails.  This is because we don't give you the opportunity to set the extra arguments like you would in the relationship method you'd normally create in your model (column names and/or pivot table name).

Unfortunately, at this time, I don't have a solution for you, other than to rename your table to be `compra_detalhes`

**Comment by pirocoptero** [comment]
@fletch3555 thank you for answering. I'll try your solution. See ya! xD

**Comment by cuzboo** [comment]
Do we have solution for this issue? I have the same problem, nobody responds.

**Comment by fletch3555** [comment]
@cuzboo.  I doubt your issue is exactly the same.  This issue is a year old and for an older version.  Your database fields are likely different.  Please open a new issue with all the relevant information, or ask in slack.

I'm closing this one due to age.  If it's still an issue for OP, please make sure you're using the latest version and update the information here

**Comment by SiddharthSampath** [comment]
Even I have the same issue, I have selected the has many relationship, but I'm only being show the table name, and am not able to select anything,
![hasmanyprob](https://user-images.githubusercontent.com/27061009/48304753-b9a5fc80-e544-11e8-96ef-8db3020a56f5.JPG)

**Comment by emptynick** [comment]
Thats not related to the original issue, also as @fletch3555 mentioned before, this issue is more than a year old.
As a side note: not even Laravel allows you to edit a HasMany/One relationship. I guess that's why Voyager doesn't allow you to do so also.
