### ISSUE TITLE
Options to Return a Response of Menu Object in Menu Builder Instead of a HTML

### ISSUE THREAD

**Issue by codeitlikemiley** [thedevdojo/voyager#2006]
Hi, Im using vuejs for front end, i wanna utilize the menu builder , but i dont want html to be return....

I think We Should Have 2 Options always for voyager either return a View(default) or a Response.

It would really make sense if you will use VueJs as your front end, 
and want to initialize all the data of your vue components

There are lot of things that we might need to return a response instead of view like
roles and permissions, users, i mean most of all the data types we have in our migrations...

**Comment by fletch3555** [comment]
The menu builder was originally for Voyager's purposes, so it's html only.  Since we provide a menu() blade helper, I agree that it would make sense to have a vue component or JSON response as well.  We're open for PRs

**Comment by dfk7677** [comment]
Correct me if I am wrong but this would require the following:
- A `display` function in the `VoyagerMenuController` class which would return the JSON response with the menu items.
- A `menus/{menuName}` GET route that would point to the aforementioned `display` function.
- A boolean `admin` column added to the `menus` table, so that the front end or anyone else hasn't got view access to the admin menus.

**Comment by emptynick** [comment]
Implemented in https://github.com/the-control-group/voyager/pull/3571
