### ISSUE TITLE
menu builder is not not working

### ISSUE THREAD

**Issue by rddewan** [thedevdojo/voyager#2037]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
I created a menu for user in menu builder and call it in my template as  {!! menu('main', 'admin_menu') !!}
but i don't see any menu and if i set as {!! menu('main') !!}  i can see the menu in list without any style

it was working will previously suddenly went off

**Comment by fletch3555** [comment]
All fields are required when submitting issues.  Please edit your issue description and provide the requested version numbers.

For your issue, you shouldn't be using the `admin_menu` view, as that's styled specifically for within Voyager.  The default should be using the `bootstrap` view, which shouldn't have any issues with styles.  If you leave it default, do you get any errors in your browser console?

**Comment by rddewan** [comment]
@fletch3555  thanks for your reply i have added the version detail as you have mention 
if i use  
{!! menu('main','bootstrap')!!}
the menu drop down is not working .Menu is showing drop down icon but when click on it nothing happens 
![menu1](https://user-images.githubusercontent.com/13164167/32150372-e730bd82-bd4c-11e7-85a4-1b59ab1b0e8e.jpg)

**Comment by fletch3555** [comment]
I don't see any version information.  Please try again (and make sure you click "Save")

Also, please answer the other questions I asked, specifically the one about browser console errors.

**Comment by rddewan** [comment]
Laravel Version: 5.5.19
    Voyager Version: 1.0.6
    PHP Version: 7.1
    Database Driver & Version: MySQL

**Comment by vaggelis2018** [comment]
@rijudewan there is already a menu on admin. Are you sure you adding the new menu items on the same menu? You don't need to use {!! menu('main','bootstrap')!!} again in the same menu. This is to render the menu once. For example in the front side of your website in the navbar.

**Comment by rddewan** [comment]
@vaggelis2018  I have created a menu as main in the voyager admin panel and i am calling that menu in the blade file on my user side  i am not menu to the voyager admin panel i am just call then new menu in by blade file 

thank you

**Comment by fletch3555** [comment]
Voyager provides the `menu()` helper solely as a way to build the markup for your use.  Implementing the functionality (i.e. dropdowns) is 100% on the developer, not Voyager, to implement.  We try to not be opinionated, or to provide too much, because that leads to a higher chance of conflict with your site.

In short, please do not try to use the `admin_menu` view in your site, it will not work.  Please leave off the view name and it will use the default `bootstrap` view.  If you need to customize that view, you can override it per our documentation.  If you use a different framework (i.e. angular, vue, etc), you're free to implement your own view file and use that instead.

I'm going to close this as it's not an issue with Voyager.
