### ISSUE TITLE
Does not create /public/storage/posts/date2017/image

### ISSUE THREAD

**Issue by Ifnir** [thedevdojo/voyager#2047]
- Laravel Version: 5.5.*
- Voyager Version: 1.0.5
- PHP Version: 7.*
- Database Driver & Version:

### Description:
Files exists in storage/app/posts/date2017.
The folder is not created in public/storage/posts/
Doesn't work doing "php artisan storage:link"

filesystem.php
`
'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
            
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/public/storage/',
            'visibility' => 'public',
        ],

`

### Steps To Reproduce:
No clue.

**Comment by Ifnir** [comment]
Solved:
Change 'root' => storage_path('app') to 'root' => storage_path('app/public/posts')

**Comment by fletch3555** [comment]
I'm guessing you're in shared hosting, or have otherwise installed Laravel inside the `public_html` directory (such that `/path/to/public_html/public/` exists).  If this is the case, then that's your problem, and I would strongly recommend changing how it's installed.  Keeping it that way exposes your .env file (at `domain.com/.env`, using your domain instead of `domain.com` of course)
