### ISSUE TITLE
Model Path change gives unauthorized error

### ISSUE THREAD

**Issue by SAM-AEL** [thedevdojo/voyager#2066]
- Laravel Version: 5.5.18
- Voyager Version:  1.0.5
- PHP Version: 7.0.22
- Database Driver & Version: MariaDB & 10.1.25

Description:
Try to change the default model path from bread. Then the browse and edit pages shows "unauthorized error". If change model path to default one, then it starts working again. Its a pain to edit the model from vendor folder everytime, wonder how to solve this issue (screenshot attached)

![Error](https://user-images.githubusercontent.com/14927758/31852437-43989c2a-b695-11e7-94b4-8aa79da5230c.PNG)

Steps To Reproduce:

**Comment by fletch3555** [comment]
When BREAD exists for a model/table, VoyagerServiceProvider will pull the model name from it and build out the policy definitions (https://laravel.com/docs/5.5/authorization#registering-policies).  I'm guessing you're changing the model namespace which is confusing Voyager because either the model doesn't exist in the old namespace anymore, or it doesn't yet exist at the new namespace.

You can try putting a copy of the model at both namespaces, changing the BREAD value, then deleting the one you don't need.  I can't guarantee it'll work, but it's worth a try.

**Comment by SAM-AEL** [comment]
@fletch3555 i did copy the model from voyager src models folder and tried on multiple locations.. everytime im getting same error if the path isnt the default one..  and the only page that doesnt work after change is the browse bread page

**Comment by moniquequines** [comment]
i'm having the same issue, also tried @fletch3555 solution but no success.

**Comment by ux-engineer** [comment]
I'm having a similar problem but after I had changed Users table's BREAD slug. It was left unnoticed during development and found now. Haven't yet figured out how to get it solved even with changing related settings to default ones for this table/bread.

**Comment by raoufOu** [comment]
you must make model in app folder
C:\laragon\www\gestionSalleVoyager2
λ php artisan make:model Adherant
Model created successfully.

**Comment by fletch3555** [comment]
This is a year old now, so I'm gonna close it.  If anyone still has this problem, please open a new issue
