### ISSUE TITLE
How display post in other language?

### ISSUE THREAD

**Issue by pieinn** [thedevdojo/voyager#2068]
Hi guys,
Voyager is super and easy to use!

Please advice how to display Post in multilingual project in different language?

My route -----
`Route::get('post/{slug}', function($slug){
	$post = App\Post::where('slug', '=', $slug)->firstOrFail();
	return view('post', compact('post'));
});`

post.blade ------
`<title>{{ $post->title }}</title>`
How to display post in other languages?

Thank you very much.

**Comment by AndCymru** [comment]
Don't bother with it just yet: there is no multi-language functionality in Voyager so far, see here: https://github.com/the-control-group/voyager/issues/1676

Nobody seems to bother, so for now Voyager is OK package for single-language content (with possible menus display in several languages).

**Comment by SAM-AEL** [comment]
you could add another column for another language on post table and use laravels inbuilt language feature to display right language post

**Comment by fletch3555** [comment]
@AndCymru, why do you say "nobody seems to bother"...? We definitely do have multi-lingual functionality, though there are definitely some limitations with it.

**Comment by AndCymru** [comment]
yes, you definitely have SOME multi-language functionality, namely l13n. you don't have i18n though - looks like you lost the ball somewhere in the middle of the game without knowing, whatever the reason.

there are 2 sides of the multi-lingual medal: localisation (AKA l13n) and internationalisation (AKA i18n).

with voyager, you can localise it, and have it in your own language.

but you can not have site in multiple languages. period.

it's a pity, this is a great package, i just love it. but i have to go with something else because of these "some limitations". more of it, because it has everything needed in the code, and partly (menu system) still works, and - presumably - would be relatively easy to fix. to me, it's how voyager saves translatables, somewhere in java core. whoever programmed it could probably spend couple of hours at most and fix it. but so far vayger stays unusable. :(

**Comment by fletch3555** [comment]
@AndCymru, I'm more than familiar with l13n vs i18n.  You haven't given any examples of things you can't do with Voyager. Instead, you've used hyperbole saying

> but you can not have site in multiple languages. period.

Perhaps it's just a language barrier, but your comments read with a tone of arrogant discontent.  Please list specific examples identifying the distinction between l13n and i18n, and what Voyager does not allow you to do.

**Comment by AndCymru** [comment]
see here: https://github.com/the-control-group/voyager/issues/1676

**Comment by akazorg** [comment]
@AndCymru 
> but you can not have site in multiple languages. period.

That is implemented, you are facing some bug. You are free to dive into the code, fix it, and share with us!!

Happy coding guys

**Comment by akazorg** [comment]
@AndCymru have you updated assets? the JS...
Please return... I'm curious.

**Comment by vaggelis2018** [comment]
@AndCymru I have already two websites with 2 languages. Everything is working fine and i didn't met any limitations at all. I think the point here to help @laraketai . Voyager is referencing to admin side. You can use an another package if you want for your front side like https://github.com/mcamara/laravel-localization
And return from your controllers the translated attributes as described here in issue #561 .

**Comment by akazorg** [comment]
Closing issue now. Multilingual is fully working.

**Comment by pieinn** [comment]
Thanks a lot for @vaggelis2018!!! Working fine!

**Comment by vaggelis2018** [comment]
Glad i helped @laraketai

**Comment by AndCymru** [comment]
hi, guys.
at some point it was eventually fixed.
after doing composer update - almost - everything works fine.
"almost" is because something weird happens to tinymce, which doesn't display html tags.
sure, i'm talking about admin part of the site all the time here, as voayger has nothing to do with frontend.
in the backend (i.e. voyager), if you go editing posts in several languages, post editor will show you body without any tags, both in reach-text view, and source code view.
BUT! all the tags are saved into database, tinymce just won't show them.
this is already something, at least i can live with it, maybe change tinymce for something else.. i don't know yet, didn't look into it yet.
thank you everyone for assisting, and good coding!

**Comment by vaggelis2018** [comment]
@AndCymru I think this was happening from a helper function which stripped out the html tags on translation

**Comment by PointfullDevelopers** [comment]
How can I get the content in other language? there is nothing in the documentation?

**Comment by AniltonMoraisJr** [comment]
How I translate a new table ? I try put the translate code in the right folder, but it didn´t work.

**Comment by AndrewHnidets** [comment]
https://github.com/the-control-group/voyager/pull/561

You can translate all model like: $post = $post->translate('locale', 'fallbackLocale');
After that $post->title gonna be at your 'locale'

If you need to translate specific model value - $post->getTranslatedAttribute('title', 'locale', 'fallbackLocale');

If you need to get current locale use - app()->getLocale()

GL :)

**Comment by fletch3555** [comment]
This has been closed for nearly 18 months and has gone untouched for ~9... please don't add comments to such old issues
