### ISSUE TITLE
[Feature Request] Ship by default with font awesome

### ISSUE THREAD

**Issue by kirtangajjar** [thedevdojo/voyager#209]
Also, I think it is a good idea to keep the link of the page with voyager fonts in menu builder form.
![image](https://cloud.githubusercontent.com/assets/8456197/20647525/56079bda-b4bc-11e6-90ec-979b35c0ba50.png)

**Comment by marktopper** [comment]
If I get it right, you would like to add this only to have some menu items with a font-awesome icon.
However then I would say that you add font-awesome to the front-end where your menu is gonna show. Then you can use font-awesome icons as well by inputting `fa fa-bolt`.

**Comment by kirtangajjar** [comment]
Well that can be done but it is a pretty common operation so I thought it would be nice to have them so that devs could have more of a "batteries included" experience. Also, they are pretty popular so chances are people are already familiar with their class names of icons.

Also, why was the link to voyager icons removed in menu builder that was in the window? That looks pretty helpful.

**Comment by marktopper** [comment]
You can input any icon class you wish, most likely this will be used with Font Awesome.
However in order for it to work you **must** add Font Awesome to the front-end where the menu will be shown.

About the remove of the icon link for Voyager icons, the answer is quite simple because that the Voyager icons are only available in the Voyager admin panel and **not** available in the front-end.

**Comment by handiwijoyo** [comment]
Hi, font-awesome was removed and replaced by Voyager font (see #56) to keep it minimal. 

However you still can add it to your own project if you want it.

**Comment by kirtangajjar** [comment]
@handiwijoyo Thanks, that explains it :+1:
