### ISSUE TITLE
Slow page loading

### ISSUE THREAD

**Issue by amc123-glitch** [thedevdojo/voyager#2103]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7
- Database Driver & Version:

### Description:
I have a fresh install of laravel 5.5 and this is my first time really working with the voyager package. I am noticing that straight from the setup instructions any link I click on the admin panel pauses for a bit then goes.

### Steps To Reproduce:

- fresh 5.5 laravel project
- follow the most recent voyager install/setup instructions
- login

**Comment by fletch3555** [comment]
We've had reports of slowness when dealing with significant quantities of data, but not with a bare install.  I won't outright dismiss your claim, but the issue is more likely with latency related to the machine you're on, network, or a number of other possible causes.  I can't say which without knowing more about your setup.  What DB are you using? Is it running on the same machine, or remote? Are you working in a local dev environment (i.e. on a laptop), or are you working on a remote server?  What browser are you using?  Does it happen in multiple browsers or on multiple machines?  Also, when you say it "pauses for a bit", do you mean "a moment", or "a few seconds"? There is a huge difference between the two.  Also, please post a screenshot of the network tab for your browser's dev tools.  I'm interested to see the timing for the request as it should help narrow down where the latency is.

**Comment by mushtaqj** [comment]
I am having the same issue, the pc is the local host, pages take time to load after a slight pause

**Comment by amc123-glitch** [comment]
@mushtaqj  details on your laravel version, voyager version, OS, and db would help them a little better

**Comment by mushtaqj** [comment]
@AnthonyMichaelc - I sorted it out, looks like this is an issue with my local pc rather than laravel, also xdebug seems to slow things down when it is enabled. So my comment is no longer relevant. Thanks for your willingness to iron things out
