### ISSUE TITLE
How to customize the admin panel?

### ISSUE THREAD

**Issue by OGhawsi** [thedevdojo/voyager#2108]
- Laravel Version: .5.5.*
- Voyager Version: latest
- PHP Version:
- Database Driver & Version: pgsql

### Description:
I would like to add a section in the admin panel in order to show all the messages sent by the users to the application.Any idea how can I do that.
Thanks in advance.

**Comment by fletch3555** [comment]
What do you mean by `add a section`? a new page, or a new section on an existing page?

If adding a new page, you can either work within the BREAD framework (check out our docs and [Voyager Academy](https://laravelvoyager.com/academy/) for further help), or you can add a new page just like any laravel application (create your own route, controller, and view).

If adding a new section on an existing page, you'll need to override the view to add it (then figure out how to get the data there).  Check our docs for assistance with overriding views.

Also, these kinds of questions are best asked on our Slack channel due to the high likelihood of conversation.
