### ISSUE TITLE
ErrorException after upgrading to 1.0

### ISSUE THREAD

**Issue by OctaneInteractive** [thedevdojo/voyager#2181]
- Laravel Version: 5.4.36
- Voyager Version: 1.0
- PHP Version: 7.1.11-1
- Database Driver & Version: MySQL 5.7.20

### Description:

I decided to upgrade Voyager to 1.0 and followed the [instructions](https://voyager.readme.io/docs/011-to-1).

When I then attempt to sign in I get:

> ErrorException
> Type error: Argument 1 passed to TCG\Voyager\Policies\MenuItemPolicy::checkPermission() must implement interface TCG\Voyager\Contracts\User, instance of App\User given, called in /var/www/project/vendor/tcg/voyager/src/Policies/BasePolicy.php on line 32 (View: /var/www/project/vendor/tcg/voyager/resources/views/menu/admin_menu.blade.php) (View: /var/www/project/vendor/tcg/voyager/resources/views/menu/admin_menu.blade.php) (View: /var/www/project/vendor/tcg/voyager/resources/views/menu/admin_menu.blade.php) (View: /var/www/project/vendor/tcg/voyager/resources/views/menu/admin_menu.blade.php)

The entire error is much more substantial, so if anyone needs that, let me know and I'll include it.

**Comment by fletch3555** [comment]
Your `User` model needs to `extends TCG\Voyager\Models\User`.  I believe it's in the documentation (though I don't remember if it was in the upgrade guide or elsewhere)

**Comment by OctaneInteractive** [comment]
Hi @fletch3555, are you recommending I edit files in Voyager itself?

**Comment by fletch3555** [comment]
No. Your app has a User model defined (likely App\User). You just need to change its parent class

**Comment by OctaneInteractive** [comment]
Hi @fletch3555, I got the error when signing in via Voyager itself, not anything I'd written.

**Comment by fletch3555** [comment]
That's exactly the change I meant.

As for the loading/spinny-wheel issue, I'm not sure.  Sounds like a JS error.  Anything in your browser console?  My guess is you're missing assets since v1.0 included a change to using Laravel Mix-compiled JS/CSS files.  If this seems accurate based on what you're seeing, then just run `php artisan vendor:publish --force` (optionally including a `--provider` or `--tag` option to limit what gets published)

For the logout exception, that makes sense since that route is defined as POST only (check `php artisan route:list`)

**Comment by OctaneInteractive** [comment]
In the end, I had to start from scratch with a snapshot on AWS.

The one thing I didn't do this time is copy-and-paste from the migration files to the ones I already had, so that could have played some part, perhaps?

Yes, the spinning wheel thing was something to do with JavaScript.

Everything's working now.

@fletch3555, thank you.

**Comment by fletch3555** [comment]
No problem.  Glad you got it working
