### ISSUE TITLE
tinymce and filemanager use together

### ISSUE THREAD

**Issue by secondnetwork** [thedevdojo/voyager#2234]
I am looking for a solution to tinymce and filemanager in post use together

![fzdjsgfdjsgshjgfdjs](https://user-images.githubusercontent.com/13808106/32849409-58166904-ca2f-11e7-8028-3e84391cdbaf.png)

**Comment by vFire** [comment]
I hope this could be a selectable option not a must, because sometimes we don't want to organize the files in media libary manually, just want the file attached to the document, once the document is removed then the related file or picture is also be removed, thus will make the system simple and clean, anyway linke the tinymce 's uploding to media library is surely another good feature for some other circuments.

**Comment by fletch3555** [comment]
A complete rewrite of how Voyager handles uploaded files/images is on our roadmap.

**Comment by ctf0** [comment]
@fletch3555 what do u think of using https://github.com/ctf0/Laravel-Media-Manager and maybe create a plugin/module to connect voyager with it ?

**Comment by fletch3555** [comment]
That looks like an enhanced copy of ours (visually at least).  We're not opposed to making use of another package, but no decisions have been made yet on implementation.
