### ISSUE TITLE
Tables are too wide for container

### ISSUE THREAD

**Issue by Tropicalista** [thedevdojo/voyager#2247]
- Laravel Version: 5.5.21
- Voyager Version: 1.0.6
- PHP Version: 7.0.10
- Database Driver & Version:

### Description:

Users table, Roles table, Posts table and other table that use DataTable are too wide for the container. I suppose this is due to extra row class added.

### Steps To Reproduce:

Go to http://127.0.0.1:8000/admin/posts

**Comment by fletch3555** [comment]
Depends 100% on your screen resolution and how many fields you have in those tables.  Voyager can't force it to be 100% width of the container without scrolling because then you'd potentially have columns that are 10px (or some other ridiculously small size) wide.  Voyager can't possibly know how wide your table is going to be, so it can't provide a CSS solution for it.

Do you have a proposed solution?

**Comment by Tropicalista** [comment]
In my widescreen 1920x1080 and fresh install without additional columns it shows an horizontal scrollbar.

I see that each table row is inside a `div class="row"` that add margin. I think removing thos calasses solve the problem.

**Comment by fletch3555** [comment]
Can you provide a screenshot of what you're seeing? 1920 should be way more than enough to show the table with default fields.

**Comment by Tropicalista** [comment]
![view](https://user-images.githubusercontent.com/1663035/32970518-9e39014c-cbe9-11e7-8cca-4f52fcbec11d.png)

**Comment by fletch3555** [comment]
Ah, that's a CSS box model issue, not a table width issue.  What browser are you using? Does it behave the same with another browser?

**Comment by Tropicalista** [comment]
Same on firefox and IE

**Comment by dfk7677** [comment]
The problem is caused by the negative (-15px) margin introduced by the `.row` CSS class (Bootstrap) of the div(s) inside the data table.

This can be rectified by the following change in [app.scss (line 1004)](https://github.com/the-control-group/voyager/blob/master/resources/assets/sass/app.scss#L1004):
```scss
.dataTables_wrapper .row {
  margin-bottom: 0.5em; }
```
To:
```scss
.dataTables_wrapper .row {
  margin-bottom: 0.5em;
  margin-left: 0;
  margin-right: 0; }
```
@fletch3555 Do you want me to make a pull request?

**Comment by fletch3555** [comment]
Yes, please do @dfk7677

**Comment by dfk7677** [comment]
[PR](https://github.com/the-control-group/voyager/pull/2265) done @fletch3555 . I am not sure if I shouldn't have submitted the compiled [app.css](https://github.com/dfk7677/voyager/blob/master/publishable/assets/css/app.css) though.

**Comment by fletch3555** [comment]
Perfect, thanks.  Yes, we do want the compiled app.css, since we don't have a CI pipeline set up to recompile it.
