### ISSUE TITLE
Why the JavaScript file is too heavy?

### ISSUE THREAD

**Issue by Hujjat** [thedevdojo/voyager#2249]
- Laravel Version: 5.5.*
- Voyager Version: 1.*
- PHP Version: 7.1.*
- Database Driver & Version:

### Description:

It's a wonderful project. I just looked at the asset files. The app.js file is almost 1.6Mb. And for performance, it's too heavy. Is there any way to decrease the size? besides, every feature should work as well. 

Thank's

**Comment by fletch3555** [comment]
It's only used for Voyager, not for your app, so it's REALLY not that bad.  Having said that, yeah, we know it's a bit bloated.  It's currently holding all of the JS dependencies in one file (jquery and more), which is why it appears so large.

There isn't too much we could do without breaking out the dependencies into their own file (then we'll have something like a 1MB file, and a 0.6MB file, which doesn't save you all that much).  It'll take a complete top-down review and refactor to change that, which isn't something we're prepared to do right this moment, but we certainly appreciate your concern.
