### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by wilsilva** [thedevdojo/voyager#2258]
How collaboration with project ?

**Comment by fletch3555** [comment]
For a rough overview: https://opensource.guide/how-to-contribute/

More specific to Voyager, just look for issues marked "Help Wanted" or anything else that seems interesting (but check with the maintainers before working on issues that seem controversial or otherwise have no response to them).  Specifically (but not covered by issues here), we need the most help with fleshing out phpunit tests and documentation.

Please feel free to join our Slack group with further questions.  There a a ton of knowledgeable devs on there that have been with the project for quite a while.

**Comment by wilsilva** [comment]
Thanks!
