### ISSUE TITLE
Voyager login always "These credentials do not match our records." in shared hosting.

### ISSUE THREAD

**Issue by ianyusuf** [thedevdojo/voyager#2260]
- Laravel Version: 5.4
- Voyager Version: Latest
- PHP Version: 5.6.32
- Database Driver & Version:

### Description:
I am getting the error "These credentials do not match our records." every time I log in to the admin route. It works fine on the localhost, but when it comes to the shared hosting, I fail to go through the authentication.

### Steps To Reproduce:
It works fine on the localhost:
![image](https://user-images.githubusercontent.com/21698752/33055339-9f9122a2-ceb1-11e7-8887-669f7978ab3c.png)
![image](https://user-images.githubusercontent.com/21698752/33055360-c2691226-ceb1-11e7-9e47-703e708e892f.png)

But it didn't work in shared hosting. (In this case I used niagahoster.co.id):
![image](https://user-images.githubusercontent.com/21698752/33055391-fd81281c-ceb1-11e7-97d1-5ab06cb95c2b.png)

"These credentials do not match our records." error always appear. I already checked the user table and the username, password, and email are right. What should I do with this case? Should I change something in ENV or Routes file? or in another file? Thankyou.

**Comment by MohsinNadeem** [comment]
Try checking user permissions in your database. Alternatively, you can try creating a new user from terminal.

**Comment by fletch3555** [comment]
Open up dev tools and make sure the redirect path is correct (make sure you're not getting in then kicked back out for some reason).  Make sure your user has a role with the `browse_admin` permission set correctly (a "quick fix" for this is to run `artisan voyager:admin <your email>`, which will auto-assign all permissions to the `admin` role, and assign that role to your user).  Additionally, please make sure your session configuration is correct, since authentication requires a valid session be stored.

I'm sure you've already done this, but please check the logs to see if anything useful got caught.

**Comment by ianyusuf** [comment]
So should I install the composer in the shared hosting here? Or I can run the php artisan voyager:admin in the local then I deploy to the hosting? What file should I check and I change?

Here is the user role in my DB:
![image](https://user-images.githubusercontent.com/21698752/33107188-aef05f94-cf68-11e7-8b32-86fe20f85111.png)

 Btw, where can I find the logs lol sorry I'm still new to Voyager.

**Comment by fletch3555** [comment]
Voyager is built on top of Laravel, and requires a reasonable understanding of how Laravel works in order to understand and work with Voyager.

With that said, the logs are for laravel, not specific to voyager, and are located in `storage/logs`.  You should get your site working locally before moving to a hosted environment, but if you're looking at shared hosting, you're likely going to have a ton of issues (all of which can be google'd for solutions, none of which should be Voyager-specific).

**Comment by ianyusuf** [comment]
Oh I see, sorry. I still don't know what's the problem, because all the MVC for the view is doin alright, but the admin page (which is I'm using voyager) isn't working. I'm still learn how to hard code in Voyager tho, thanks for the help. I'll check the log again.

**Comment by cyrildewit** [comment]
Is this still an issue? Otherwise, this can be closed.

**Comment by fletch3555** [comment]
Closing due to age.  If this is still an problem for you, please open a new issue with updated information.
