### ISSUE TITLE
Use another table name instead of `users`.

### ISSUE THREAD

**Issue by pkitatta** [thedevdojo/voyager#2271]
- Laravel Version: 5.5
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version: MYSQL

### Description:
Hi, is it possible to specify another table name instead of the default `users` table? I would like to name my table `admins` and not `users`.

I apologise if this is a repeat question.

**Comment by fletch3555** [comment]
Renaming the table is easy.  Edit the migration (or add a new one doing the rename), then add a `$table` property on your `User` model with the new table name.

If you want your model class to match the table (i.e. `App\Admin` instead of `App\User`), then you'll have to do a little more work.  In `config/app.php`, you have to change the user model path, as well as in `config/voyager.php`.  I'm sure there are other steps, but I can't think of them at the moment.  Try what I've suggested and if you still have issues, let me know.

As a side note, implementation questions are best asked on our Slack group.  Github issues should be reserved for issues with Voyager's code.

**Comment by pkitatta** [comment]
Hi @fletch3555, so I managed to rename the table to admins and even tried to create a user. Whereas the user was created successfully in the database, i got this error:

```

C:\xampp\htdocs\hangoutAdmins>php artisan voyager:admin paul@test.com --create

 Enter the admin name:
 > paul

 Enter admin password:
 >

Creating admin account


  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'voyager.users' doesn't exist (SQL: select * from `users` where `users`.`id` = 1 limit 1)



  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'voyager.users' doesn't exist



  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'voyager.users' doesn't exist



C:\xampp\htdocs\hangoutAdmins>
```

It talks about table `voyager.users` not existing. Any thought?

**Comment by fletch3555** [comment]
Likely either the command doesn't play nicely with that change, or you have the config set improperly (in `config/voyager.php`

**Comment by pkitatta** [comment]
made another fresh installation created an admins table and specified this in the App\Users model.

On creating a user I get this:
![image](https://user-images.githubusercontent.com/17586059/33208146-799abb54-d121-11e7-8b35-b7c4e67b31d2.png)

The record is created in the database without role_id in the admins table.

On trying to sign in from the website I get this:

![image](https://user-images.githubusercontent.com/17586059/33208242-da236b60-d121-11e7-9c6a-d44f91f12867.png)
