### ISSUE TITLE
Create public BREAD User

### ISSUE THREAD

**Issue by mateushackfaccat** [thedevdojo/voyager#2309]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: -

### Description: 

I'm new to Voyager. I ask for a little patience. I need to create a public user registry for new users to do this. But looking at the BREADController, and the Voyager Documentation, it was not clear to me how I call this record in a VIEW outside of browse.blade.php and edit-add.blade.php. I've even followed the documentation and created a View Test (https://voyager.readme.io/v1.0/docs/overriding-views), but it's all blank. I do not know how to specify which table it needs to fetch the data to display in the View. Within the DATABASE MENU, BREAD is working, but the user must be logged in to access.

**Comment by fletch3555** [comment]
I'm not exactly sure what you're trying to do, but it doesn't sound like what Voyager was built to do.

Voyager is intended to be an ADMIN tool, and due to the functionality it contains (database CRUD actions), it should definitely be secured behind an auth system, not public.  It sounds like you're looking for a scaffolding tool, which voyager isn't.  What you CAN do, however, is build the page yourself and access the data through Eloquent models, just like any other Laravel app.

**Comment by mateushackfaccat** [comment]
Got it, I'm testing it this way. I thought I could use a public register of users outside the validation area!

**Comment by fletch3555** [comment]
"public register of users"... like just a list of all users in the site/app? Sure, just use something like `App\User::all()` in a page you build.  Then you have full control over the route, middleware(which is what's doing the auth check), controller, and view.

**Comment by mateushackfaccat** [comment]
Ok! I will try it!

**Comment by fletch3555** [comment]
Okay, I'm going to close this for now.  If you have further questions, I recommend joining our Slack group.  There are quite a few devs on there that would be more than happy to help you figure it out.

**Comment by mateushackfaccat** [comment]
Which Slack chat link?

**Comment by fletch3555** [comment]
It's in our README: https://voyager-slack-invitation.herokuapp.com/
