### ISSUE TITLE
ASK[overwrite the posts bread]

### ISSUE THREAD

**Issue by mlazuardy** [thedevdojo/voyager#2321]
- Laravel Version: latest
- Voyager Version: 1.0.7
- PHP Version: 7.1
- Database Driver & Version: php myadmin 4.7.0

### Description:
So i want to overwrite the Posts table and its Bread,
i want to configure the status of the post, it default is DRAFT, and if i change it to published, the user will get increment of COIN "in user table" for n, how to overwrite this table and the bread too?

**Comment by fletch3555** [comment]
* Adding fields to existing tables can be done with a migration or through the Voyager database editor.
* Adding fields to Voyager's form pages can be done by editing BREAD through Voyager.  If custom views (e.g. `pages/*.blade.php`) are used instead of the default views (`bread/*.blade.php`), then you will need to update the view file for your new fields as well.
* If you want to customize controller functionality, you can extend the existing controller, change the functionality to meet your needs, then edit the BREAD to use the new controller.

All of this is documented (poorly in some cases) in [our documentation pages](https://voyager.readme.io/docs)
