### ISSUE TITLE
belongsToMany relationship bugfix

### ISSUE THREAD

**Issue by manjana** [thedevdojo/voyager#2355]
- Laravel Version: 5.4.*
- Voyager Version: 1.0.*
- PHP Version: 7.0.22
- Database Driver & Version:10.0.31-MariaDB-0ubuntu0.16.04.2

### Description:

belongsToMany relationship dont delete from pivot table all relations 

### Steps To Reproduce:

create belongsToMany relationship add some relations and try to delete them from voyager interface

bug is in

/vendor/tcg/voyager/src/Http/Controllers/Controller.php on line 57
`if (!$request->hasFile($row->field) && !$request->has($row->field) && $row->type !== 'checkbox') {
           continue;
}`
 
My fix is
`if(!$request->hasFile($row->field) && !$request->has($row->field) && $row->type !== 'checkbox' && (!empty($row->type) && !empty($options->type) && $row->type !== 'relationship' && $options->type !== 'belongsToMany')) {
                continue;
            }`

**Comment by fletch3555** [comment]
What are you trying to fix...? We need more detail than "I had an error, this is what I changed to fix it"

**Comment by manjana** [comment]
I not said "I had an error, this is what I changed to fix it"
i wrote exactly line of logical bug and problem in belongsToMany relationships to reproduce.

belongsToMany relationship in voyager 1.0.* doesnt delete all relations from pivot table when trying to delete (sync) all of them (post arriving empty and `if` is skipping empty relation)

Belongs to many relation has pivot table
users - table (id,name)
books - table (id,book_name)
and pivot table user_books (pivot_id,user_id,book_id)
attach some data to pivot table for them and save.
you can reproduce bug detaching all data from pivot table
**DATA NOT BE DELETED** it's a bug
bug is on /vendor/tcg/voyager/src/Http/Controllers/Controller.php on line 57

`$row->type !== 'relationship' && $options->type !== 'belongsToMany' `
are skipped on `continue` line 58 
i wrote my fix in previous post.

**Comment by fletch3555** [comment]
There are 2 ways to handle deleting related data.  Either you do it through code, or you set ON DELETE on the foreign key relationship in the database.

The first option requires Voyager to know you want to do that, or for you to add code in the model to do that.  If Voyager does it, it becomes opinionated and someone else complains because they don't want it to work like that.  Or you add it to your model, and well, you own the model class, so that's all you.

The second option is configured when creating the table/foreign key, so likely in your migration.  Perhaps Voyager's database editor should give that as an option in the UI, or perhaps you should be creating migrations anyway for the sake of moving between environments or getting other devs set up.  What I'm saying is that you're free to add this yourself.  We'll consider pull requests if someone wants to add that option to the UI, but honestly it's not high on our priority list.

Given this description, I hope you can see how this isn't a bug in Voyager.  At most, it's just a feature that hasn't been implemented yet.
