### ISSUE TITLE
Mysql error and Page Not Found when Install

### ISSUE THREAD

**Issue by Chriswu92** [thedevdojo/voyager#2367]
- Laravel Version: 5.5
- Voyager Version: 1.0.9
- PHP Version:7.0
- Database Driver & Version:
Mysql 5.7.11
### Description:
sth wrong in install.

### Steps To Reproduce:
After I set AppServiceProvider.php file,
```
use Illuminate\Support\Facades\Schema;

public function boot()
{
    Schema::defaultStringLength(191);
}
```
 then
 execute 'php artisan voyager:install',
the error : Syntax error or access violation: 1071 Specified key was too long

and after create admin user,
localhost:8000/admin 'Page Not Found'

**Comment by fletch3555** [comment]
Have you tried searching the repo for that error? Sounds like you've already used the common solution , but there is an additional issue that triggers that error (Voyager uses a unique key that ends up being too long still).  The issue is that your mysql version needs to be updated.  If that's not possible, then there are a couple solutions that have been posted here in the past.  I'm mobile otherwise I'd try to look it up for you
