### ISSUE TITLE
Update CRUD on GUI and migration was not updated

### ISSUE THREAD

**Issue by skalero01** [thedevdojo/voyager#2375]
- Laravel Version: 5.5.25
- Voyager Version: 1.0.9
- PHP Version: 7 
- Database Driver & Version:

### Description:
I just update the CRUD (Add a field) for pages and it just add the colum on the table but the migration was not updated.

I think that the idea of having migrations is to be updated always in case we want to replicate it on another sites, are you planning to add this feature? Do you need some help? 

Regards

**Comment by fletch3555** [comment]
Voyager does not touch migrations.  If you have migrations, it's because you wrote them or they're default from Voyager.  Also, it's bad practice to change migrations unless still in active development (e.g. the site has not been shared with others or pushed to production).  This is because Laravel keeps track of migrations that have already run, so a modified one will not be re-run unless you manually do so (with `artisan migrate:refresh` or similar)

**Comment by skalero01** [comment]
Maybe it should create a new migration to modify the columns, but everything depends on the version of the site.. as you said

So, you really not interested at all to add this feature?
