### ISSUE TITLE
Too many redirects on login

### ISSUE THREAD

**Issue by nickbryan** [thedevdojo/voyager#2448]
- Laravel Version: 5.5
- Voyager Version: 1.x-dev
- PHP Version: 7.2
- Database Driver & Version: 

### Description:
I am using the dev branch to start development of a new project which will use the multi roles feature. For some reason, after a successful login, I get ERR_TOO_MANY_REDIRECTS in chrome. I have removed the /admin prefix so my admin panel us just under the /root (i have done this on 1.0 without issues) not sure if it's related.

Could you also tell me when you expect the next official release to launch including these features?

### Steps To Reproduce:
* Log into the admin panel on the 1.x-dev branch

**Comment by nickbryan** [comment]
Ah it was because my user did not have browse_admin permission. Although when this is the case it redirects back to / causing the infinite redirect.

**Comment by fletch3555** [comment]
yes, Voyager uses Laravel's default auth framework, and the default guard.  Due to this, it accepts all valid authentication attempts, then redirects unauthorized requests to the root of the domain.  Voyager is intended to be at a sub-path (though it's configurable which subpath you choose).  Moving it to the root will  MOSTLY work, but you may run into issues like you describe.  It'll take custom work to avoid those issues.  We likely won't be changing that anytime real soon.

Anyway, glad you figured out your problem.

**Comment by nickbryan** [comment]
Hi @fletch3555 thank you for the reply. Do you have a release date in mind for the 1.x dev branch? I know its hard to say at the moment, just looking for an estimate. We have started a new project and I am currently working of the dev branch for the multi role functionality. I am a bit concerned where this will leave me when the new version is released so I am debating starting again on the 1.0 branch and doing the upgrade when the new release is stable. Unfortunately I need this functionality pretty quickly. If you have any recommendations that would be great. My main worry is with the publishable vendor stuff and if I am making changes how that will effect me when it is released.

**Comment by fletch3555** [comment]
I don't recommend working on 1.x-dev since it's still accepting breaking changes.  With that said, you're free to do whatever you'd like, it'll just be hard for us to properly support you since you're not on a stable release.

I don't currently have a date in mind, but I expect it will likely be sometime in the next 3-6 weeks.  We have a lot of testing and documentation to add, and a handful of features that are still in the works.

**Comment by nickbryan** [comment]
Thats great news. I have restarted the project on the 1.0 branch as per your recommendation. Your timeline seems very reasonable and we should be able to manage that also. Thanks again for the reply and for the work you guys are putting into this
