### ISSUE TITLE
Error when login in Voyager with PostgreSQL 9.6

### ISSUE THREAD

**Issue by Camilo-Sistemas** [thedevdojo/voyager#2465]
- Laravel Version: 5.5.28
- Voyager Version: 1.0
- PHP Version:
- Database Driver & Version: PostgreSQL 9.6, on CentOS 7.2

### Description:

SQLSTATE[22P02]: Invalid text representation: 7 ERROR: la sintaxis de entrada no es válida para integer: «browse_admin» (SQL: select exists(select * from "permissions" where "permissions"."id" = browse_admin) as "exists") (View: /proyectos/laravel/inv2016/vendor/tcg/voyager/resources/views/menu/admin_menu.blade.php) (View: /proyectos/laravel/inv2016/vendor/tcg/voyager/resources/views/menu/admin_menu.blade.php) (View: /proyectos/laravel/inv2016/vendor/tcg/voyager/resources/views/menu/admin_menu.blade.php) (View: /proyectos/laravel/inv2016/vendor/tcg/voyager/resources/views/menu/admin_menu.blade.php)

### Steps To Reproduce:
Hi, well... I just install voyager follow documentation and create a user by:
    php artisan voyager:admin admin@admin.com --create

then i enter description and password... and all is OK, user is created; but when I tray to login ocurrs the error.

**Comment by klrkdekira** [comment]
According to stacktrace
```
"select exists(select * from "permissions" where "permissions"."id" = ?) as "exists""
array:1 [▼
  0 => "browse_admin"
]
```
The column queried should be `permissions.key` instead of `id` (which is an integer).

The query assumes `permissions.key` to be the primary key, but the above situation occurs because `permissions.id` is actually the pkey. 
Here,
https://github.com/the-control-group/voyager/blob/1.0/src/Policies/MenuItemPolicy.php#L40
```
        // If permission doesn't exist, we can't check it!
        if (!Voyager::model('Permission')->whereKey('browse_'.$slug)->exists()) {
            return true;
        }
```

Turned out it's patched, time to update I supposed.
https://github.com/the-control-group/voyager/issues/2475.

I think this issue can be closed.

**Comment by fletch3555** [comment]
Agreed, this was patched in the latest release.
