### ISSUE TITLE
Prevent 'htmlentities' when posting to database.

### ISSUE THREAD

**Issue by nanadjei** [thedevdojo/voyager#2530]
I want to add new pages to a system am building using 'voyager pages' creator. When I get to the body and input html data, it gets escaped before posting to the database. And I want to prevent that. how do I do that please ?

**Comment by fletch3555** [comment]
All input should be escaped when submitted to the database, and unescaped when displayed in a view.

Sounds to me like you're submitting HTML markup into the normal rich text editor field, instead of it's "source" tab.  The rich text editor is essentially a WYSIWYG editor, so of course it will encode your data.  You will need to open the "source" view (apologies, but I don't have a screenshot for you) and paste your markup there.
