### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t   oo long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by mithublue** [thedevdojo/voyager#2540]
- Laravel Version: 5.5.32
- Voyager Version: 1.0
- PHP Version: 
- Database Driver & Version: 7.0.10

Description: When I go to install the package with the command

 php artisan voyager:install --with-dummy

In comman prompt, it is seen that, it publishes the voyager assets, database, language, config file successfully.  And also migration table created successfully. But after that, this error is found 

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 1000 bytes (SQL: alter table `translations` add
  unique `translations_table_name_column_name_foreign_key_locale_unique`(`tab
  le_name`, `column_name`, `foreign_key`, `locale`))

In PDOStatement.php line 107:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 1000 bytes

In PDOStatement.php line 105:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 1000 bytes

Note that : this error different from the default string length error. I have already set the default string length in AppServiceProvider.php in boot method like the following

Schema::defaultStringLength(191);

Steps To Reproduce:

1) Install laravel 5.5
2) Include the voyager package
3) Set the necessary config as directed in voager doc
4) Run the comman 'php artisan voyager:install --with-dummy'

And the error will be shown in the command prompt that you are using.

**Comment by fletch3555** [comment]
Did you search the project? https://github.com/the-control-group/voyager/search?q=Syntax+error+or+access+violation%3A+1071+Specified+key+was+too+long%3B+max+key+length+is+1000+bytes&type=Issues&utf8=%E2%9C%93

There are a few possible solutions:
1. Upgrade your database to at least MySQL 5.7.7(or mariadb 10.2.2), since this is (reportedly) only an issue with older versions
   * https://github.com/the-control-group/voyager/issues/1840#issuecomment-332299930)
2. Change your database configuration
   * https://github.com/the-control-group/voyager/issues/901#issuecomment-291470960
   * https://github.com/the-control-group/voyager/issues/1158#issuecomment-296154146
   * https://github.com/the-control-group/voyager/issues/1333#issuecomment-309006094
