### ISSUE TITLE
i dont want to redo on production server all the things i did on local 

### ISSUE THREAD

**Issue by sath26** [thedevdojo/voyager#2553]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version:7.1
- Database Driver & Version: MySQL

### Description:
From Admin Panel
1. I can create model(i wont need any other code from laravel eloquent for it to work other than making model)
2.make breads
3. then feed them on views using loop

but then i have push to bitbucket to deploy on server so i wont have vendor folder
on server i will have to use composer install the packages
now will the things i did on local server will be brought back on production?

###For deployment:
i dont want to redo all the work
i made migrations manually to later on to  add tables on server database. but i cant figure out how i will save bread that i did on local.

PS. i havent tested this on production server. i am telling this based on the assumption that i have to reinstall voyager in server and i cant find where my change are saved other than vendor folder.

**Comment by fletch3555** [comment]
You have a few options to pick from, and they've all been discussed at length in other issues here as well as on Slack.

1. Do a database export and import to production.  This will include all of the BREAD information as well
2. Use a package that gives you an Artisan command to create migrations and/or.  Most of these packages have the caveat that they only do FULL tables, and can't do incremental updates.
3. Write the migrations/seeders yourself.  You'll just need a tool to look at the database and some free time.  This isn't ideal if you're trying to add one new row somewhere, since that's easily recreated through the UI.

We're looking at implementing this feature, but haven't found a good way to do it yet.

**Comment by SamDeacon** [comment]
so wait, the simplest way to push a near-finished-voyager-app to production is going to be an sql dump clone?

**Comment by fletch3555** [comment]
Simplest, sure.  In the sense that it's the least number of commands to run.

To be more complete, your app should really be making use of migrations and/or seeders anyway, so you could just as easily use another package to generate those for you.
