### ISSUE TITLE
Register & Reset Password ,

### ISSUE THREAD

**Issue by allaghi** [thedevdojo/voyager#2563]
- Laravel Version: 5.5.32
 -Voyager Version: 1.0
- PHP Version:
- Database Driver & Version:

### Description:

I am wondering if there are these features come with voyager , (registration & reset password )

Thanks in advance

**Comment by fletch3555** [comment]
They do not, because you should not be registering for the admin page of your site.  Voyager should simply be accessed, with access being granted by another admin.  If you lose access to all admin accounts, you can simply promote a new one with the `voyager:admin` Artisan command.

That being said, Voyager uses the default authentication guard of Laravel's built-in auth framework, so if you need registration for your site, just create it.  Laravel docs will be most helpful with this.

**Comment by allaghi** [comment]
okay , I understand your view about registration section, how about forget password @fletch3555 . even if voyager for admin section. it has to have forget password, like WordPress
