### ISSUE TITLE
Validation errors for rich text editors not showing

### ISSUE THREAD

**Issue by apsg** [thedevdojo/voyager#2578]
- Laravel Version: 5.5.33
- Voyager Version: 1.0.14
- PHP Version: 7.1
- Database Driver & Version: mysql

### Description:

For a custom table I created a BREAD with several rich text fields. These fields cannot be null (and in BREAD manager there is info: Required: YES) but still, I can try to save new item to the database (and get mysql error "field xxx cannot be null").

Following [this](https://voyager.readme.io/docs/validation) I've added validation rule for these rich textboxes:

`{
    "validation": {
        "rule": "required",
        "messages": {
            "required": "This field is required"
        }
    }
}`

but it only prevents me from saving new item to the DB when the field is empty - it does not show any kind of error/message. Also, on validation, there are js errors showing in console:

`An invalid form control with name='description' is not focusable.`
`An invalid form control with name='about' is not focusable.`

I suppose it's some kind of issue related to using tinymce rich text editor. How can I make ANY kind of message showing on failed validation?

**Comment by abacram** [comment]
Yes, apparently it's related with validateBread function from Controller.php. Validations are running with $row->display_name instead $row->field. I recommend you to wait for a release with the fix, but if you're hurry for now, i had to override /vendor/tcg/voyager/src/Http/Controllers/Controller.php and make a fix to validateBread in order to get working in my local until the fix is released.

P.D.: i don't recommend you to make any changes into the tcg vendor files, because you may lost them when you try to update or mount your project in another environment/machine.

**Comment by apsg** [comment]
This issue was solved by https://github.com/the-control-group/voyager/pull/2660 in release 1.0.16, so it can be marked as closed.
Thank you!

**Comment by fletch3555** [comment]
Thank you for following up.
