### ISSUE TITLE
Change image upload path 

### ISSUE THREAD

**Issue by carefreeav09** [thedevdojo/voyager#2669]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version:7.0
- Database Driver & Version:

### Description:
The images uploaded using Voyager follow the path, "menu-item-name/monthYear/image.ext" in the database. How can i change the image path to just 'image.ext'?  

I tinkered around with VoyagerController and VoyagerMediaController inside the vendor directory, changed the filesystems, but couldn't change the path.

**Comment by fletch3555** [comment]
Please save yourself some trouble and avoid changing things in the vendor directory.

**Comment by carefreeav09** [comment]
I'm only doing it to learn, so i can take that risk. I know changing the things in the vendor directory would eventually disappear when i update composer or change dependency. But it would help me understand the controllers better.

**Comment by vblinden** [comment]
I don't think this is possible at the moment. You can make a pull request to add this functionality?

**Edit:** #2581

**Comment by b4dnewz** [comment]
is possible to change the disk for one BREAD only?

For example I have a table called "downloads" which should store references to private files but by default they are saved in "public" directory that is public accessible since **voyager.storage.disk** by default points to the public folder.

I would like to have that uploaded files in a non-accessible directory and then serve them manually after some auth and roles verification.

If I change the **voyager configuration** to:
```php
'storage' => [
    'disk' => 'private',
],
```
where **private** is a custom defined disk like so:
```php
'disks' => [
       'private' => [
          'driver' => 'local',
          'root' => storage_path('app/private'),
          'url' => env('APP_URL').'/storage',
          'visibility' => 'private',
        ],
]
```
it will alter all the uploads in every BREAD not only the table that I need and probably the Media section too, which will become private by conseguences.

I thought to extend the BREAD controller, use a custom one or override the [voyager/resources/views/formfields/file.blade.php](https://github.com/the-control-group/voyager/blob/f6e0a1055d091a4da43ffa7c77e2f0b95bdc5377/resources/views/formfields/file.blade.php) template but I don't know extracly how to do it and if is the right thing to do.

Any idea or suggestion about this? Thanks in advance.

**Comment by emptynick** [comment]
This will be possible in version 1.2.
See (https://github.com/the-control-group/voyager/pull/3889).
