### ISSUE TITLE
How to check same product name to add products in Voyager

### ISSUE THREAD

**Issue by reach2rahulbharti** [thedevdojo/voyager#2672]
I want to restricted to add product name which have already exist with same name...

**Comment by defaultpage** [comment]
Hi! You can use next [validation rule](https://voyager.readme.io/docs/validation) in your bread options:
```json
{
    "validation": {
        "rule": "unique"
    }
}
```

> Basically you just have to lowercase display names (Assuming they are identical) like name/Name order/Order.

**Comment by reach2rahulbharti** [comment]
@ArtemMolotov  I want to check the condtion with already inserted data in table....

**Comment by fletch3555** [comment]
@reach2rahulbharti, @ArtemMolotov's answer is correct.  You could also do it with a "UNIQUE" constraint on the database column, but that will just throw errors instead of displaying user-friendly messages.  However, the UNIQUE constraint will likely complain if you try to add that when the data is not unique currently.  If you're trying to clean up duplicate data (after adding the unique validation rule), you can try something like this: https://stackoverflow.com/a/13146595.  This question was for MS SQL Server specifically, but it should translate to MySQL or PostgreSQL fairly easily.

**Comment by reach2rahulbharti** [comment]
{
    "validation": {
        "rule": "unique"
    }
}
This Validation Rule did'nt Work....

**Comment by defaultpage** [comment]
Can you show your bread display names? Voyager have some errors with validation at this moment. You just have to lowercase display names (without spaces etc).
> Basically you just have to lowercase display names (Assuming they are identical) like name/Name order/Order.

**Comment by reach2rahulbharti** [comment]
@ArtemMolotov Please check this link of my bread page

![image](https://user-images.githubusercontent.com/36505183/36308553-30ec4d92-1347-11e8-9471-c8d9638215d8.png)

![image](https://user-images.githubusercontent.com/36505183/36308590-54be7a7e-1347-11e8-9c99-345bfdcb7722.png)

**Comment by reach2rahulbharti** [comment]
I want to add distinct Category name...

**Comment by defaultpage** [comment]
Validation will be working if you set `category_name` as display name or you can fork current project with #2660 pull request.

**Comment by reach2rahulbharti** [comment]
after change display name...we unble to edit and add category name....
it shows following error

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'resource_guide.rg-category' doesn't exist (SQL: select count(*) as aggregate from `rg-category` where `category_name` = Testing Categary and `id` <> 13)

**Comment by defaultpage** [comment]
I think this error is not related to the changed display name. Please, check your table name.

**Comment by reach2rahulbharti** [comment]
I have change display name same as table name ....now problem is fix....thanks for support
