### ISSUE TITLE
Asian menu item titles cause drop downs in the admin menu to misbehave

### ISSUE THREAD

**Issue by ssang** [thedevdojo/voyager#2688]
- Laravel Version: 5.5.13
- Voyager Version: 1.0.5
- PHP Version: 7.1.9
- Database Driver & Version: MYSQL MariaDB-10.2.9

### Description:
Korean Language in the titles for parent menu items in the admin menu causes drop downs to misbehave. The ID that is set to the parent menu item does not include the title if the title as korean in it. If there are multiple drop downs that include Korean, there will be multiple dropdown IDs so that only the first one toggles.

### Steps To Reproduce:
This may be true for all Asian or Foreign characters but I've only done it with Korean.

1) Create a menu Item with a korean title: 한국말
2) Add some child items
3) Create another one with a korean title: 대한민국
4) Add some child items. 
5) Try the open the second drop down in the side bar.

**Comment by emptynick** [comment]
That is likely because the collapsible id is the slug of the menu-title. See [here](https://github.com/the-control-group/voyager/blob/1.0/resources/views/menu/admin_menu.blade.php#L65).  
`echo str_slug('한국말', '-');` echoes an empty string.
`echo str_slug('대한민국', '-');` also is empty.  
So jQuery/Bootstrap doesnt know which collapsible should be toggled.  
I think the best way to fix this is to use the ID of the `menu_item` instead of the title-slug

**Comment by fletch3555** [comment]
I believe you're correct @emptynick.  Likely just needs a new `map_` method: https://github.com/the-control-group/voyager/blob/1.0/resources/assets/js/slugify.js#L112

**Comment by emptynick** [comment]
No, the slug isn't generated by JS, but by Laravels `str_slug` method.
https://github.com/the-control-group/voyager/blob/1.0/resources/views/menu/admin_menu.blade.php#L46

**Comment by fletch3555** [comment]
crap... yeah, you're right... we should probably have the same implementation on both sides, for consistency.

**Comment by t0rjan** [comment]
fixd this problem. code in https://github.com/the-control-group/voyager/issues/2786

**Comment by t0rjan** [comment]
This can be fixed in this way: https://github.com/the-control-group/voyager/issues/2787
