### ISSUE TITLE
[model]::withTranslation() problem

### ISSUE THREAD

**Issue by mchrapka** [thedevdojo/voyager#2716]
- Laravel Version: 5.6.5
- Voyager Version: 1.0.16
- PHP Version: 7.1.9
- Database Driver & Version: MySQL

### Description:
Using withTranslations() and getTranslatedAttribute(...) returns bad results

### Steps To Reproduce:
I'm developing two-language ('en' and 'pl') application.

I want to get offers with translation using:
```
$offers = App\Offer::withTranslations()->get();
```

Generated SQL query is:
```
select * from `translations` where `table_name` = 'offers' and `locale` in ('pl', 'en') and
`translations`.`foreign_key` in ('1', '2', '3', '4', '5', '6') and `locale` = 'pl' or `locale` = 'en'
```

This gives me ALL rows from translations table having `locale = 'en'` (includes translations from all tables)

When I use: `$offer->getTranslatedAttribute('slug', 'en')` I got translation from another table.

I think query should end with brackets:
```and (`locale` = 'pl' or `locale` = 'en')```

The same problem is with withTranslation().

**Comment by fletch3555** [comment]
This line is causing the `table_name` and (first) `locale` check:
https://github.com/the-control-group/voyager/blob/1.0/src/Traits/Translatable.php#L35

However, when you run `withTranslations()`, it actually calls this scope, which adds the `or`:
https://github.com/the-control-group/voyager/blob/1.0/src/Traits/Translatable.php#L56

This is definitely not expected behavior.  Thank you for pointing it out.
