### ISSUE TITLE
BREAD editing results in a 405 (Method Not Allowed)

### ISSUE THREAD

**Issue by SturmB** [thedevdojo/voyager#2721]
- Laravel Version: 5.6.5
- Voyager Version: dev-1.x-dev
- PHP Version: 7.2.2
- Database Driver & Version: MySQL 5.7.21 Homebrew

### Description:
Editing the BREAD for any database table results in three 405 errors appearing in the console:

![screen shot 2018-02-23 at 1 03 44 pm](https://user-images.githubusercontent.com/6216224/36609295-64f7d540-189a-11e8-86f2-5b99eb1f07e9.png)

### Steps To Reproduce:

1. Fresh installation of Laravel 5.6 & Voyager dev-1.x-dev.
2. Create admin account (unless Voyager was installed with dummy entries).
3. Log in to Voyager.
4. On the sidebar, click on "Tools", then "BREAD".
5. Open the dev console in your browser.
6. On any table for which BREAD has already been created, click on the "Edit BREAD" link.
7. Check your console.

**Comment by fletch3555** [comment]
~I... I have no idea why that's broken, but I get it too.  It's caused by the ajax-populated dropdowns in the relationship modal.  They're trying to do a GET to `/admin/bread/[breadName]`, which isn't a valid route.  At this point, I can't tell if the route was deleted (though I can't tell what controller method would've been called, so that must've been deleted as well), or if the code that generates that route changed (much more likely, though I don't see where)~

Edit: found it.
