### ISSUE TITLE
unable to display multi-level menu. While clicking sub menu it is de-activate suddenly.. i dnt know why.

### ISSUE THREAD

**Issue by rajesh12kumar** [thedevdojo/voyager#2789]
- Laravel Version: 5.4
- Voyager Version: 1.0
- PHP Version: 7.0.13
- Database Driver & Version:
MySQL & 5.6.17

### Description:
unable to display multi-level menu in a Voyager's admin panal. While clicking sub menu it is de-activate suddenly.. i dnt know why.

**Comment by marktopper** [comment]
What menu are you talking about? The admin menu or any other menu layout?
Cause it is known that the admin menu only supports 2 levels.
We are open to pull requests.

**Comment by fletch3555** [comment]
@rajesh12kumar, first, all version information is required when opening issues.  This provides the context necessary for us to help you.

For your question, as @marktopper mentioned, we'll need more information.  Voyager's admin menu currently supports 2 levels (main/root level, and one level of children).  If you are trying to add a 3rd level, you will have to customize it (please open a pull request if you do, because that's been requested a few times).  If you're trying to make other menus function this way, that will be up to you to implement the JS for..

**Comment by yalks** [comment]
vendor\laravel\framework\src\Illuminate\Support\helpers.php 
 找到 str_slug 方法 改成
`function str_slug($title, $separator = '-', $language = 'en')
    {
        return $title;
    }`

**Comment by emptynick** [comment]
Pretty sure that this was fixed in https://github.com/the-control-group/voyager/pull/2798
