### ISSUE TITLE
Multilingual pages

### ISSUE THREAD

**Issue by Tirliton** [thedevdojo/voyager#2860]
- Laravel Version: 5.5.34
- Voyager Version: 1.0.15
- PHP Version: 5.6.30
- Database Driver & Version: libmysql - 5.1.73

### Description:
Hi,
I installed Voyager and I created a multilingual website. I try to use the multilingual functions of Voyager with the pages table. The translations are stored in the translations table and everything works fine. My question is : how can I get the right content (in the right language) in the front end of my website ?

I created a controler for the pages, which select the page in the pages table. But how can I select the content in the other languages ?

Here is my PageControler show function:

```
class PageController extends Controller {
    // Show a page by slug 
    public function show($slug = 'home')
    {
        $locale = App::getLocale();

        $page = DB::table('pages')
            ->select('title', 'body', 'meta_description', 'meta_keywords')
            ->where('slug', '=', $slug)
            ->first();

        return view('pages.index')->with('page', $page);
    }
}
```

Any idea ?

Thx for your help !

**Comment by fletch3555** [comment]
Use the [model class](https://github.com/the-control-group/voyager/blob/1.0/src/Models/Page.php#L12) instead of querying the database directly.  The model already includes translated fields for `title`, `slug`, and `body` automatically.  Feel free to extend this class in your own project if you need more.

In the future, "how to" style questions are best asked on our Slack group.  We prefer to save the Github issues for bugs and feature requests.
