### ISSUE TITLE
Custom controllers and views not working; how to set up subdirectories for controllers and views

### ISSUE THREAD

**Issue by larry-tx** [thedevdojo/voyager#2877]
- Laravel Version: 5.5.39
- Voyager Version: 1.0
- PHP Version: 7.2.2
- Database Driver & Version: mysql 5.0.12

### Description:
Attempting to use Voyager in the creation of a complex Web application with many tables. In the past I have organized controllers, models, and views using many subdirectories to avoid having hundreds of files in individual directories. For instance, the Entities models directory will ultimately have Entity, EntitiesEntityCategory, EntitiesEntityRole, EntitiesEntitySource, EntityCategory, EntityRole, EntitySource, EntityType in it. The HealthCare models directory will have just as many models in it. Likewise for the HomeAutomation models directory. I'm trying to find a way to make this work in Voyager, and it may well be that Voyager just isn't up to it.
### Steps To Reproduce:
1. Create directory Apps\Http\Controllers\Entities
1. Change controllers namespace in voyager.php to read `'namespace' => 'App\\Http\\Controllers\\Entities'`.
1. Changes models namespace in voyager.php to read `'namespace' => 'App\\Models\\Entities'`
1. Generated a EntityType.php model using `php artisan make:model EntityType`
1. Run `php artisan voyager:controllers`
1. Add directory `Resources\views\vendor\voyager\entity-types` (`entity-types` is the URL slug for the entity_types table)
1. Attempted to create BREAD for the entity_types table using EntityTypesController for the controller name.
1. Ran/submitted to create the BREAD.
1. Received a "Success" message in response to the submission.
1. Checked the relevant directories for controllers and views. Absolutely nothing whatsoever had been created in those directories. Nothing whatsoever, despite the "Success" message. Also, check every possible directory where the controller and views might have been created. Nothing. Did a search for the controller in the entire Web site directory (parent above App). Nothing.

###Questions
1. Is there a way to create custom controllers and views? I attempted to follow in great detail your instructions in the docs and it doesn't seem to work.
1. How would you recommend proceeding to create and organize a complex Web site with many models/controllers/views files like this.
1. Is there any way to get a valid response when submitting a BREAD specification that fails? The "Success" message is hardly helpful.

**Comment by fletch3555** [comment]
First of all, THANK YOU for providing so much detail.  We've gotten so used to seeing "[x] is broken... fix?" type issues that provide absolutely no useful information.

With that said, I think you've misunderstood how Voyager works.  Voyager does not create all these Models, Views, and Controllers for you.  It will create Models for you (at the fully-qualified namespace provided in the form) if you toggle the right switch while creating the BREAD, however it will not create Controllers or Views.  Instead, Voyager uses a common "default" controller and view files that all BREAD types use IF a more specific one isn't found.  If you want to use a custom controller, it's up to you to create it (likely extending the default one), and configure it in the BREAD settings.  If you want custom views, it's up to you to create them (likely copy/pasting from the defaults), and placing them in the directory mentioned by the docs.

To touch on a few comments in your issue description...

1. I get the impression you're an old-school developer that's used to rigid structure in your applications, most likely due to corporate style guides.  Laravel certainly doesn't require this, and therefore Voyager does not either.  In fact, following such a rigid structure may make developing with Laravel/Voyager MORE difficult as they don't necessarily follow Laravel conventions, and therefore block some of the "magic" from working automatically.
2. I strongly advise against using the `artisan voyager:controllers` command, as it's bound to be removed.  It's purpose was to automatically publish controllers to your App directory and change all needed settings so that Voyager will continue to function.  With the addition of the `Controller` field in the BREAD settings, this command serves little or no purpose.
3. As stated previously, controllers and views will not be automatically generated in your App directory, nor will they be generated in the vendor/tcg/voyager directory either.  Instead, Voyager will use TCG\Voyager\Http\Controllers\BreadController (or BaseController in v1.x-dev, soon to be v1.1) for all BREAD types that do not have a configured controller.  Additionally, Voyager will use `vendor/tcg/voyager/resources/bread/*.blade.php` as the default view files.

Voyager was not originally built for such a large app (assuming the scale is as big as you make it seem), though that doesn't mean it won't be able to handle it.  If you have further questions, please feel free to join our Slack group and we can talk further.  You'll likely get a much faster response on there.
