### ISSUE TITLE
Upload Multiple Images error

### ISSUE THREAD

**Issue by piterog** [thedevdojo/voyager#2887]
- Laravel Version: 5.4
- Voyager Version: v1.0.13
- PHP Version: 7
- Database Driver & Version:

### Description:
When I'm trying to upload multiple images using voyager I have this message:

> Unsupported image type. GD driver is only able to decode JPG, PNG, GIF or WebP files.

How you can see, some images erase the datatype... and all images are .jpg
![apagar](https://user-images.githubusercontent.com/6227151/37859986-7daea9ca-2efb-11e8-921d-11b253fd9bd1.JPG)

### Steps To Reproduce:
1. Upload images

**Comment by fletch3555** [comment]
Simply having a `.jpg` extension does not make it a `JPEG` file.  Please confirm the files are actually jpeg files

**Comment by piterog** [comment]
Yes sir.. all files are jpeg file.

**Comment by piterog** [comment]
Hey guys, i have some news.. there are specific images that can not be sent, at first they are normal .jpg, but they do not send anyway, does anyone have an idea of the problem?

**Comment by kylemilloy** [comment]
I had this issue and it turned out the upload_max_filesize in php.ini was too small which fixed the issue after I shrunk the file. Did this solve it for you?

**Comment by piterog** [comment]
@kylemilloy thanks for the answer man, but still the same error :( Don't work to me

**Comment by kylemilloy** [comment]
Hmmmm...I'd check your **upload_max_filesize** and **post_max_size** just to be sure that any of the two aren't limiting you. 

If you change the limit don't forget to restart php so the changes take effect.

**Comment by piterog** [comment]
Yeh i have do this... post_max_size = 0;
and upload_max_filesize i have commented...

The problem still the same upthere!

**Comment by kylemilloy** [comment]
By default upload_max_filesize is 2M...if you've commented it out this will be what the value is. Set it to something a little more reasonable like 32M, 128M, etc. I notice you've got a file that you're uploading called "picjumbo"...how "jumbo" are we talking? What's the file size?

Restart php again and run phpinfo (either via command line or with a .php file) to confirm that the new value is being used...something like `php -i | grep upload` If the upload_max_filesize isn't being set then it's being overwritten somewhere else...we'll cross that bridge if we come to it...

**Comment by emptynick** [comment]
I'm pretty sure that this is not the problem. Otherwise PHP/Laravel would die with a `PostTooLargeException`

**Comment by kylemilloy** [comment]
@emptynick - Not sure if you're replying to me or not but if so you're confusing upload_max_filesize with post_max_size. Besides, `post_max_size=0` means infinite...not zero. 

`upload_max_filesize` tells PHP what the max size allowed of individual files are
`post_max_size` tells PHP what the max size of any post is, as this is set to 0 it's infinite (up until PHP runs out of memory at least). 

And no, when I had this same issue pop up today it was failing due to upload_max_filesize being too small. Took a *long* time and a bit of luck to find that out as all the logs said otherwise.

@piterog - another thing to try is one image at a time and see which image(s) causes the backend to choke. From there we can narrow down the search...do all images fail or just specific ones, is there a corruption in the mimetype that's causing it to break, does re-encoding fix it, removing the exif data, etc.

**Comment by kylemilloy** [comment]
Pic for proof....

doesn't error out with post too large...
![screen shot 2018-05-02 at 4 05 48 pm](https://user-images.githubusercontent.com/15757117/39551642-0ae56d4c-4e23-11e8-88a5-4f6b4e22011b.png)

**Comment by emptynick** [comment]
True that, I always confuse those two.
Anyway, for me when the image size is between `upload_max_filesize` and `post_max_size` it just doesn't update the picture, not throwing an Exception (using single image, not multiple, maybe thats why I cant replicate it)
Edit: yeah that seems the be the problem

**Comment by kylemilloy** [comment]
And I think I found why...

If you look in `Http\Controllers\ContentTypes\Image` the first line in the handle function is `$this->request->hasFile`. In `Http\Controllers\ContentTypes\MultipleImage` we don't have this inside the for loop (or anything to check that the file is indeed an image)...therefore it fails the upload with this exception instead of failing silently.

I would suggest we add a similar check into MultipleImage in the for loop...or a try catch...or just validate its mimetype and skip it if it's not an image (same behaviour as single image)...however some proper exception handling may be in order here as failing silently with no logging isn't great...up to the core team how they want to implement that...I'll write a PR if necessary...can amend it later to add proper logging...

Doing a dd on the file that gets uploaded shows that because it's a partial upload when the upload limit isn't high enough it gets marked as an octet stream...therefore not an image...therefore no overflow error and instead Intervention chokes on it.

**Comment by piterog** [comment]
@kylemilloy the scene is: My bride exports the photos in photoshop, all the same, some work perfectly, and others give this error I showed up. When I pass the erroneous photo in a compactor, like a tinypng.com, the new compacted photo, works well.. In Windows OS, if I look at the image property, 
there is the type JPG normally. I don't know why. Thank you buddy

**Comment by kylemilloy** [comment]
Congrats on your marriage. 

Judging by the symptoms your issue is definitely the max upload setting. You will need to increase your upload limit in your php.ini file. We can probably close this ticket and if you like I can walk you through changing this setting and fixing it for your specific environment...reach out to me on [telegram](https://telegram.org/), my username is @kylemilloy...we can troubleshoot there.

**Comment by piterog** [comment]
@kylemilloy i have tested here, and this is.. **upload_max_filesize**

**Comment by msdavid1296** [comment]
@piterog 
Hi,
I too had the same problem. It is because of the corrupted images. You can handle it by code.

**Comment by piterog** [comment]
Hey @msdavid1296 my problem was **upload_max_filesize**, I increased the value of the variable and everything went back to normal!

**Comment by msdavid1296** [comment]
Fine :)

**Comment by jessmancia** [comment]
Did you find any solution? I have the same problem.

**Comment by kajan746** [comment]
change following variables in php.ini file

>     post_max_size = 128M
>     upload_max_filesize = 128M

print phpinfo() to find your php.ini location.

If its cpanel its under software section->php versions-> click on "Switch To PHP Options" . Then change the value. 
Also change the `max_execution_time` to `600`

**Comment by chiragpipariya** [comment]
I also facing the same issue "JPEG" file is not supported. 

{message: "Unsupported image type. GD driver is only able to decode JPG, PNG, GIF or WebP files.",…}
message: "Unsupported image type. GD driver is only able to decode JPG, PNG, GIF or WebP files."
exception: "Intervention\Image\Exception\NotReadableException"
file: "/home/site/wwwroot/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php"
line: 59
