### ISSUE TITLE
Use of permission_groups

### ISSUE THREAD

**Issue by xaviqv** [thedevdojo/voyager#2895]
- Voyager Version: 1.0

What is the meaning or the planned functionality for permission_groups table?

**Comment by emptynick** [comment]
Without knowing it better I'd say theres no planned functionality, because it was dropped again in 1.x
See https://github.com/the-control-group/voyager/blob/1.x-dev/migrations/2017_11_26_014010_drop_permission_groups_table.php
And the original PR https://github.com/the-control-group/voyager/pull/736
The roles-system was completely changed in 1.x anyway
