### ISSUE TITLE
Can not upload post when image not selected

### ISSUE THREAD

**Issue by aozen** [thedevdojo/voyager#2936]
- Laravel Version: 5.5.*
- Voyager Version: Last Version
- PHP Version: 7.2.2
- Database Driver & Version: Last v.

### Description:
When trying to upload. It request it says image not selected. But i am upgrading the posts. I didn't need to select an image again. But there must be an image. I was added 
`{
    "validation": {
        "rule": "required|image"
    }
}` 
Is this about me? Or voyager issue. I don't know.  If anyone suggest any solution. I will be glad. Thanks in advance.

**Comment by fletch3555** [comment]
Since the field is marked "required", a value must be set when submitting the form.  File upload fields don't get assigned file objects when values exist in the database.  There's really no good solution here.  You'll have to create a custom validation rule for it to check for an existing database value to know whether to check if it's "required".
