### ISSUE TITLE
belongsToMany relationship with itself column specification

### ISSUE THREAD

**Issue by lqchinh88** [thedevdojo/voyager#2951]
Laravel Version: 5.5.28
Voyager Version: 1.0
PHP Version: 7.1.14
Database Driver & Version: MySQL 5.6.35

### Description:

I have a `Company` table and pivot table `Company_stakeholding_company`. A company will have many stakeholding companies. When I specify belongsToMany relationship in Voyager, there's no way to specify second column named `stakeholding_company_id` , it will assumes 2 columns in pivot table both are `company_id`. 
In `data_rows` table, the details of relationship is 
`{"model":"App\\Company","table":"companies","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"company_stakeholding_company","pivot":"1"}`

How do I specify 2 columns in the pivot table ?

**Comment by neurotools** [comment]
Same problem here with News that have "Related News".

**Comment by fletch3555** [comment]
Voyager does not currently support self-referencing many-to-many relations due to the field name conflict.

We're open to pull requests

**Comment by MrCrayon** [comment]
Since this is still a problem this is a work around I suggested that was reported as working:

- ~Make a view `stakeholding_companies` of `companies`~
- Create a Model `StakeholdingCompany extends Company` **(should use the same table)**
- Create a relationship from `Company` `belongsToMany` `StakeholdingCompany`, ~you need to select `company` as table because views are not listed, but that's only used to get field list.~
- Select your pivot table `company_stakeholding_company`
- Enjoy
