### ISSUE TITLE
Extending existing Data Types

### ISSUE THREAD

**Issue by amrittb** [thedevdojo/voyager#2990]
- Laravel Version: 5.4.30
- Voyager Version: 1.0.17
- PHP Version: 5.6
- Database Driver & Version: MySQL

### Description:
The existing data types (Posts/Pages/Users) used in Voyager are perfectly fine for many applications. However, some applications may require only adding a few fields on the tables for the data types. What is the best way to extend the existing data type?

**Comment by MrCrayon** [comment]
I don't know if it's the best way but, create your model:
```php
<?php

namespace App\Models;

class AlmostPost extends \TCG\Voyager\Models\Post
{
    //change what you want
}
```
Then you need to tell voyager to use your model in your AppServiceProvider boot method:
```php
Voyager::useModel('AlmostPost', \App\Models\AlmostPost::class);
```
and in bread configuration.

I'm not sure if both changes are always needed but I do it like that.

**Comment by fletch3555** [comment]
In addition to what @MrCrayon suggested, I'd just like to add that Voyager doesn't ship with a `User` model.  Instead, we use the default one from the Laravel Auth scaffolding (from `artisan make:auth`), and just modify it with a contract and trait.  You're free to add whatever you need to that model since it belongs to your app.

**Comment by amrittb** [comment]
Thanks for your input on this. Also, to update the actual database of existing datatypes would it be better through migrations or the database system in Voyager. I generally prefer migrations as they can be version control. Would this create any sort of problems in Bread system?
