### ISSUE TITLE
symlink(): No such file or directory

### ISSUE THREAD

**Issue by bryanezavala** [thedevdojo/voyager#2991]
- Laravel Version: 5.5
- Voyager Version: 1.1
- PHP Version: 7.2
- Database Driver & Version: MySQL

I have uploaded my application to a shared hosting, the laravel files are in the root: `/home/creatipp/laravel` and the public folder is found in `/home/creatipp/public_html/creatipcenter.com`
I hope you can help me.

![001](https://user-images.githubusercontent.com/33789256/38910453-fa4f7210-428e-11e8-8003-c4c826a2c2e4.jpg)
![002](https://user-images.githubusercontent.com/33789256/38910454-fa6e8ea2-428e-11e8-93c0-a232aafbeb25.jpg)

**Comment by Picl0u** [comment]
The same for me...

**Comment by fletch3555** [comment]
Your Laravel install is non-standard, which is the cause of this.  Voyager uses `public_path()` to check for the symlink.  By default, this method returns `/path/to/laravel/public` (where `/path/to/laravel` is `/home/creatipp/laravel` in your case).  Since you've moved the `public` directory, you have to tell Laravel how to find it again, which can be done by overriding the `path.public` singleton in the DI container.  There are numerous posts about this online, and this is outside the scope of this project, so I'll let you do a bit of research on your own.
