### ISSUE TITLE
Sorting for formatted date

### ISSUE THREAD

**Issue by AstralProgrammer** [thedevdojo/voyager#3096]
- Laravel Version: 5.5.40
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: mysql 14.14

Date entries with format of %d-%m-Y are not treated as dates but string instead whenever sorted on the browse / listing.

I've created a DATE new column via BREAD. Set column to have DATE field and format of dd-mm-yyyy on the listing page. 

Having it formatted in yyyy-mm-dd and mm-dd-yyyy get sorted just fine.

**Comment by MrCrayon** [comment]
If you are not using server side pagination, ordering is done by DataTables.
Its supported date formats depend from browser used but it's usually ISO8601, that's why yyyy-mm-dd works.
If you want other formats to work you'll need to extend DataTables.
I'm not sure if you can do it just adding js or if you'll need to customize the browse view.
You can check it here: https://datatables.net/blog/2014-12-18
