### ISSUE TITLE
Drap-and-drop to change image index on Multiple Images?

### ISSUE THREAD

**Issue by hungxinh** [thedevdojo/voyager#3110]
- Laravel Version: 5.5 -> 5.6
- Voyager Version: 1.0.17 -> 1.1
- PHP Version: 7.X
- Database Driver & Version:

### Description:
Edit a saved Product/Post, I want to drag-and-drop to change the position of the 3rd image to the second position, and the second image to the 3rd position.
Can Voyager add this feature?
![screenshot 2018-05-01 16 41 52 copy](https://user-images.githubusercontent.com/23396671/39468981-0c32336a-4d60-11e8-9974-c6175ad0877f.png)

**Comment by fletch3555** [comment]
I can't tell what you're doing with this.  "Changing" images requires an "upload", which is why the file selector is there.  We COULD get fancy and allow drag/drop uploads (from your computer to the browser) like some other platforms have, but that doesn't seem to be what you're asking for.  Your image seems to show you dragging the image away from the image list, which could mean anything.

Please provide more information than just an image.  Here's one of many helpful blog posts on how to write useful issues on github: https://upthemes.com/blog/2014/02/writing-useful-github-issues/

**Comment by hungxinh** [comment]
Edit a saved Product/Post, I want to drag-and-drop to change the position of the 3rd image to the second position, and the second image to the 3rd position.
Can Voyager add this feature?

Sorry @fletch3555 , my english is not good!

**Comment by fletch3555** [comment]
Ah, so it's reordering, not creating.  That's partly my fault (I didn't see "index" in the issue title).

We're certainly open to pull requests for this.

**Comment by hungxinh** [comment]
Thank you.

**Comment by jannescb** [comment]
Anything new on this topic? Reordering images seems to be pretty essential for many projects.

**Comment by emptynick** [comment]
Yep. Use the media-picker. It allows you to reorder the selected items.

**Comment by jannescb** [comment]
> Yep. Use the media-picker. It allows you to reorder the selected items.

Thanks, I must have missed that. 
Now I am missing the thumbnail option - am I able to use it with the media-picker?

**Comment by emptynick** [comment]
Not currently.
I'd be happy to review a PR implementing this.

**Comment by seanmgd** [comment]
> Yep. Use the media-picker. It allows you to reorder the selected items.

Please what is this media picker ?

i saw it is mentioned on this link 
https://docs.laravelvoyager.com/core-concepts/bread-builder#media-picker
but i did not find this parameter on my bread editor.. please help me

**Comment by emptynick** [comment]
It was implemented in version 1.2.
So if you are on a version below that you wont see it.
@jannescb thumbnails were implemented in 1.2.4
Closing this as I hope that the media-picker will replace image/multiple images and files in the future.
