### ISSUE TITLE
Call to a member function relationLoaded() on null after updating an administrator

### ISSUE THREAD

**Issue by agus24** [thedevdojo/voyager#3134]
- Laravel Version: 5.6.17
- Voyager Version: 1.1
- PHP Version: 7.2.4
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.22

### Description:
role id at users table become null after edited an administrator user (like edit name, picture, password) so that trigger this error.

![image](https://user-images.githubusercontent.com/23353234/39641861-e8afec1a-4ff9-11e8-829a-aead541ce598.png)

here's some error from mysql when i try to access users table

![image](https://user-images.githubusercontent.com/23353234/39641984-52992b64-4ffa-11e8-9044-1ab72e66ce7d.png)

i dumped the data and this is the result : 
![image](https://user-images.githubusercontent.com/23353234/39643341-aa644de8-4ffe-11e8-85ea-2d5aa471a906.png)

step to reproduce : 
1. install voyager with dummy
2. try to edit default user

**Comment by Siarhei-Sudakou** [comment]
confirm

**Comment by fletch3555** [comment]
Please search before opening issues: https://github.com/the-control-group/voyager/search?utf8=%E2%9C%93&q=Call+to+a+member+function+relationLoaded%28%29+role&type=Issues

Also, accurate version info is required for us to appropriately support you.  Are you on Voyager v1.1.0 or v1.1.1?

I ask, because v1.1.1 includes a fix to this (#3014) already.
