### ISSUE TITLE
All additional roles can't be removed

### ISSUE THREAD

**Issue by carlost89** [thedevdojo/voyager#3140]
- Laravel Version: 5.5.40
- Voyager Version: 1.1
- PHP Version: 7.0.28
- Database Driver & Version: 5.7.22

### Description:

When I try to remove all additional roles from an user, the additional roles remain the same. When I removed one additional role but not all, the changes are storaged.

### Steps To Reproduce:
Remove all additional roles from an user.
Save changes.
Additional roles remain the same.

**Comment by fletch3555** [comment]
This is because when you remove them all, the browser doesn't send the field in the POST, so the Controller doesn't see it and doesn't update the field.  @emptynick, we should fix this.

I'm thinking empty hidden field populated by JS from the selected value(s) of the dropdown. This can be used everywhere we have this issue(which seems to keep cropping up

**Comment by emptynick** [comment]
This will be fixed with either #3016 or #3020.

**Comment by vblinden** [comment]
I think #3112 fixes this issue also @fletch3555 @emptynick

**Comment by emptynick** [comment]
Fixed in #3016.
Merged into 1.x
