### ISSUE TITLE
Missing required parameters for [Route: /] 

### ISSUE THREAD

**Issue by maharjan-sunil** [thedevdojo/voyager#3142]
- Laravel Version:5.6
- Voyager Version: 
- PHP Version:
- Database Driver & Version:mysql

Missing required parameters for [Route: /] [URI: post/{id}]. (View: E:\intern\vendor\tcg\voyager\resources\views\dashboard\navbar.blade.php)

**Comment by emptynick** [comment]
Please provide more informations, like the version fields and steps to reproduce, e.g. where you encounter this error and so on.
Otherwise we are not able to help you.
Once you filled those details, we can reopen this issue.

**Comment by maharjan-sunil** [comment]
php 7.2.4 
i face the error when i try to login

**Comment by fletch3555** [comment]
You still haven't provided the most important version, Voyager.

Also, a full stacktrace would be the most help

**Comment by nstaff** [comment]
I know the issue is closed, but I'm answering in case someone else googles this error.

I had a similar issue yesterday. The likely problem is that you have a database entry on your posts table that does not have an ID associated with it. Your route is looking for the parameter '/posts/{id}' and its saying that its missing that parameter. Possibly because you are using the `action()` helper in your navbar.blade.php. This means that the blade engine cannot build the view because it is missing the route (all routes must exist for them to build).

Recommend combing through your database, or hard coding the URL in your navbar (temporarily) until you can do more debugging.

**Comment by yohio** [comment]
I am aware of the issue being closed and all but for me, the fix was to add the following line to the class object:

protected $primaryKey = 'whatever';

This fixed it for me because the table I was trying to create BREAD for had no column of ID and had a different primary which the system then got confused about.
