### ISSUE TITLE
Images, media Issu

### ISSUE THREAD

**Issue by KyryloGrygorenko** [thedevdojo/voyager#3149]
- Laravel Version: 5.4.
- Voyager Version: ^1.1
- PHP Version: 5.6
- Database Driver & Version:
MySql
### Description:
After launching the app from local to the server all images are not visible. The url of the image is 
src="http://mysite.com/storage/users/May2018/Tq4bqKXAHMVGtMt6WNWV.jpg". In my root directory which is /public I do have the /storage directory but it has only .gitignore file.  I've tried APP_URL=http://127.0.0.1:8000   Doesn't help
APP_URL=http://ubb.st.php-academy.org  Doesn't help
Please help! Thank you!
![voyager_image_issue](https://user-images.githubusercontent.com/25619186/39716725-c4a1015a-5239-11e8-924d-772bda6e3de5.jpg)

**Comment by fletch3555** [comment]
APP_URL needs to be the URL to your site, including port.  Also, your site can't live in a subdirectory (e.g. `http://domain.com/path/to/laravel`) What's the URL to your site?

**Comment by KyryloGrygorenko** [comment]
The Url to my site is http://ubb.st.php-academy.org.  I've tried http://ubb.st.php-academy.org:8000 also.

**Comment by KyryloGrygorenko** [comment]
I've found out where the files that I have uploaded had been stored. It is storage/app/public/
![files_being_saved_here](https://user-images.githubusercontent.com/25619186/39717926-5f32c232-523d-11e8-919e-96d8aa246e47.png)

**Comment by KyryloGrygorenko** [comment]
I've found out where the files that I have uploaded had been stored. It is storage/app/public/
![voyager_image_issue](https://user-images.githubusercontent.com/25619186/39718059-d1e4e832-523d-11e8-820e-69ed97b6fa5e.jpg)

**Comment by KyryloGrygorenko** [comment]
I've found out where the files that I have uploaded had been stored. It is storage/app/public/
![files_being_saved_here](https://user-images.githubusercontent.com/25619186/39718092-e5f7a67a-523d-11e8-867e-e6cea8b25c8b.png)

**Comment by fletch3555** [comment]
Your APP_URL needs to change to the domain (use the commented-out one in your screenshot).  While we're on the topic, `.env` does NOT use HTML-style comments, so please get rid of that.

By default, Voyager uses Laravel's default `public` filesystem (`config/filesystems.php`).  This can be changed, but you might as well understand how it works first.

In short, Laravel will generate links to files at the path of `/storage/path/to/file.ext`.  Through your web browser's configuration, this will equate to the file at `/path/to/laravel/public/storage/path/to/file.ext`, where `storage` is a symlink to `/path/to/laravel/storage/app/public`.  Please make sure this is the case (if it's not, your Voyager dashboard will have a banner informing you of this.

Laravel knows how to generate links like this because of the "disk" configuration in `config/filesystems.php` ([ref](https://github.com/laravel/laravel/blob/master/config/filesystems.php#L51)).  This config has a `root` key which says where to write files to, and a `url` key which says how to generate URLs.

You're free to change this configuration however you'd like, but check the Laravel docs since Voyager doesn't do anything specific in this regard.

**Comment by KyryloGrygorenko** [comment]
Thank you for your help! This is what I have in filesystems.php 
![filesystems](https://user-images.githubusercontent.com/25619186/39751122-de747a4a-52bf-11e8-985c-42a336b1548c.jpg) . But I didn't get the point what needs to be changed in order to make the 
the links to the images work. The URL that is generated for the user avatar is http://ubb.st.php-academy.org/storage/users/May2018/ZYnEvsUSwt3WLEfmkMJ6.jpg. 
![voyager_avatar](https://user-images.githubusercontent.com/25619186/39751322-7a6bc2aa-52c0-11e8-92ac-77207766671b.jpg) . I still don't have an idea what am I doing wrong. I appreciate your help!

**Comment by KyryloGrygorenko** [comment]
Looks like I finally found the way to make it work. In the filesystems.php


![image](https://user-images.githubusercontent.com/25619186/39767431-6e23f06a-52ef-11e8-9765-7b91ba01b90d.png) 
Thanks for all your help and prompt responses! Voyager is a cool product!!!

**Comment by wakasann** [comment]
Laravel Version: 5.4.
Voyager Version: ^1.1
PHP Version: 5.6
Database Driver & Version: MySql

@fletch3555 thank you for your detailed answer,i have same issue at show avatar ,i  try change my `config/filesystems.php` file

```
'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage/app/public',
            'visibility' => 'public',
        ],
```

i have chagned the `disk` -> `public` -> `url`  value  ` env('APP_URL').'/storage'` to ` env('APP_URL').'/storage/app/public'`,it works for me
