### ISSUE TITLE
Upgrading to version 1.1 breaks custom controllers

### ISSUE THREAD

**Issue by Grabes** [thedevdojo/voyager#3171]
- Laravel Version: 5.5.40
- Voyager Version: 1.1.1
- PHP Version: 7.1
- Database Driver & Version: Mysql 5.7

### Description: 
Upgrading to version 1.1.1 now references `VoyagerBaseController` instead of `VoyagerBreadController` which causes custom controllers to break which were created before 1.1.

### Steps To Reproduce:
After upgrading from 1.0.x to 1.1.1
And I am using custom HTTP Controllers
And have a custom controller extending the `VoyagerBreadController`
When trying to access a CMS page which uses my custom controller
Then the CMS page uses `VoyagerBaseController`
And trying to edit/add/delete results in a 500 error

### Solutions
This is a breaking change and there was no mention in the docs. Found others with the same issues #2746 and #3011

**Comment by fletch3555** [comment]
This is correct, and definitely should be in the docs, likely in the 1.0 to 1.1 upgrade guide (I'm mobile, so I'll check shortly).  This project never claimed to follow semver, so yes, it's possible for breaking changes to get in to a "minor" release.

The fix is simply to change your custom controllers to use Base instead of Bread.  It was renamed by us, but is functionally identical.

**Comment by fletch3555** [comment]
https://voyager.readme.io/docs/10-to-11#section-custom-controllers
