### ISSUE TITLE
a view to show data for its own user

### ISSUE THREAD

**Issue by abdolrhman** [thedevdojo/voyager#3275]
- Laravel Version: *
- Voyager Version: *
- PHP Version: *
- Database Driver & Version: mysql

### Description:
Hello , i have voyager setup , what i need , that is there a users , where each user has its own matches , so how to create a view and for each user , get its own matches only , 
plz help this is very important since this will make me create my project , 
and really thanks for this great thing ,

**Comment by donmbelembe** [comment]
If you want to create a custom page inside voyager, refer to the [docs](https://voyager.readme.io/docs) especially in the customization part.

additionally learn about [Route parameters](https://laravel.com/docs/master/routing#route-parameters)
and bonus [Masking IDs in URLs using hashids in Laravel](https://sampo.co.uk/blog/masking-ids-in-urls-using-hash-ids-in-laravel)

**Comment by fletch3555** [comment]
@abdolrhman, version numbers are required, as is the "steps to reproduce" section for bugs.  Otherwise, it's very difficult for us to troubleshoot.  If you're asking a question instead of reporting a bug or suggesting a new feature, we encourage you to ask in our Slack group's #help channel, where you'll likely get a faster response.

And as always, please make sure to read the docs.
