### ISSUE TITLE
how to create many-to-many relationship for User

### ISSUE THREAD

**Issue by mankowitz** [thedevdojo/voyager#3307]
- Laravel Version: 5.6.23
- Voyager Version: 1.1
- PHP Version: 7.25
- Database Driver & Version: mysql 5.7

### Description:

This is more of a question than a bug. 

Each user is associated with multiple sites using a pivot table named site_user. I have added the relationship to the User BREAD, but it does not appear in the user edit form. I have edited add-edit.blade.php, but I am not sure what to do with this code block.

```php
<div class="form-group">
    <label for="sites">{{ __('voyager::profile.roles_additional') }}</label>
    @php 
        $row = $dataTypeRows->where('field', 'user_belongstomany_site_relationship')->first(); 
        $options = json_decode($row->details);
    @endphp 
    @include('voyager::formfields.relationship')
</div>

```

### Steps To Reproduce:

n/a

**Comment by SteamWind** [comment]
Show us a screenshot of your relationship and your view please.

**Comment by mankowitz** [comment]
This is a screenshot of the relationship. The view is just the defalut add-edit.blade.php. I tried to edit it by changing the datarow. I was wondering how to change `__('voyager::profile.roles_additional')` into something I could use for sites

![image](https://user-images.githubusercontent.com/329570/41473734-233678f0-7088-11e8-8773-e58167ca477c.png)

**Comment by fletch3555** [comment]
Voyager provides a custom "users" `edit-add` view, which is not currently dynamic like the default "bread" view.  Due to this, adding new fields through Voyager will not appear in the view by default.  You can copy the "bread" view from vendor to `/resources/views/vendor/voyager/users/edit-add.blade.php` to add this dynamic functionality back, which will cause your relation to appear correctly.

Once you get that working, you'll be able to override the view however you need.

**Comment by mankowitz** [comment]
@fletch3555 where do I copy this into?
