### ISSUE TITLE
Custom field in user table not showing in Add and Edit form

### ISSUE THREAD

**Issue by rddewan** [thedevdojo/voyager#3315]
- Laravel Version: 5.6.23
- Voyager Version: 1.1.2
- PHP Version: 7.1.14
- Database Driver & Version: MySQL

### Description:
I have added a custom field in user table . In admin panel using bread i can view this field but when i try to edit or add user i cant see this custom field in the form .

How can i add this custom field to edit and add user form in bread ?

Thank you

**Comment by SteamWind** [comment]
We need more informations to reproduce your problem. Provide screenshots, configurations, etc.
Thank you.

**Comment by rddewan** [comment]
i have attached few screen shot but the configuration as default i have not changed any...
![1](https://user-images.githubusercontent.com/13164167/41459520-65d782e2-70bc-11e8-919a-6b5864b52848.png)
![2](https://user-images.githubusercontent.com/13164167/41459521-66222f2c-70bc-11e8-8e41-bede4647c801.png)
![3](https://user-images.githubusercontent.com/13164167/41459523-666b87f8-70bc-11e8-92be-57b2130bde92.png)

**Comment by fletch3555** [comment]
Voyager provides a "custom" user view, which is how it's 2-columns instead of the simple form layout normal BREADs use.  You can override this by copying `/vendor/tcg/voyager/resources/views/bread/edit-add.blade.php` to `/resources/views/vendor/voyager/users/edit-add.blade.php`.  This will override the custom view with the original dynamic BREAD view, so it'll be completely configurable by Voyager again.  You'll then be free to edit the view as needed.
