### ISSUE TITLE
Trying to upload a mp4 file

### ISSUE THREAD

**Issue by Jiiieeef** [thedevdojo/voyager#3397]
- Laravel: v4.4
 - Voyager: v1.1
 - PHP: 7.2
 - Database: MySQL

Hey there,
I am trying to upload mp4 files in a BREAD table.
I've configured my field to use a file input but it seems to do nothing, only '[]' is recorded in my DB. 
The column in my table is a VARCHAR(191).

Is there something I am doing wrong ?

**Comment by Emerica** [comment]
Having the same issue.
Seems the created upload field gets set to a multiple form field, the id is an array[] and multiple is set.

When the File controller gets the data it fails to find any files in the request array with a key of the filename, as they are all number based.

 It then  does this  when it can't find the key.
`return json_encode([]);`

I'm new to Voyager so I can't suggest a good solution, but I was able to change the file http\controllers\contenttypes\file.php
` 
if(!$this->request->file){
    return json_encode([]);
}
$files = Arr::wrap($this->request->file[0]);`

NOTE: This allows a single file to be uploaded, but throws away any kind of multi upload, it's only taking the first item in the array of files.. It might break something else too, I've got limited exp.
Maybe someone here can take a deeper look at the situation and suggest a solution that works.
For now we have an idea what's causing it.

**Comment by emptynick** [comment]
The only reason I see why its only failing for mp4 files is because they are large - normally.
Please check your php.ini's for `post_max_size` and `upload_max_filesize`.
For me `upload_max_filesize` is 2MB and `post_max_size` is 8MB.
Handling too big post-requests is unfortunately not (easily) possible.
From the [PHP docs](http://php.net/manual/en/ini.core.php#ini.post-max-size):
```
If the size of post data is greater than post_max_size, the $_POST and $_FILES superglobals are empty.
```

**Comment by Emerica** [comment]
That's a good suggestion, though I don't think that's the case, my above hack would have likely failed with an exception that it reached the upload limit. Yet the file still got uploaded without error
.
My analysis showed that the array key being searched for in the upload array did not exist. 
`if (!$this->request->has($this->row->field)) {
            return json_encode([]);`

This checks to see if the request has a field with the column name. This is fine on images uploads because the view creates a form field that is named after the column.
You can see in views/formfields/image.blade.php that html looks like this.
`<input @if($row->required == 1 && !isset($dataTypeContent->{$row->field})) required @endif type="file" name="{{ $row->field }}" accept="image/*">
`

But in the file uploader..

`<input @if($row->required == 1 && !isset($dataTypeContent->{$row->field})) required @endif type="file" name="{{ $row->field }}[]" multiple="multiple">
 `
Notice the array brackets added to the end of the name,  {{ $row->field }}[] it also sets the  multiple option.
When the request for the file upload comes back it will never find {{ $row->field }}, it needs to find {{ $row->field }}[]
The form field http controller runs the code noted above and returns an empty json list.

If you have a look at the multiple image upload controller, it's done differentley.
`$filesPath = [];
 $files = $this->request->file($this->row->field);
foreach ($files as $file) {`

$files = $this->request->has($this->row->field);   becomes $files = $this->request->file($this->row->field);
And then it starts to loop through the returned array.

My guess is the file http controller is bugged and needs to be fixed.  
If I'm just stupid, you're welcome to prove me wrong :)

**Comment by Emerica** [comment]
Looking at it a little more. The files get Arr::wrap'd and filespath is set, you should just be able to remove lines 15-17 of the file http controller.

        if (!$this->request->has($this->row->field)) {
            return json_encode([]);
        }


This is a working solution and upload(s) work. 
With the files and filespath vars being set in the case of nothing being uploaded, I don't expect the code to error.
Editing and not selecting a file also did not change the results. Appears good.
