### ISSUE TITLE
Refreshing login page when default guard is set as `api` 

### ISSUE THREAD

**Issue by gileneusz** [thedevdojo/voyager#3398]
## Version information
 - Laravel: v5.6
 - Voyager: v1.1
 - PHP: 7.1.3
 - Database: MySQL 8.0

## Description

I cannot log into fresh Voyager instalation with default guard set as `api` inside config auth.php
Voyager is refreshing login page without any error. This is not occuring when default guard is set as `web` and there is no easy solution how to fix, or even set 'web' guards inside web routes in laravel that serve mainly as an api endpoint. 

## Steps To Reproduce
1. Make fresh instalation of laravel and Voyager
2. Set inside config.auth.php
```
    'defaults' => [
        //'guard' => 'web',
        'guard' => 'api',
        'passwords' => 'users',
    ],
```
3. Try to login as admin
4. See error - refresh admin page

## Expected behavior
Possible login as an admin.

**Comment by brianchristopherpeck** [comment]
Check this out for an explanation of how `'guard' => 'api'` works... https://mattstauffer.com/blog/multiple-authentication-guard-drivers-including-api-in-laravel-5-2/
It sounds like there's something wrong with the way the below steps are implemented:
1.) Add an api_token column to your `users` table. 60-character string, unique.
2.) Instead of using the auth middleware in your route definition, use the auth:api middleware.
3.) In your API routes, use Auth::guard('api')->user() to get your user instead of Auth::user().
I'm pretty sure this isn't a voyager issue

**Comment by fletch3555** [comment]
The issue is that Voyager makes use of the default guard, and does not (currently) provide a way to override it.  When you set the default to "api", a number of middleware are no longer included.

The fix here should be to add a config to Voyager to enable setting what guard to use.  There is another (fairly recent, I believe) issue with a similar guard-related problem, where I suggest the same solution.  Not sure offhand whether there's a PR open yet to add it.  If not, and you'd like to do it, please feel free.

**Comment by urukalo** [comment]
temp solution what i use:
set def guard to `web`
in base api controller(make one if you dont have) constructor override config ( with `Config::set('auth.defaults.guard', 'api');` or similar)

this is ugly solution, it is bad to change config data dynamically (i didnt check impact on caching and other performance related functionalities)  ... but it work for now 😈

**Comment by emptynick** [comment]
Implemented in https://github.com/the-control-group/voyager/pull/3968

**Comment by dlws21** [comment]
Starting with Voyager 1.2 you can define a (custom) guard which is used throughout Voyager.
To do so, just bind your auth-guard to VoyagerAuth.
Open your AuthServiceProvider and add the following to the register method:
`$this->app->singleton('VoyagerAuth', function () {
    return Auth::guard('your-custom-guard');
});`
Now this guard is used instead of the default guard.

In Voyager Docs https://docs.laravelvoyager.com/customization/custom-guard
**But doesnt work for me**

**Comment by vntrungld** [comment]
@alexykouakou That's because from postLogin of VoyagerAuthController still use $this->guard() to attempt $request. This can be solve by replace $this->guard() to app('VoyagerAuth')

**Comment by SvenSchoene** [comment]
What helped me was setting the guard/middleware on the `admin` route group in addition to registering the custom `VoyagerAuth`-guard in the `AuthServiceProvider`:

```php
Route::group(['middleware' => ['web'], 'prefix' => 'admin'], function () {
    Voyager::routes();
});
```

**Comment by SvenSchoene** [comment]
~~What helped me was setting the guard/middleware on the `admin` route group in addition to registering the custom `VoyagerAuth`-guard in the `AuthServiceProvider`:~~

```php
Route::group(['middleware' => ['web', 'auth:web'], 'prefix' => 'admin'], function () {
    Voyager::routes();
});
```

[EDIT]  
That only worked after the user is already logged in. The login page fails with `{"message":"Unauthenticated."}`, which is not really surprising actually. Let's see how to fix that, I have an idea...

[EDIT 2]  
Ok, I'm not happy, but what works for me now is in the controllers that are published in the applications `app/Http/Controllers/Voyager/` directory, add the following constructor: 

```php
    public function __construct()
    {
        $this->middleware('web');
        $this->middleware('auth:web');
    }
```

I did **not** add it in `VoyagerAuthController.php` and `VoyagerController.php`, as well as any Controller that extends `VoyagerBaseController` (because I added it there anyway).

I got the idea from here: https://stackoverflow.com/a/46824614/6055486  
Hope this helps someone.
