### ISSUE TITLE
admin and front end

### ISSUE THREAD

**Issue by amc123-glitch** [thedevdojo/voyager#3401]
## Description
What I have not been able to find on this topic is how to to implement this in a way that allows the basic users to enter data and then the admins be able to access/read the data being submitted from the other side. (really just a form on a blade template) and be able to interact with it.

**Comment by fletch3555** [comment]
If you use the same model classes (or different models that use the same database table), then the data will live in the same place.  Just add a form to your app that submits data, then admins can review it (or whatever you need) from within Voyager.

Sounds like you may have thought a little too deep into it.  Voyager does not need distinct tables from the rest of your app, which is why we don't force creation of a separate database connection in `config/database.php`.  Based on my understanding of the information you've provided, you don't need a multi-level admin panel.  You just need the one level, and a means for users to submit data from your front-end app.

**Comment by AnthonyMichaelc** [comment]
I think you get where I was going with my question. Yeah usually I build from scratch and restrict certain things. This time I wanted to try Voyager but know I can't have the basic users logging into the back end dashboard. But would Like them to login to submit data and edit it as needed, if that makes sense
