### ISSUE TITLE
Image Displaying Problem

### ISSUE THREAD

**Issue by ManojKiranA** [thedevdojo/voyager#3426]
## Version information

 - Laravel: v5.6.29
 - Voyager: v^1.1
 - PHP: 7.1.17
 - Database: [mysql] [5.0.12] (e.g. MySQL 8.0)

## Description

A Bug is when i set a image for user it is not displaying in left side  navigation menu
(Even i hve tried installing in new laravel project but is is not displaying the image)

## Steps To Reproduce
1. Go to 'admin page'
2. See error while navigating in sidemenu

## Screenshots
https://www.flickr.com/photos/141561628@N07/43694277511/in/dateposted-public/

**Comment by fletch3555** [comment]
Please share the `src` url for the broken image

**Comment by lexman02** [comment]
Do you have your AppURL set in your .env file? That used to happen to me before I just started using `php artisan serve`

**Comment by defaultpage** [comment]
Hi! Can you open "<project_dir>/public/storage"?

#2726 
#2823
#2890
#3092

**Comment by dereks** [comment]
This happens when the line APP_URL in the file .env does not match your webserver configuration.

For example, if your .env file says

APP_URL=http://localhost

Then the served image URLs will have that as their prefix. So if you are visiting your site at https://10.0.3.18/admin/, there will be a mismatch between the https:// used for the admin pages and the http:// used for the images -- so the images won't load.

From the attached screenshot it looks like you are viewing the page at http://localhost:1234/, so my guess is that the port number ( the colon-1234 on the end) is not getting set correctly for your image URLs. Double check what is in your .env file, as per the Laravel docs.

I had the http vs https mismatch and got broken images. I fixed it by setting the APP_URL to be just empty, so that the image URLs are all relative (with no prefix).  Now the images work regardless of that protocol (HTTP vs. HTTPS), IP address (localhost vs. 10.0.3.18), and port number (1234 vs 443 vs 80).

Maybe Voyager should set APP_URL to blank by default, so images work out-of-the box.

**Comment by ManojKiranA** [comment]
yes, it worked, it is because of  APP_URL.
Thanks for  your for support.
Over and Out
