### ISSUE TITLE
I get permission denied when creating a Model

### ISSUE THREAD

**Issue by rroslan** [thedevdojo/voyager#3517]
Trying to create a simple products table together with the Product model. Seems like I was getting permission denied to write in the App folder.
Locally I am running on windows and had no problems creating a table and the model.

I am using deployer to push  the same copy of the voyager to digitalocean.

Hope someone can help me here.

**Comment by fletch3555** [comment]
We have issue templates for a reason.  Right now, I have no idea what version you're using (there have been MASSIVE changes between versions in the past), or anything else.

This is very unlikely to be an issue with Voyager, rather an issue with your deployment process.  I hope you understand the vast differences between Windows and Linux permissions models.  If not, please go look into it.  Most likely, the user your webserver is running as (`apache`, `nginx`, `www-data`, `httpd`, etc) doesn't have write access to your project folder.  Generally speaking, this isn't a bad thing for web applications, but Voyager requires it in order to function.

Your server configuration (especially related to filesystem permissions), is well beyond the scope of support we can provide on the github repo's issue tracker.  I would recommend asking on our Slack, or better yet, a more generic forum like LaraChat
