### ISSUE TITLE
Assets not load

### ISSUE THREAD

**Issue by gintoki05** [thedevdojo/voyager#3528]
## Version information

 - Laravel: v5.6.
 - Voyager: latest
 - PHP: 7.2
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

Im just doing fresh install laravel and voyager, but why my asset not load. even im change 'assets_path' => '/vendor/tcg/voyager/assets', to 'assets_path' => 'public/vendor/tcg/voyager/assets', the result is Sorry, the page you are looking for could not be found.

## Expected behavior
Please help me what happen here

## Screenshots
![screenshot from 2018-09-06 11-57-37](https://user-images.githubusercontent.com/26396390/45136007-5e662f80-b1cc-11e8-8599-a880cc0328bf.png)

**Comment by fletch3555** [comment]
What's the url of the page in the screenshot?

Assets returning a 500 are 100% not caused by Voyager. Most likely its misconfiguration of the webserver.  Can you look at the network tab and see what the actual response body is? I'm curious if it's a laravel "whoops" page, or a webserver "500 error" page, or something else

**Comment by gintoki05** [comment]
![screenshot from 2018-09-06 20-01-33](https://user-images.githubusercontent.com/26396390/45158951-ab1f2a00-b20f-11e8-8ac9-f0a02d492086.png)
im using laravel valet in linux.

**Comment by fletch3555** [comment]
Well your path is wrong... why is it trying to load from vendor/tcg/voyager.....? Sounds like you've done something very strange with your install.  Please describe exactly what you did to get laravel installed, then what you did since to get Voyager installed.

Also, I asked for the URL of the login page in your first screenshot. Please provide that

**Comment by gintoki05** [comment]
1. laravel install : composer create-project --prefer-dist laravel/laravel blog "5.6.*"
2. $ composer require tcg/voyager
3. setting env
4. php artisan voyager:install --with-dummy

login http://auto2000.test/admin/login

i dont know, it must be load to public/vendor automaticaly right? without change the voyager config. 
maybe wrong with my laravel valet linux configurattion? laravel valet linux install -> https://www.youtube.com/watch?v=dFO9UcbTIDs

**Comment by gintoki05** [comment]
its fixed alhamdulillah, just reinstlal my vallet. thanks for your response, cheers
