### ISSUE TITLE
Login another user

### ISSUE THREAD

**Issue by gintoki05** [thedevdojo/voyager#3532]
## Version information

 - Laravel: v5.6.#
 - Voyager: v1.1.#
 - PHP: 7.2
 - Database: [type] [version] (e.g. MySQL 8.0)

Question 
I want to login to admin dashboard with another account, but when loggin the url redirect to domain without /admin (can't). How to fix it

**Comment by fletch3555** [comment]
Just to make sure I understand this correctly...

You have a user that can log into Voyager, and it all works fine.
You have another user that can log into Voyager, but redirects you to the bare domain (i.e. `example.com` instead of `example.com/admin`)

Assuming this is correct, then your second user's role does not have the `browse_admin` permission
