### ISSUE TITLE
can't overwrite the users/edit-add 

### ISSUE THREAD

**Issue by saeid78** [thedevdojo/voyager#3568]
## Version information

 - Laravel: v5.6.29
 - Voyager: v1.1
 - PHP: 7.2
 - Database: [MySQL] [5.7.23] 

## Description:
Hello,
First of all let me thank you guys for building this useful package!
I came across a problem that when I want to modify default users\edit.add blade as it has just few fields from user table, I get "vendor.tcg.voyager.resources.views.master not found"  error when trying to edit the user.
Not to mentioned I've already changed the model to App\User in BREAD UI and cut /past edit.add base  into my resource folder: views\vendor\voyage\users
How can I edit the view edit-add for users/edit.add only ?
Many Thanks.

**Comment by fletch3555** [comment]
Couple things.....

1. I have absolutely no idea what you did to get `vendor.tcg.voyager.resources.......`, but I suspect you changed the view in an attempt to reference a view from the vendor directory.  That won't work, but Voyager makes use of view namespaces (i.e. `voyager::master`).
2. Voyager provides a customized `users/edit-add` view out of the box.  This prevents BREAD changes from appearing.  If you wish to revert this custom view and make it behave like a fresh BREAD view, you can do the following:
> Copy `vendor/tcg/voyager/resources/views/bread/edit-add.blade.php` to `<your app root>/resources/views/vendor/voyager/users/edit-add.blade.php`.
3. If you want to keep the Users view and just add to it, repeat the above process, but copy `users/edit-add.blade.php` instead of `bread/edit-add.blade.php`.  Then, of course, modify to your heart's content

**Comment by saeid78** [comment]
@fletch3555 
I did what you said above, but getting the same error! I just want to change the edit blade.
View blade is working just fine , but when I try to add/edit I get below:
![add editview error](https://user-images.githubusercontent.com/10727725/45819300-03dfcf80-bcb2-11e8-8cb3-c136b64c708d.png)
Please advice.

**Comment by fletch3555** [comment]
Correct me if I'm wrong, but didn't we resolve this in Slack? I'm going to close this for now, but if that assumption was incorrect, please feel free to reopen it
