### ISSUE TITLE
Additional css not included on login page

### ISSUE THREAD

**Issue by decowboy** [thedevdojo/voyager#3639]
## Version information

 - Laravel: v5.7.9
 - Voyager: v1.1.7

## Description

The additional css files are not included on the login page, while they are included on (most?) other pages. This shows that the additional css file setting in itself is working, but it can't be used to alter the style of the login page.

**Comment by fletch3555** [comment]
Yes that is correct. The login page is a stand-alone view and doesn't use the main layout that the rest of Voyager uses. The explanation for that is simple, it's a completely different layout.

Having said that, you can just override that one view file (same as any other page, which our docs cover) and edit it as needed.  I'd prefer not to add `additional_css` to that view due to the high likelihood of conflict between styles for that page and styles for everything else.
