### ISSUE TITLE
Entity is not added to menu and routing is not updated

### ISSUE THREAD

**Issue by wymedia** [thedevdojo/voyager#364]
Laravel Version: 5.3.26
Voyager Version: 0.10.0
PHP Version:
Database Driver & Version:

### Description:

When a menu-item is created, it is not added to the UI. Also the route seems not to be created which results in error. 

1) I create a table called video
2) I create the bread functions
3) I create a menu-item videos and point this to /admin/videos
4) I refresh the page, but the video menu item is not shown on the UI
5) I go to a browser to /admin/videos but it gives a routing error

### Steps To Reproduce:
See this [video](https://www.dropbox.com/s/zzhj07dygkdn1h1/Laravel-Voyager.mov?dl=0) around the 3rd minute to see the exact steps

**Comment by marktopper** [comment]
I see, thanks for the good explaining video. Looking into it right away.

**Comment by marktopper** [comment]
Just found the issue. When you build new BREAD 🍞 with the setting `Generate Permissions` enabled, it will generate the permissions. But then your account will not yet have the rights for that permission.
In order to fix this you must go to `Roles` and add the new added permissions to your role for that BREAD 🍞.
However I think that the role creating the BREAD 🍞 should automatically get the permissions.
I will implement this and notice you.

**Comment by wymedia** [comment]
Thanks, I confirm this works indeed as you mentioned. Issue can be closed.
