### ISSUE TITLE
An invalid form control with name='bio' is not focusable.

### ISSUE THREAD

**Issue by Khaled-Elfishawy** [thedevdojo/voyager#3642]
## Version information

- Laravel: v5.6
- Voyager: v1.1.7
- PHP: 7.2
- Database:mysqlnd 5.0.12-dev

## Description
Pages with translatable fields that have a rich text box bread prevent the creation of new items. Console displays an invalid form control with name="{fieldname}" is not focusable. New item does not submit.

i Search in Issues And I dont Now What To Do All other issues is closed and i dont found any solve there
plz tell my what to do exactly to solve this problem

**Comment by DrudgeRajen** [comment]
After digging sometime, I came to know that If the field is not null in database and the input type is RichTextBox then this issue occurs. FIY,  NOT NULL feature of database is used to make field required so that browser can validate the required inputs. 
I think there is some problem with hidden translatable field in case of RichTextBox as input type if the respective column is not null. **So, for workaround make the column nullable which will make the respective input field not required and it will work for translatable as well.**
Also, if you have already created a column with NOT NUll, then you need to update the column from database to set as nullable. Because, right now updating the table using Database Menu of Voyager  will not affect the Bread.

**Comment by fletch3555** [comment]
@DrudgeRajen is correct.  Also, this has been reported multiple times on this repo.  The core of the issue is that browsers complain when you try to focus a hidden field.  The richtextbox is hidden automatically due to the editor we use, and the field gets focused due to default browser validation.  This is really more of a browser issue than a Voyager issue, but they don't seem interested in fixing it, so we have to find a workaround.  We just haven't done so yet.

PRs welcome!

**Comment by ivanmart** [comment]
@DrudgeRajen I have fresh update 1.1.3 => 1.1.10, I had no success changing the corresponding field to NOT NULL in database. It even shows now "Required: No" in BREAD, but error is the same. What helped is to set `required` to `0` in `data_rows` table. Hope this helps someone.
