### ISSUE TITLE
TinyMce how up quality image in voyager?

### ISSUE THREAD

**Issue by ExsyDev** [thedevdojo/voyager#3698]
Hello. In rich text box, when I upload image, quiality is very small. How I can up to 90-95% ? In config I did not find this section.

**Comment by fletch3555** [comment]
Please use the issue templates we have defined.  They prompt you to enter the information necessary for us to troubleshoot issues.  If you're asking a question instead of reporting an issue, that question is likely best asked in our Slack group instead unless directed to create an issue here by one of the maintainers.
