### ISSUE TITLE
 Relations with conditional

### ISSUE THREAD

**Issue by lbernardocu** [thedevdojo/voyager#3755]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 7.2
 - Database: MySQL 

Hello friends. I need to put some conditions in my relationships between tables but I can not do it. For example, a relationship between the work table and devices, I only want to show in the work view the devices that have not been worked. In the table devices has a field that indicates 0 that has not been processed and 1 that yes. Please, someone who has found something to help me. Thank you

**Comment by fletch3555** [comment]
Questions like this should really be posted in Slack, not here.  We try to reserve github issues for actual problems with the code or new features.

Having said that, Voyager does not currently provide a mechanism to filter these.  There are a few options though.

1. If the relationship will always be filtered that way, then just add the condition to the relationship method (instead of `return $this->BelongsTo(...)`, you can do `return $this->BelongsTo(...)->where()`)
2. If the relationship may need to be different, then consider scopes(refer to Laravel docs).  You may need to customize the controller in Voyager to get that to work though.  I can't say for certain since I haven't tried it.
3. You can try using an accessor method to call the relation and then the filter, and have Voyager use that accessor as a "custom field" (something like this: http://docs.laravelvoyager.com/customization/custom-realtionship-attributes, though I'm not sure that would work in this case)

**Comment by lbernardocu** [comment]
thanks fletch3555
