### ISSUE TITLE
VoyagerBreadController.php line 37 : Trying to get property of non-object

### ISSUE THREAD

**Issue by olipiskandar** [thedevdojo/voyager#39]
can you fix this ?

**Comment by fletch3555** [comment]
Did you run `php artisan voyager:install`?

I was able to work around a similar error (different line number, same message) by making sure the roles were imported BEFORE any users during a db migration/seed, since Voyager has a "created" listener for users that sets the default role to "user".

If that doesn't sound related to what you're doing, then please provide more information, such as the full stacktrace from the logs, whether you're running Voyager OOTB or if you added it to an existing project, and any modifications you may have made.

**Comment by qcol** [comment]
I have the same error. It happened when created custom table and added Bread to it. After this operation, error occurs on dashboard page:

`VoyagerBreadController.php line 37 : Trying to get property of non-object`

When deleted Bread - everything works fine again.

**Comment by aroon9002ahmed** [comment]
i have same error
FatalErrorException in VoyagerBreadController.php(37) : eval()'d code line 1:
Class 'App\products' not found
