### ISSUE TITLE
problems in voyager v1.1.11 latest updates ?

### ISSUE THREAD

**Issue by blacksud0** [thedevdojo/voyager#3915]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1.11
 - PHP: 7.3

## Description:
Many of the problems I have encountered especially in the latest version should be handled because they do not work well

> - on rtl mode dropdown profile not working
> - on compass / Resources / Fonts It has some problems in style (icon)
> - when I enable  multilingual to supported by the BREAD input it's not working 
> - If I select one of the existing languages, the menu they remain as they are and are not translated
> - I wish to add an option if the user wants to enable the rtl mode From within the control panel
> - When the user wants to change the password, the current password is not verified :-1: 

## Development
I hope to add such features from your side and enable activation or deactivation option for the user :+1: 
* [Voyager Frontend](https://github.com/pvtl/voyager-frontend)
* [Voyager Page Blocks](https://github.com/pvtl/voyager-page-blocks)
* [Voyager Forms](https://github.com/pvtl/voyager-forms)

I wish you success always

**Comment by fletch3555** [comment]
There's nowhere near enough information provided for us to troubleshoot these issues you're reporting.  Each one should be it's own issue (and likely already exists, potentially already fixed in an unreleased version).

As for the links at the bottom, I'm not sure why you've provided them, but they're not made by us, nor are they supported by us.

**Comment by blacksud0** [comment]
thank you very much 
I'm waiting for the next release :+1:
