### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by saadmeer66** [thedevdojo/voyager#4029]
## Version information

 - Laravel: v.5.6
 - Voyager: v.1.1
 - PHP: #.#
 - Database: sql

## Description
well i done all things on local and  deploy all data on production and its working fine. but when i add new data on production and on local i made chnges  and push it to git repo it replaces the local storage file to the production files and my new data on production  replaces with local.
i tried to git ignore storage  folder  but it wont work.
i am using /envoyer.

## Additional context
this all happen in media manager.
there are 4 folder in media manger local and i push on production it has also 4 i add one more folder on profuction now production contain 5 folder. now i make some changes on local and pushed now the production contain also 4 the 5th folder deleted

**Comment by fletch3555** [comment]
Title is strongly recommended (the `[BUG]` part is there as a prefix, not intended to be the whole thing)

Also, all version information is required, including PHP and database (no, "sql" is not a database type/version), which you did not provide.  Additionally, we prefer if the full version is supplied, specifically for Voyager since there was significant changes between 1.1.0 and 1.1.11


As for your problem, your question seems to be more about git usage, not anything specific to Voyager or even Laravel.  In git, if you commit a file, then it's tracked.  If you then add it to .gitignore, it's already tracked, so changes will still appear.  You need to `git rm` the file(s) to stop tracking them.

Questions should be asked in our Slack group so we have the opportunity to triage them and potentially solve unrelated issues without cluttering our issue tracker.

**Comment by saadmeer66** [comment]
voyager version is 1.1 and i want to stop the tracking of the of the storage folder...
