### ISSUE TITLE
whereTranslation not works with `!= ""` (not equal to empty string)

### ISSUE THREAD

**Issue by minhdanh** [thedevdojo/voyager#4102]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.2
 - PHP: 7.2
 - Database: MySQL 5.7

## Description

I'm trying to select records that don't have empty slug, using `whereTranslation` (let's say I have 5 posts with slugs, 1 post with empty slug (English)):

```Post::whereTranslation('slug', '!=', '', ['en'], false)->get();```

This is returning zero records. Although I have 5 records that have non-empty slugs.

However this works:

```Post::whereTranslation('slug', '=', '', ['en'], false)->get();```

In this case the only record with empty slug is returned.
So maybe `whereTranslation` not works with `!= ''` in this case?

## Expected behavior
Records with non-empty slugs are return.

**Comment by reageek** [comment]
I am going to go out on a limb and guess, English is your default language. 

Setting false on the last param, removes the default language from the search scope. This happens because there is a when condition that applies an orwhere statement to search the default table and there is no english language translations in the translation table.

If you know you are searching the default table you should be using just a normal where statement. You could avoid this issue with a simple check for the fallback locale, or default locale language check and then do the appropriate query scope.

A possible fix would be to do a check in scopeWhereTranslation for the fallback locale.

Something like

```
        if(in_array(config('voyager.multilingual.default'), $locales)){
            $default = true;
        }
```

**Comment by minhdanh** [comment]
Ah, no English is not the default language. I should have mentioned that.

**Comment by reageek** [comment]
Odd, with the exception of the default language, I get a result.
![whereTranslation](https://user-images.githubusercontent.com/5495292/56590422-15c18200-65b5-11e9-9584-0fc77b3ec518.JPG)

Is it possible, that there is no entries that have translated slugs?

**Comment by minhdanh** [comment]
The default language I'm using is `vi`.
I've just tried to create a new Post that have empty vi slug but with en slug then `Post::whereTranslation('slug', '=', '', ['en'], false)->get();` is returning that post.
While the posts that have empty en slug but with vi slug are not returned.
Is this the expected behavior?

> Is it possible, that there is no entries that have translated slugs?

There are entries with translated slugs, actually.

**Comment by minhdanh** [comment]
Ok, I figured out. It's my mistake.
