### ISSUE TITLE
[BUG] No translations when installing

### ISSUE THREAD

**Issue by pelomedusa** [thedevdojo/voyager#4160]
## Version information

 - Laravel: v5.7.26
 - Voyager:v1.2.3
 - PHP: 7.3

 - Database: mysql5.7.26

## Description
When installing Voyager with dummy, i ran into the infamous `No query results for model [TCG\Voyager\Models\DataType].` To fix this, i copied the file from [this](https://github.com/the-control-group/voyager/pull/4140/commits/a73bc0fd93a32497b4c45175aefb6b11db375398) commit, and it solved the error. However, the translations in my database did not work:
![db](https://user-images.githubusercontent.com/15833842/58314638-39742400-7e10-11e9-8262-4b0fe35633c7.png)

In my app.php
```
    'locale' => 'fr_FR',
    'fallback_locale' => 'fr_FR', //also tried with 'en_US'
```
In my voyager.php:
```
    'multilingual' => [
        'enabled' => true,
        'default' => 'fr',  //also tried with 'en'
        'locales' => [
            'fr',
        ],
    ],
```

**Comment by chrysochos** [comment]
Three problems solved.
1) I have 2 models. Menus and Pages. I can use a locale for Menus and I can save the translation in database. However when I try to save the translation of Page, even without any change in text of body, title etc, I get ErrorException "mb_strtolower() expects parameter 1 to be string, array given"  from line 9 in /voyager/vendor/teamtnt/tntsearch/src/Support/Tokenizer.php file.

IN ORDER TO SOLVE THIS I USE json_encode($text) as shown below.

class Tokenizer implements TokenizerInterface
{
    public function tokenize($text, $stopwords = [])
    {
       $text=json_encode($text);  // I add this line
       $text  = mb_strtolower($text);
       $split = preg_split("/[^\p{L}\p{N}]+/u", $text, -1, PREG_SPLIT_NO_EMPTY);
        return array_diff($split, $stopwords);
    }
}

2) I had the problem with the rich text editor and I replace it with a text area. Now I can translate without any issue.

3) When the default language is not 'en' the language change is not working. So, change the default language to 'en'.

 

-----------

Voyager is "v1.2.3"
Laravel is 5.8.16
PHP 7.2.17
mysql: 5.7.26-0ubuntu0.18.04.1 (Ubuntu)

**Comment by pelomedusa** [comment]
> When the default language is not 'en' the language change is not working. So, change the default language to 'en'.

This was probably the problem. I can't confirm because i'm using another package instead, but i had the same problem with the other package solved this way.
