### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lequan1102** [thedevdojo/voyager#4243]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.6
 - PHP: 7.2
- Database Driver & Version: phpmyadmin 4.7.0
## Description
I enjoyed voyager, it worked very well at its job. But I'm having a problem - when I don't enter enough fields to check, like (title, image, category_id, body), it appears laravel error message, not a voyager popup. Did I configure something wrong, thanks
![Zalo_ScreenShot_5_7_2019_913323](https://user-images.githubusercontent.com/31363629/60712189-a4049d80-9f40-11e9-8c89-247cccdcd9e8.png)

**Comment by fletch3555** [comment]
Voyager tries to stay out of your way as much as possible, so we assume you know which fields are required to have a value and which aren't (e.g. nullable, or have a default value set in the DB).  Perhaps we could catch the exception and display a prettier message, but we don't do much of that anywhere since it's almost always a missing field in the BREAD configuration and should always be discovered during dev/testing.

I'm open to a PR for better exception handling if someone wants to try

**Comment by MrCrayon** [comment]
Posts and Pages BREAD are just examples, if you want to use it you should set validation rules.

You can see how to do that in voyager documentation.
