### ISSUE TITLE
Generate thumbnail of already existing image

### ISSUE THREAD

**Issue by florentvdry** [thedevdojo/voyager#4282]
## Version information

 - Laravel: V5.8
 - Voyager: Latest
 - PHP: 7.2
 - Database: MySQL

## Description:

Hi all,

For optimize my website, i use the thumbnail with my model with this kind of configuration : 

    "thumbnails": [
        {
            "name": "cropped",
            "crop": {
                "width": "300",
                "height": "250"
            }
        }

Sometime i made change in my view file and have to add other resize settings, but the image is not generate. I have to re-upload an image for generate all the images.

Can i generate images automatically ? If i change a thumbnail for my blog, i have to change the image of all posts for generate new images..

Do you have any solution ?

Thank you

**Comment by fletch3555** [comment]
We don't currently have a way to do this, but I'm open to discussions if anyone has any ideas on how to implement this

**Comment by vkiranmaniya** [comment]
We can solve this by creating the command, The command will take the directory name as the argument and create thumbnails of files inside it, if not created. The command can also be used as Cron job so it will be more helpful

**Comment by florentvdry** [comment]
Yes it's can be done like that i think

**Comment by erdidoqan** [comment]
@fletch3555 voyager use spatie media library ? 

https://docs.spatie.be/laravel-medialibrary/v7/converting-images/regenerating-images

**Comment by fletch3555** [comment]
No it does not

**Comment by mko-tapptic** [comment]
On a semi-related note if you upload the image in media tab and then select it in bread with additional thumbnails defined they will not generate either, because they are generated on upload not on model save. This would at least provide a workaround, but it'd be nice if it was fixed as well.

**Comment by vkiranmaniya** [comment]
I think it's simple, we can modify the `thumbnail` helper method to create a new thumbnail if the thumbnail is not found, this is the perfect solution I guess.

**Comment by yarkm13** [comment]
Solving this by creating the command which will regenerate all thumbs is best way IMHO 

But @vkiranmaniya proposition may be good enough either but we can't tell if all thumbs was regenerated already. And check for file existence each time thumbnail is requested will cause additional load forever contrary to command method which will regenerate images once ad we can do it late in the night. But as soon there are no "thumbnail helper" we can modify `Resizable` trait or create custom trait as temporary solution. Something like this:

    namespace App\Traits;

    use TCG\Voyager\Traits\Resizable as VoyagerResizable;
    trait Resizable
    {
        use VoyagerResizable {
            VoyagerResizable::thumbnail as parentThumbnail;
        }

        /**
         * Method for returning specific thumbnail for model and generate thumbnail if not exist
         *
         * @param string $type
         * @param string $attribute
         *
         * @return string
         */
        public function thumbnail($type, $attribute = 'image')
        {
            $tumb = parentThumbnail($type, $attribute);

            // generate $tumb if not exists

            return $tumb;
        }

    }

And then change `use TCG\Voyager\Traits\Resizable;` in model to `use App\Traits\Resizable;`

But main problem here is that it's impossible to do without duplicating actual resizing and thumbnails generating code from Voyager itself because that code tightly coupled with upload process and Request. We need to create fake Request object containing files from database and call `TCG\Voyager\Http\Controllers\ContentTypes\Image::handle()` to reuse that code and that doesn't look as good solution though. I was trying but i don't like it. I don't like to rewrite resizing code also.

Correct me if i'm wrong and there are simple solution out there.
