### ISSUE TITLE
ErrorException (E_ERROR) get_class() expects parameter 1 to be object, string given

### ISSUE THREAD

**Issue by omarkadd** [thedevdojo/voyager#4398]
## Version information

 - Laravel: v5.8.35
 - Voyager: v1.2.7
 - PHP: 7.3.4
 - Database:MYsql 5.7

## Description

ErrorException (E_ERROR)
get_class() expects parameter 1 to be object, string given (View: /home/u535562063/domains/najdeh-system.com/vendor/tcg/voyager/resources/views/bread/partials/actions.blade.php) (View: /home/u535562063/domains/najdeh-system.com/vendor/tcg/voyager/resources/views/bread/partials/actions.blade.php)
Previous exceptions
get_class() expects parameter 1 to be object, string given (View: /home/u535562063/domains/najdeh-system.com/vendor/tcg/voyager/resources/views/bread/partials/actions.blade.php) (0)
get_class() expects parameter 1 to be object, string given (0)

## Additional context
right after upgrading to 1.2.7

**Comment by emptynick** [comment]
We need a little more information.
This doesn't happen on a default installation. So do you have custom Actions? If yes, how do they look?
Can you post a screenshot of the stacktrace?

**Comment by omarkadd** [comment]
this error happens where i use a custom view nothing fancy i just added a new table in the browse the action.blade is reading from this table .. in the past it worked great after update this happened as for the table it has the same action buttons as the default table

**Comment by omarkadd** [comment]
i downgraded voyager to 1.2.6 for now  till i find a solution to the problem thanks

**Comment by takamunetanii** [comment]
> i downgraded voyager to 1.2.6 for now till i find a solution to the problem thanks

I solved it in the same way.thank you.
In my case, it happens only user table.

**Comment by impsart** [comment]
Also getting this error. I'm using Laravel Wave that relies on voyager. Only package I can think of that might be having conflicts with at the moment.

**Comment by mattrabe** [comment]
For anyone suddenly suffering from this...

This is absolutely related to upgrading from 1.2.6 to 1.2.7. But, **it is more specifically related to using a 1.2.6 bread/browse.blade.php view on top of a 1.2.7 voyager core.** This describes my situation, and it describes the OP's situation.

It also seems to interplay with cache (maybe view cache), so you **may not see this right after an upgrade**. It may pop up some time later, seemingly out of the blue when your cache happens to refresh...

Your solution is not to downgrade to 1.2.6: it is to upgrade your custom browse.blade.php to the 1.2.7 version 🎈Diff it with your customized version, and I bet you'll find that your version uses `Voyager::actions()` (bad) instead of the new `$actions` (🎉). For me, this was lines 32 & 257

**Comment by ahmadsyamim** [comment]
Still getting error.
get_class() expects parameter 1 to be object, string given

$action return "TCG\Voyager\Actions\DeleteAction"

laravel/framework - v6.5.1    
tcg/voyager - v1.3.0

**Comment by insology** [comment]
Hello, i have the same problem with 1.3.* version, i'm using the default actions.blade.php with $class = get_class($action);

**Comment by MrCrayon** [comment]
@insology this is a closed issue, did you read previous comments?

**Comment by MattiaMarchiorato** [comment]
@MrCrayon , yes but i confused actions.blade with browse.blade.php :(

**Comment by EdisonValdez** [comment]
I solved this by **removing the content**  of the caching file which is referring the error to...
**Obs:** I didn't delete the file itself but removed the content inside of it. 

I emptied **(storage/framework/view/6809f6fe544a24d10b0e29d8a5f79e801cedd864.php)** and it worked.
Noted: I followed all the tips above and in my case, none of them worked. I'm not sure if it is a definitive solution, but in the meantime, it works well and these issues are gone.

Give it a try and let me know.

**Comment by tommiekn** [comment]
Hi, i'm having the same issue, just been updating an app i wasnt updating since a couple of years.

I am using custom views and thats the first thing i update once i update the app but to debug this issue i have removed all the custom views, and still have the issue, so really no clue where this is coming from.

Tried to downgrade but nothing changed.
Tried to delete all caches, views and what so ever but nothing changed.

Im currently on 1.3.2

If i do a grep like : grep -R "Voyager::actions" *

I get the following.

_resources/views/vendor/voyager/actions/browse.blade.php_:        @foreach(Voyager::actions() as $action)

_resources/views/vendor/voyager/submission-forms-entries/browse.blade.php_:        @foreach(Voyager::actions() as $action)

_storage/framework/views/dc188e9091367cd620e987dccb956c98ac3fd6c0.php_:                                            <?php $__currentLoopData = Voyager::actions(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $action): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>

_vendor/pvtl/voyager-frontend/resources/views/vendor/voyager/users/browse.blade.php_:                                            @foreach(Voyager::actions() as $action)

_vendor/tcg/voyager/src/Http/Controllers/VoyagerBaseController.php_:            foreach (Voyager::actions() as $action) {


Please note that i have updated all the browse.blade.php except the first two ones you see up here, if i update these two with Voyager::actions()-> $actions, it gives exception:

Undefined variable: actions

The weird thing is that this is happening only on these two templates, all the others has been updated correctly and works with no issues with $actions.

As well weird thing that this "vendor/tcg/voyager/src/Http/Controllers/VoyagerBaseController.php" is not updated for what i see on the grep.

Somebody has any idea on how to figure this out?

**Comment by MrCrayon** [comment]
@tommiekn this is a closed issue.
Read previous comments https://github.com/the-control-group/voyager/issues/4398#issuecomment-537762684 and if you have problems upgrading please ask in Voyager slack chat.
