### ISSUE TITLE
Voyager not loading properly

### ISSUE THREAD

**Issue by nattive** [thedevdojo/voyager#4414]
## Version information

 - Laravel: v5.8.33
 - Voyager: v1.2
 - PHP: 7.2.5
 - Database: [type] [version] MySQL 

## Description

Images and icons are not display, icons are displaying letters 
## Steps To Reproduce
I dont know what i did wrong, I was trying to override the controller and view, which worked. But later, after relogin everythibg seems broken, looks like its getting the inages and icon from a diffrent source, i removed and reinstall voyager, same issue. What can be the cause pls.

## Last steps i did before noticing the error

Last steps i could recall i took are:
1) created a new view controller
2) created a new edit-BREAD
3) did a virtual host from  127.0.0.1 to nattivehub.test

Screenshot
![Annotation 2019-09-15 121603](https://user-images.githubusercontent.com/53889328/64920801-67acb380-d7b3-11e9-9396-6b73a7ccd10c.png)

**Comment by fletch3555** [comment]
Sorry for the late response.

Unfortunately, there's not much I can suggest since I have no way of knowing what changes you've made.  Having said that, if it's just broken images, there are generally only two causes.  Either your APP_URL isn't correct (needs to match the domain you're accessing your site at), or you're missing the storage symlink
