### ISSUE TITLE
MenuItem Policy

### ISSUE THREAD

**Issue by yogeshchauhan** [thedevdojo/voyager#4426]
## Version information

 - Laravel: v6.0.3
 - Voyager: v1.2
 - PHP: 7.3
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description of problem

I want to over-ride MenuItem Policy. Is it any way to over-ride this?

**Comment by fletch3555** [comment]
Voyager 1.2 does not support laravel 6. There's an issue where composer is allowing it, but there are known issues.  1.3 will fix those issues and add official support.

Also, what you're asking is a question, not a bug report or feature request.  Questions are best asked on slack since it often leads to a discussion.

**Comment by fletch3555** [comment]
But to answer your question, yes, just create a new policy class, extend the original, and register it in a service provider like you would in any other laravel app
