### ISSUE TITLE
[Hook] Could not find package "test_hook" when add "test_hook"

### ISSUE THREAD

**Issue by csliangy** [thedevdojo/voyager#4438]
## Version information

- Hooks Version: 1.0.9
- voyager-hooks: 1.2.2
- Voyager Version: 1.x-dev c9dd5a8
- Laravel Version: 6.0.4
- PHP Version: 7.2.20

## Description

After enable the "browse_hooks" permission, I can see the "hooks" menu, however, I cannot create any hook.

## Steps To Reproduce

1. Steps to reproduce the behavior:
2. laravel new hooks
3. cd hooks
4. composer require tcg/voyager
5. php artisan voyager:install --with-dummy
6. add "browse_hooks" permission to database to make the menu visible
7. "Add hook"

## Error message:
InvalidArgumentException
Could not find package test_hook. Did you mean one of these? yipl/hookah pxn/hooktest appventus/hooks dam1r89/test-hooks thecrypticace/hooks

## Screenshots
![image](https://user-images.githubusercontent.com/515787/65659546-230cfc00-e080-11e9-8901-b62192bf14a9.png)

**Comment by fletch3555** [comment]
Hooks are managed under a separate package/repository.  Can you do a little debugging and figure out whether the issue is from larapack/hooks (base hook functionality) or larapack/voyager-hooks (voyager bridge).  Most likely the base hooks package, but I don't have quite enough info here to debug it myself.
