### ISSUE TITLE
Server side option - Problem

### ISSUE THREAD

**Issue by Muhammadinaam** [thedevdojo/voyager#455]
New option added in Voyager to show Browse page using Laravel pagination is not working:

I added 10,000 users with tinker and then I edited the BREAD and enabled server side (Pagination) option. Then I noticed two problems:

Now voyager shows on 15 entries. Next and Previous buttons don't show records after 15 users. I have to manually add (?page=4) at the end of url

![bug1](https://cloud.githubusercontent.com/assets/22542738/21522182/2bf48002-cd25-11e6-8dc9-f7ac022f5124.png)

When I try to edit BREAD and deactivate server side option and save. BREAD gets saved but server side option is not disabled.

Further, I am not able to show ID of users in browse page. (May be this problem is not related to above issue)

**Comment by tnylea** [comment]
@Muhammadinaam is there a custom view that you are using. For instance is the default browse.blade.php not being loaded because there is a custom view here: `resources/views/vendor/voyager/users/browse.blade.php` ?

Let me know. And I can continue investigating. Also make sure to run

`php artisan view:clear`

**Comment by Sliverwing** [comment]
@tnylea 

but there are no codes to adapt server side paginate in `voyager/resources/views/users/browse.blade.php`

please check it out :-)

**Comment by tnylea** [comment]
got it merged in :) Thanks.
