### ISSUE TITLE
Change the roles and permission logic in voyager

### ISSUE THREAD

**Issue by podeionut** [thedevdojo/voyager#4617]
## Description of problem
I want to modify the logic of roles and permission in voyager.
I want to add a new field(company_id), in the tables roles, permissions, and permission_roles so every COMPANY registered will set its own roles and permission_roles for every employee(user-> which belongs to a company_id).
I'm struggling in solving this issue.

Example: 
Company Test1(admin user) has Employee A(normal user), B(normal user), C(normal user)
Company Test2(admin user) has Employee D(normal user), E(normal user), F(normal user)

The app has three menus let's name them X, Y, Z.
Company Test1 will give access to normal users to X, Y menus
Company Test2 will give access to normal users only to Z menus.
**Can you give me any advice?**
I don't want to change a lot in the voyager code. I just want to add a new field in those tables so every company will set their roles and permissions for each of their users.

**Comment by fletch3555** [comment]
What you're describing sounds a lot like multi-tenancy.  There are many ways to solve this, so how you do it is really up to you.  We can't prescribe a specific solution since we're not fully aware of your requirements.  If you'd like to talk through them a bit, feel free to post in our Slack group.  Additionally, I would suggest reading up on multi-tenancy concepts and see if that helps guide you toward a particular solution.

We prefer to keep github issues for actual package bugs and feature requests, so I'm going to close this now.  If you have any further questions, please feel free to ask in Slack

**Comment by MrCrayon** [comment]
You don't need to change anything in permission_roles.
You'll first want to make sure to filter permissions company Admins can't access like create_company but also browse_media etc.
Then you can add a company_id to roles and apply a global scope. 

That's to keep you started but since we prefer to keep github issue for bugs and feature requests I'll have to close this. (already closed)

If you have other questions regarding Voyager you can ask in Voyager slack group.

Be sure first to check laravel documentation on how to implement my suggestiions and what @fletch3555 said.
