### ISSUE TITLE
Adding a new unsupported locale in voyager 

### ISSUE THREAD

**Issue by DimitrovK** [thedevdojo/voyager#4618]
## Version information
 - Laravel: v6.7.0
 - Voyager: v1.3.0
 - PHP: 7.2
 - Database: MySQL 5.7

## Description

I want to add a custom, unsupported locale to Voyager's backend using MultiLanguage. The language is Bulgarian.

I've added the following to config/voyager.php

```
    'multilingual' => [
        /*
         * Set whether or not the multilingual is supported by the BREAD input.
         */
        'enabled' => true,

        /*
         * Select default language
         */
        'default' => 'en',

        /*
         * Select languages that are supported.
         */
        'locales' => [
            'en',
            'bg',
        ],
    ],
```
It actually does work and I can pick from EN and BG on the pages. What I want to do is for the user to be able to set it's locale to BG which is not part of the default ones. 

## Steps To Reproduce
Created the following folder `resources/lang/vendor/voyager/bg/` however there is no **BG** locale when I go to a User's profile to set the locale. 

I've tried to clear configuration's cache as well but to no avail.

## Expected behavior
Be able to change to BG locale when editing a user profile.

**Comment by MrCrayon** [comment]
Since the language is not currently supported this is not a bug.

Locales are dinamically listed here:
https://github.com/the-control-group/voyager/blob/c6dad15f4eff4bad97a85488dcc93cbf795eb2f6/src/Voyager.php#L326

So I'm afraid you'll have to create a folder in vendor to use that, or you can create your custom list of locales supported and feed that to your users.

The best long term solution would be if you could open a PR with Bulgarian so it gets included in Voyager, you can copy **en** and leave in english the sentences you don't have time or no interest to translate.

**Comment by DimitrovK** [comment]
Thank you,

Will try and implement the short term solution and create a list which I'll provide my users. Why didn't I think of that ....  

As for the long term one, I've actually started the translation, once I'm done, I'll open a PR and provide the Bulgarian locale.

**Comment by MrCrayon** [comment]
Even I personally don't consider this a bug we could maybe change getLocales to merge listing from `vendor/publishable/lang` and `resources/lang/vendor/voyager` @emptynick  @fletch3555

**Comment by fletch3555** [comment]
We should definitely support any directory that laravel itself will read translation files from.  Which means we should probably look into whether there's a framework class/method that can do the lookup for us instead of directly referencing a directory(in case a user changes it in their project).  Much like `path.public` is bound to the container for referencing the public directory.

**Comment by MrCrayon** [comment]
@fletch3555 I don't think lang folder path can be changed, it's always resource path plus lang.
https://github.com/laravel/framework/blob/ba4204f3a8b9672b6116398c165bd9c0c6eac077/src/Illuminate/Foundation/Application.php#L392

But anyway we can use:
`resource_path('/lang/vendor/voyager')`

**Comment by MrCrayon** [comment]
@DimitrovK you can try #4621
