### ISSUE TITLE
I can't filter results on Custom relationship attributes that uses eloquent relationship

### ISSUE THREAD

**Issue by GitCodeCruiser** [thedevdojo/voyager#4798]
## Version information

 - Laravel: 6.2
 - Voyager: v1.3
 - PHP: 7.4.1
 - Database: [mysql] [10.4.11-MariaDB]

## Description
When trying to filter a select results I'm getting "the results could not be loaded". I have a custom attribute in my relationship which is a result of a column from current table and a column from a table in relationship (eloquent relationships).

If I remove column of the table in relationship my custom attribute on Bread relationship filter works just fine.

## Steps To Reproduce
1. Create a custom attribute on the model that includes an attribute of 2nd table using eloquent relationships
eg.
public $additional_attributes = ['full_name'];

    public function getFullNameAttribute()
    {
        return "{$this->name} - {$this->district->name}";
    }
    public function district() 
    {
        return $this->belongsTo( District::class, 'district_id', 'id');
    }

2. Create a relationship using voyger

3. Select the custom attribute on the relationship and save

4. Add new register on BREAD

5. Try to filter select results
## Expected behavior
I understand that it's difficult to search in the second table but it must at-least let me filter based on the the current table value.

## Screenshots
![image](https://user-images.githubusercontent.com/20744955/75682700-a8dc4580-5cb7-11ea-9929-bd78702d5187.png)
![image](https://user-images.githubusercontent.com/20744955/75682747-c0b3c980-5cb7-11ea-9445-02716136c384.png)

## Additional context
In the screenshots above ملک غلام محمد is the value from current table and لاہور is the value from second table i.e. district

**Comment by MrCrayon** [comment]
What's the response in ajax call, is there any error?

**Comment by fleroy91** [comment]
I've got the same issue and it's coming from there:
https://github.com/the-control-group/voyager/blob/1.4/src/Http/Controllers/VoyagerBaseController.php#L873

If you use a scope, you have an Eloquent model and the `->additional_attributes` is raising an exception because it works only for model object.

I solved it by overriding the VoyagerBaseControler@relation method and changing this:

`if (in_array($options->label, $model->additional_attributes ?? [])) {`

by this:

`if (in_array($options->label, app($options->model)->additional_attributes ?? [])) {`

**Comment by emptynick** [comment]
I think this is fixed here: https://github.com/the-control-group/voyager/pull/4875

**Comment by MrCrayon** [comment]
Closed because no feedback was provided.
