### ISSUE TITLE
Suggest a new feature called "Admin Log"

### ISSUE THREAD

**Issue by khanhtit1102** [thedevdojo/voyager#4864]
## Description of problem

If the voyager system is used by multiple administrators. When some administrator delete a page or a post. We don't know who deleted it. It gonna be a big problem.

## Proposed solution
So I suggest an idea. It should be have an administrator's action log. We'll know who deleted, edited this post or something.

- Hope the Voyager has this feature as soon as possible. Thank for your useful package.

**Comment by chadpriddle** [comment]
Agreed about this being built in off the bat. I use this composer addon package. After it is installed, I add the loggin function in each of my model files. Then it creates an "activity_log" table in my DB. I create a BREAD instance on that table so that I can view the logs in voyager. Pretty slick. 

https://github.com/spatie/laravel-activitylog

**Comment by fletch3555** [comment]
We appreciate the suggestion, but have no plans to add this right now.  Voyager and Eloquent provide a number of events you can listen for to provide your own audit log functionality.
