### ISSUE TITLE
Download File uploaded with Voyager, from view

### ISSUE THREAD

**Issue by Morgul21** [thedevdojo/voyager#4916]
## Version information

 - Laravel: v7.0
 - Voyager: v1.4
 - PHP: 7.2
 - Database: MariaDB 10.4.11

## Description

I have a products table and marked a field as `file` in Voyager Admin Panel. After uploading the file, I'm not able to retrieve it clicking on download.
I can download it from the Voyager Panel, but not from the view.

Here's what I've tried
**HomeController.php**
```
public function download($id)
    {
        $product = Product::where('id',$id)->firstOrFail();
        $down = $product->download()->get();
        $down = json_decode($down);
       
        foreach($down as $item){
  
            $path =json_decode($item->link);
        }
        return response()->download(storage_path($path[0]->download_link));
    
    }
```
view.blade.php

```
<form action="{{route('home.download',$product->id)}}" method="GET">
          {{csrf_field()}}
          <input type="hidden" name="id" value="{{$product->product_id}}">
          <input type="hidden" name="name" value="{{$product->name}}">
          <input type="hidden" name="price" value="{{$product->price}}">
          <button type="submit" class="cart-button card-game-btn align-self-end position-absolute"><i class="fas fa-download">&nbsp;</i>Download</button>
        </form>
```
It keeps telling me that the file is not in storage path,and even put manually the file in the folder won't resolve this.

Also the strange thing is that Voyager uploads the file in the public\storage\downloads (the filder create linked with storage:link)
But Laravel searchs in root-folder\storage\download
Before using voyager i was simply able to download the file referring the path of the file with storage_path().
I'm sorry if this is a stupid question but I can't find anything in the docs about this.

**Comment by fletch3555** [comment]
Well that makes sense to me.  I think you might be misunderstanding how the `storage:link` command works.  It creates a filesystem "symlink" from `public/storage` to `storage/app/public`, so that both appear to contain the same files, but they're really only stored in one place.  For example:

Upload a file (i.e. example.pdf) with Voyager, and it might get stored as `storage/app/public/example.pdf`.  Then, when you request the file in the web browser, you can use the URL `example.com/storage/example.pdf`.  This works as long as you have laravel setup correctly in your webserver (site root is `<path to your app>/public`), and you're either using the default `public` disk in the filesystem config, or have configured your own correctly(at which point, the behavior may be different).
