### ISSUE TITLE
Voyager Laravel images on shared host

### ISSUE THREAD

**Issue by AliHusein** [thedevdojo/voyager#5017]
- Laravel: v 7.0
 - Voyager: v1.4
 - PHP: 7.2.5
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description:
laravel / voyager worked on localhost successfully but after i uploaded on shared host (hostinger) issues started .
when i upload new image it shows broken , i tried all the solutions but not worked.
![Capture](https://user-images.githubusercontent.com/24397319/87998816-b036ab00-cb01-11ea-88a6-1a49fa8484eb.JPG)
![Capture1](https://user-images.githubusercontent.com/24397319/87998826-b593f580-cb01-11ea-8620-6088e4ec2c00.JPG)

old images worked fine , the problem is just when upload new image or update images 
please help i already stucked here month ago

**Comment by fletch3555** [comment]
Safe to assume your deploy process is an FTP copy?

Assuming that's the case, you likely copied the storage symlink (`<project root>/public/storage`) and it was converted to an actual directory.  When you upload new images, they go to the correct directory (`<project root>/storage/app/public`), but are no longer accessible through the browser because the symlink is broken.

To fix this, you should be able to do the following:

1. Look at `<root>/public/storage` and confirm that all the files also exist in `<root>/storage/app/public`.
2. Delete the `<root>/public/storage` directory
3. Recreate the symlink (either through the "Fix" button on the Voyager dashboard, or via `artisan storage:link`)

I highly recommend a better deployment process though.  Laravel Forge is a good option, but costs money.  At the very least, you should use git (or some other source control system).

**Comment by AliHusein** [comment]
> 
> 
> Safe to assume your deploy process is an FTP copy?
> 
> Assuming that's the case, you likely copied the storage symlink (`<project root>/public/storage`) and it was converted to an actual directory. When you upload new images, they go to the correct directory (`<project root>/storage/app/public`), but are no longer accessible through the browser because the symlink is broken.
> 
> To fix this, you should be able to do the following:
> 
>     1. Look at `<root>/public/storage` and confirm that all the files also exist in `<root>/storage/app/public`.
> 
>     2. Delete the `<root>/public/storage` directory
> 
>     3. Recreate the symlink (either through the "Fix" button on the Voyager dashboard, or via `artisan storage:link`)
> 
> 
> I highly recommend a better deployment process though. Laravel Forge is a good option, but costs money. At the very least, you should use git (or some other source control system).

i already did that but nothing changes ,i tried fix in voyager didn't work and  artisan storage link could not do it in host 
i did reset and deployed the project and same problem
i don't know what to do

**Comment by rabbitix** [comment]
hey..
**Short answer:** you need to use public folder itself instead of storage .


i had the same issue, and i solved it by changing the `public file system config`.
 so here is how my `disks.public` in `config/filesystem.php` look like:
```php
'public' => [
            'driver' => 'local',
            'root' =>  env('PUBLIC_ROOT', public_path()),
            'url' => env('APP_URL'),
            'visibility' => 'public',
        ],
```

also i need to mention that symlink was disabled in the sharing host i have (for security reasons) ..

**Comment by AliHusein** [comment]
> ```
> 'root' =>  env('PUBLIC_ROOT', public_path()),
>             'url' => env('APP_URL'),
> ```

did not work too

**Comment by rabbitix** [comment]
did you set `PUBLIC_ROOT` in env file?
it should be something like `/home/<username>/public_html`

**Comment by AliHusein** [comment]
> 
> 
> did you set `PUBLIC_ROOT` in env file?
> it should be something like `/home/<username>/public_html`

did not find any thing about that !!!
how to do it in .env

**Comment by rabbitix** [comment]
just add `PUBLIC_ROOT=/home/<username>/public_html` to your .env file in your host.

the PUBLIC_ROOT is the path to your `public_html` directory.

**Comment by AliHusein** [comment]
> PUBLIC_ROOT=/home/<username>/public_html

did not work too , still nothing 
in storage works but i thing it can not reach public_html , when i upload it not upload in public_html

**Comment by MrCrayon** [comment]
This is not a Voyager issue, you are going to have the same exact problems trying to deploy any Laravel project. 
It's also not possible to even try help you if you don't start proactively give more informations. 

You can try to join Voyager Slack channel and ask there hoping there is someone with enough time to follow you but I would advise to first Google: laravel deployment in shared hosting public_html
