### ISSUE TITLE
"Has one" relatinship displays no results

### ISSUE THREAD

**Issue by MikadoInfo** [thedevdojo/voyager#5074]
### Version information
 - Laravel: v 7.28.0
 - Voyager: v 1.4.x-dev 
 - PHP: v 7.4.8
 - Database: MySQL v 5.7.24

## Description:
I have two tables products and prices related with a one to one relationship,
products is the parent table and is referenced in the prices table with the column  named id_product.
I made a has one relationship using the admin panel in the products table, and a belongs to many relationship in the prices table.
In the product BREAD I want to display the price if available, and in the prices table I want to display an choose the product name (in the future the sku).
The prices BREAD with the belongs to many relationship works as intened but the products table always displays no results.

### products table:

![products_table](https://user-images.githubusercontent.com/69799889/92694962-11337000-f348-11ea-9f7c-b59a8dbba3ef.PNG)

### products relationship has one related to prices:

![products_relationship](https://user-images.githubusercontent.com/69799889/92695017-26100380-f348-11ea-8631-f11b8a5efd15.PNG)

### products BREAD displays no results for prices price column:

![products_bread](https://user-images.githubusercontent.com/69799889/92695079-3b852d80-f348-11ea-8790-f21b88d8d29f.PNG)

### prices table:

![prices_table](https://user-images.githubusercontent.com/69799889/92695174-64a5be00-f348-11ea-8f97-bd48bfea0af0.PNG)

### prices relationship belongs to products:

![prices_relationship](https://user-images.githubusercontent.com/69799889/92695272-830bb980-f348-11ea-8b6e-2d521052b16e.PNG)

### prices BREAD displays products name column like i wanted:

![prices_bread](https://user-images.githubusercontent.com/69799889/92695427-b8180c00-f348-11ea-9c28-2b33b3ae2cab.PNG)

In phpmyadmin the data is stored correctly when i edit the BREAD.

**Comment by MrCrayon** [comment]
The problem is that when you select `HasOne` relationship the `Store as` should be the key of the parent Model to store in related Model.
In your case it should be `Product` hasOne `Price`, Display the Prices `price`, Store the **Product** (not Prices) `id_product`, but since that list is made up with related model table (prices) columns it works only while using standard primary key names like `id` and you cannot currently choose the right one.

Quickest workaround is to create a custom view for your field, set in Relationship Details
```json
{
    "view": "my_view"
}
```
Then create your custom view, this is the original one:
```blade
@php
    $relationshipData = (isset($data)) ? $data : $dataTypeContent;

    $model = app($options->model);

    $query = $model::where($options->column, '=', $relationshipData->{$options->key})->first();

@endphp

@if(isset($query))
    <p>{{ $query->{$options->label} }}</p>
@else
    <p>{{ __('voyager::generic.no_results') }}</p>
@endif
```

You need to change `{$options->key}` in `id_product` or `{$options->column}`

**Comment by MikadoInfo** [comment]
It works thank you

**Comment by MrCrayon** [comment]
I'll keep it open since the workaround it's not a real fix.
