### ISSUE TITLE
Force Form field on a new line

### ISSUE THREAD

**Issue by hairmenu** [thedevdojo/voyager#5109]
## Version information

 - Laravel: v8.0
 - Voyager: v1.4
 - PHP: 7.4
 - Database: MariaDb 10.2

## Description of problem

As a desktop user, i need to more option to display edit/add forms. 

## Proposed solution
Having a 'newline:true' options in the display options. So i can have a form like this
```
"display": {
        "width": "4",
        "newLine": true
    }
```
[width:3 Form 1] [width:3 Form 2] **--- empty space**
[width:3 Form 4] --- empty space
[width:12 Form 5]

in the edit-add.blade.php something like (i m aware this is not production quality code but this is the idea)
```
 @if (property_exists($display_options, 'newLine'))
     <div class="col-md-12" class="noheight"></div>
 @endif
```

**Comment by MrCrayon** [comment]
I'd rather implement a way to assign custom classes, I actually already do it in my fork.

The current way a bit hacky is appending another class after the number, it works because Voyager does not validate that field since it comes from whoever set it in BREAD configuration.
```json
"display": {
    "width": "4 clear-both"
}
 ```
 It will make that field go on the next row
