### ISSUE TITLE
User can create user and set role even when not having edit roles permissions

### ISSUE THREAD

**Issue by hynekk** [thedevdojo/voyager#5131]
## Version information

 - Laravel: v8.0
 - Voyager: v1.4
 - PHP: 7.3
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description
User can create user and set role even when not having edit roles permissions

in views/users/edit-add.blade.php
line 64 should be 

@can('edit', app('TCG\Voyager\Models\Role'))

instead of

@can('editRoles', $dataTypeContent)

**Comment by MrCrayon** [comment]
`editRoles` is a custom policy stricter than edit_users so that you cannot change your own role even if you can edit other users and change their roles, I never liked it but that's how it is.

Permission to edit roles has nothing to do with the permission of editing users or adding users.
Permission to edit roles means that you can change permissions for roles or change the name of the role.

If you want it to behave in a different way you can create a custom policy and override `editRoles` method.
