### ISSUE TITLE
Relationship not work with Model inside Models folder

### ISSUE THREAD

**Issue by nguyenthanhhungbt1905** [thedevdojo/voyager#5171]
## Version information

 - Laravel: v8.x
 - Voyager: v1.4
 - PHP: 7.4
 - Database:  (MySQL 8.0)

## Description

When i create relationship in admin panel
-> if my model file stored in folder App\Models relation will not success 
-> If i move model file back to folder App, it will success

**Comment by dissolvdgrl** [comment]
I'm experiencing the exact same problem. Tried to add a belongsTo relationship in my posts table, where Post belongs to Category. In my case I'm using Post and Category.

In my `Post.php` model file which resides in `app/Models` directory, I have `namespace App\Models;` instead of `namespace App;`.

I fixed it by editing the BREAD for my posts table and created a relationship like this:
![Screenshot_2021-03-08 Edit BREAD for posts table](https://user-images.githubusercontent.com/11900199/110314113-1b40dd80-8010-11eb-990e-ef68c0c05426.png)

The fully qualified model name had to be changed in my case: `App\Models\Category` instead of `App\Category`

**Comment by MrCrayon** [comment]
That's not a bug or a problem, Voyager form asks for _"Fully Qualified Model Name (ex. App\Category)"_

Usually by default Models in Laravel were created in `App`, since Laravel 8 default folder is `App\Models` anyway wherever you want to save your Models you need provide the correct fully qualified name.
