### ISSUE TITLE
Trying to get property 'name' of non-object. Authorization stopped working

### ISSUE THREAD

**Issue by dmitrymaslov99** [thedevdojo/voyager#5193]
## Version information

- Laravel: v8.21.0
- Voyager: v1.4
- PHP: 7.4.11
- Database: MySQL 5.7.26

## Description
When trying to authorize, this error started to appear. Everything worked yesterday, did not touch anything.

## Steps To Reproduce
1. Go to login

## Expected behavior
Successful authorization

## Screenshots
https://flareapp.io/share/o7AXWjzP#F78

**Comment by MrCrayon** [comment]
The problem is with Post dimmer in your dashboard.
Maybe you removed Post BREAD but left the dimmer in configuration?

Try to remove the dimmer/widget in `config/voyager.php` and see if that solves the problem.

**Comment by dmitrymaslov99** [comment]
Not :( https://flareapp.io/share/A7Evx345
Yes, I was removing bread from the example, so there were problems. This is my mistake. Now just ready to create a clean project?

**Comment by emptynick** [comment]
That configuration entry has to stay as an array. For example:
```php
'widgets' => [

],
```

**Comment by dmitrymaslov99** [comment]
Thank you so much!

**Comment by damms005** [comment]
@MrCrayon  @emptynick 

This issue is recurring in different forms (see #5193, #5216, and others on SO) that mostly boil down to the permission checks on null data in BasePolicy.php.

In my experience, I find that the error does not only occur when you have wrong `widgets` entry in your config file, but also occurs when you remove and re-add the User model. In this case, it was checking the `DataType` table for `TCG\Voyager\Models\User`, which I believe is erroneous.

**Suggestion**:
in Line#83 of `voyager/src/Policies/BasePolicy.php`, a null check should be added after `$dataType = self::$datatypes[get_class($model)]`, such that if `$dataType` is null, a more descriptive and helpful exception is thrown, with a message like `Permission check error: no DataType definition found for xxx...`.

I believe this will save lots of development hours, and help the community to focus on how to reduce the rampancy/recurrence of such bugs; such as additionally adding a possible solution (such as [this](https://github.com/the-control-group/voyager/issues/3991#issuecomment-499862595)). It is now becoming a good DX practice to provide actionable exceptions ([there is even a Laravel package](https://github.com/facade/ignition) that has providing useful/actionable exception messages as one of its strengths), and Voyager is already doing fine in this regard ([like this example](https://github.com/the-control-group/voyager/blob/bc2f387eed296b3fcd442633882c2ace9fd5ef94/src/Voyager.php#L97)).

I can do a PR for this if welcomed.

**_PS:_** for the issue I reported about my encounter with this error above,  I re-added User BREAD and did not set the model name as `TCG\Voyager\Models\User` but rather my app's `App\User`. This is a good use-case example for #5293
