### ISSUE TITLE
Override bread view section

### ISSUE THREAD

**Issue by AngelSani** [thedevdojo/voyager#5271]
## Version information

 - Laravel: v7.29.3
 - Voyager: v1.x-dev 5753a2c
 - PHP: 7.2
 - Database: MySQL 14.14

## Description:
Hi, I was trying to add something to the bread views, I followed the documentation exactly but there is an error. I tried this with different projects I have but throws the same error.

## Additional context
Just follow the steps, create the file resources/views/vendor/voyager/bread/edit-add.blade.php, copy and paste the code in the documentation
![Screen Shot 2021-03-24 at 3 06 56 PM](https://user-images.githubusercontent.com/71098336/112389877-ab3e8280-8cb2-11eb-8d91-4c9aae8f158c.png)
![Screen Shot 2021-03-24 at 3 07 04 PM](https://user-images.githubusercontent.com/71098336/112389880-abd71900-8cb2-11eb-9ea3-b37f71a89b8d.png)

**Comment by MrCrayon** [comment]
In Laravel you cannot override and extend a view, that causes a loop.

If you want to override the view for all BREAD you can't use `@extends` if you want to override it for a single BREAD than you have to put the file in the right folder like:

> resources/views/vendor/voyager/**posts**/edit-add.blade.php


BTW I tried to have that fixed in Laravel but I had no idea how to write a test for it and probably it doesn't bother enough people.
https://github.com/laravel/framework/pull/33123

**Comment by AngelSani** [comment]
@MrCrayon So is there a way to add a component to the edit-add.blade.php for all BREADs without having to override every single BREAD?

**Comment by MrCrayon** [comment]
As said it's a Laravel problem, so you will have more luck asking in a Laravel forum.
As far as I know these are the options:

- Patch the framework, best solution if done upstream but quite annoying if you have to keep up to date a fork.
- Find a way to tell extend to include the view from vendor and do not use the overridden one to avoid the loop.
I did this in the past adding Voyager views folder to views paths, I can't give you the details now because I'm not near a computer.
- Copy the content of the view and add what you need.
