### ISSUE TITLE
Events in heart of voyager (VoyagerBreadController)

### ISSUE THREAD

**Issue by eimanavicius** [thedevdojo/voyager#530]
It would be really easy to modify or enchant voyager behavior if there would be events.

For example, to do some processing we could listen to event
- when event voyager.bread.add.entityname is fired do some logic (for ex. event fired from VoyagerBreadController).
- or when event voyager.bread.browse.entityname is fired change listing behavior and/or do some filtering

This way we would avoid need for controller overriding. Code looks way more simpler. 

I did experiment and implemented these events and have them working. Partial sample is available here https://gist.github.com/eimanavicius/0a49c4ff70b5cc2bffea809d8e8a89ac

**Comment by handiwijoyo** [comment]
Cool, this would be a good addition. Please help us to create a PR for this, then we can review it.

**Comment by fletch3555** [comment]
I agree this would be very useful.  @eimanavicius, would you mind re-implementing this for the latest version and opening a PR? If not, we'll have to wait until someone else is willing to do so.

**Comment by vaggelis2018** [comment]
What i am using is another function in bread controller where i pass the slug and in a use case i check the slug. Then i am firing the event i want. I am doing it in this way because if for example i have a notifications table and i want to push them when i add to this specific bread i only need to create this event and i fire it only when the slug is notifications. This way i only expand the events function in bread controller. I don't know for sure if you are discussing the same issue. So i am just placing my opinion.

**Comment by fletch3555** [comment]
@akazorg has added quite a few events to Voyager in the last release or two.  I'm always open for more if the community finds a need.  I'm going to close this since the original request seems to have been completed.

**Comment by xwiz** [comment]
I think it would have been best to use the original Eloquent classes/models in update/create events. That way you can preserve observers and events already implanted on those models.
