### ISSUE TITLE
Upgrading version 1.x-dev e9160b7 to 1.x-dev 84e17f6 has syntax error at VoyagerBaseController:112 (comma)

### ISSUE THREAD

**Issue by almakano** [thedevdojo/voyager#5323]
## Version information

 - Laravel: v7.30.4
 - Voyager: v1.4
 - PHP: 7.2.24

## Description
I did `composer update` and got Internal Error, because of last comma at last argument to method leftJoin at /vendor/tcg/voyager/src/Http/Controllers/VoyagerBaseController.php:112

Could you remove unnecessary comma, please?

**Comment by Ashnard** [comment]
Just happened to me too, fixed it by removing the comma.

**Comment by MrCrayon** [comment]
Trailing commas are valid in PHP 7.3, can you double check your version?

**Comment by almakano** [comment]
> Trailing commas are valid in PHP 7.3, can you double check your version?

Confirm. Composer successfully updated voyager v1.4 to v.1.4 with installed php version 7.2.
/vendor/tcg/voyager/composer.json don't have any of php 7.3 requirement

**Comment by Ashnard** [comment]
I reverted to 1.4.2, my environment is not ready for PHP 7.3
Thanks for the info.

**Comment by MrCrayon** [comment]
@almakano my mistake I read Laravel version as if was php version, that's why I thought you had php 7.3. 😁 

Even if we fix that trailing comma 1.4.x-dev has already php 7.3 as requirement so there is no point on changing that since next release won't work on 7.2.

We already did not have tests running with 7.2 when I submitted that change since it was probably already EOL so I did not notice, sorry for that.
