### ISSUE TITLE
Voyager can't find app.css, app.js, and images

### ISSUE THREAD

**Issue by 0720678246** [thedevdojo/voyager#5380]
## Version information

 - Laravel: v#.#.#
 - Voyager: v#.#.#
 - PHP: #.#
 - Database: [type] [version] (e.g. MySQL 8.0)

**Comment by 0720678246** [comment]
![Uploading Error.PNG…]()
this is how admin panel looks

**Comment by 0720678246** [comment]
No Please help this is my first time using voyager. The Project has been working for a while only today to login to admin dashboard and find everything is broken. but in the console i have these errors. 
Failed to load resource: the server responded with a status of 404 (Not Found)
voyager-assets:1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by fletch3555** [comment]
The issue template is not optional, as stated in the template itself, which is why this was closed.

Also, I can almost guarantee this is not an issue with Voyager.  If you ask in our slack group, someone may be able to assist you with troubleshooting, but it's likely a webserver misconfiguration, so I'd also recommend asking in a more generic forum like the larachat slack, laravel discord, or the laracasts forums
