### ISSUE TITLE
Voyager Media manager not displaying files

### ISSUE THREAD

**Issue by din2011** [thedevdojo/voyager#5442]
### Laravel version

6.20.34

### PHP version

7.4.20

### Voyager version

1.5.*

### Database

MariaDB 10.4.19

### Description

Media manager displays nothings. At Console, Vue error is shown :

`[Vue warn]: Unknown custom element: <media-manager> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)`

![voyag](https://user-images.githubusercontent.com/5113206/132427713-06cbea4f-9140-46ad-9a5e-571a20715a4b.png)

### Steps to reproduce

Install Laravel 6 and Voyager 1.5.*

### Expected behavior

Media Manager should display files

**Comment by fletch3555** [comment]
Not a bug.  Laravel is not meant to be hosted the way you are (with `/public/` visible in the URL), so voyager does not work out of the box this way.

The issue isn't with media manager, it's that vue was not loaded, which is because static assets(images, JS, etc) haven't loaded, which is because your APP_URL is wrong due to how you're running it.

I strongly recommend a more standard method of running it, such as Laravel Sail, Homestead, Valet, or similar.

If you need help doing so, feel free to ask in our slack group

**Comment by din2011** [comment]
![image](https://user-images.githubusercontent.com/5113206/132510763-e624883f-5827-4f1c-a660-a778aaff5783.png)

![image](https://user-images.githubusercontent.com/5113206/132510825-f6dcb189-c6fc-4dea-8163-665be356fed8.png)

**Comment by din2011** [comment]
after I edited the resources/views/vendor/voyager/media/index.blade.php like above then its working ! Added line 37

Maybe for other who have same problems as me...

Actually  upgraded the voyager from 1.1 -> 1.3 -> 1.5 when I performed Laravel upgrade from 5.7 ro 6

**Comment by fletch3555** [comment]
That's a hack at best, and is absolutely not a recommended fix for anything at all.
