### ISSUE TITLE
Errors when Create/Edit BREAD and when Edit Table

### ISSUE THREAD

**Issue by newpain01** [thedevdojo/voyager#591]
- Laravel Version: 5.3
- Voyager Version: 0.10.10
- PHP Version: 5.6.27
- Database Driver & Version: SQLite 3.14.0

### Description:
I am using Laravel 5.3 with SQLite and I am getting errors when I try to Create/Edit BREAD and when I Edit Table from the /admin/database page. 

![voyager bread create error](https://cloud.githubusercontent.com/assets/22168845/22014393/68146f9e-dcd8-11e6-96c5-52596bd8ec91.png)
![voyager bread edit error](https://cloud.githubusercontent.com/assets/22168845/22014394/682d6972-dcd8-11e6-9767-9bf83fb75f81.png)
![voyager table edit error](https://cloud.githubusercontent.com/assets/22168845/22014395/6832edc0-dcd8-11e6-9573-eecfb2c9e0a0.png)

**Comment by marktopper** [comment]
There are some problems with the `sqlite` support at the moment.

The problem is caused by this line: https://github.com/the-control-group/voyager/blob/master/resources/views/tools/database/edit-add-bread.blade.php#L20

It should however be something like this instead: https://github.com/the-control-group/voyager/blob/master/src/Http/Controllers/Traits/DatabaseQueryBuilder.php#L103

**Comment by newpain01** [comment]
Thanks Mark, I will try to fix this.

**Comment by marktopper** [comment]
Im already on it, have a pull request for it in a few minutes.

**Comment by marktopper** [comment]
Could you do me a favor and test out the `fix/591` branch?

**Comment by newpain01** [comment]
Good job, everything working now.

**Comment by marktopper** [comment]
Wonderful, will merge it into `master` later today when fully tested and then do a version release.
