### ISSUE TITLE
[Discussion] Ways to enable model overwriting

### ISSUE THREAD

**Issue by marktopper** [thedevdojo/voyager#693]
There are multiple ways for enable model overwriting in the application. @fletch3555 and I have been discussing the best approach for this for quite a while and are now opening the discussion for everyone else.
We have been found the following possible solutions for enabling model overwriting in the future release of `v0.11`.

### Publishing empty models
First way this could be done is by publishing some empty models to the application like this to the user application:
```php
<?php

namespace App\Voyager\Models;

use TCG\Voyager\Models\Post as VoyagerPost;

class Post extends VoyagerPost
{
    //
}
```
The pros about this solution is that it does not require much documentation or changes to the codebase. This could possibly be done for the Voyager controllers as well to keep things the same way.
The cons of this is that it adds all the models to the user application, even if you may not wish to overwrite it.

### Using model aliases
Another way to enable model overwriting could be by using aliases. Then everyone and every package could easily change the model used for the model like this:
```php
public function boot()
{
    $this->app->register('voyager.models.post', MyPostModel::class);
}
```
The pros about this is that it can be done directly from packages and it does not requires to have all the model class files laying around in the user application.
The cons about this is that it will need to be proper documented and does require a lot of changes in the current codebase.

### Other solutions
If you have any other solutions for this, please share.

**Comment by anhskohbo** [comment]
I think model should be changeable in `config/voyager.php` file. That is best way for me.

**Comment by marktopper** [comment]
@anhskohbo: How would you like the configuration for this to look like?

**Comment by abdgad** [comment]
Currently I don't have a lot of ideas, I am currently busy with the database manager.
But I was thinking about a "Plugin system". Voyager will have only "core" features. And plugins will build on those features. For example a Posts plugin, or a plugin that adds a Theme, etc... In that case, it will be up to the Plugin itself to allow for customizations. It won't be Voyager's responsibility.
Of course a Plugin system will require a LOT of changes to the code base, but it will be worth it once it's complete, because then we'll focus on core features, and extra features can always be added via separate Plugins.
I will start to research this once I finish the database work.

**Comment by marktopper** [comment]
@abdgad: Thanks a lot for your feedback.
We might however still need some way to do this for the Voyager models. Since there are some models that might not be turned into a plugin.
Like DataType and DataRow

**Comment by abdgad** [comment]
@marktopper Maybe we don't need to make them extendable, because modifying core models can result in breaking the app. We don't want them to be modified. We'll just provide an api for Plugins that need access to them... What do you think?

**Comment by marktopper** [comment]
I see your point @abdgad.

**Comment by marktopper** [comment]
Done in #758
