### ISSUE TITLE
Multiple Images - Input Type => have no option to delete any image.

### ISSUE THREAD

**Issue by sarath-c-sandwich** [thedevdojo/voyager#820]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.2
- PHP Version: 5.6.*
- Database Driver & Version: MariaDB

### Description:
Multiple Image data type is really nice. I love that, but there is no option to **delete image**

### Steps To Reproduce:
Go to Database > BREAD > change **Input Type** to Multiple Images

**Comment by sikhub** [comment]
@marktopper assign me to this one, please.

**Comment by marktopper** [comment]
**Off-topic**: For some reasons I can not assign this to you @sikhub. I have contacted Github support about this, will keep you updated. Meanwhile I'm removing the `help wanted` label. Since you are on it 😄

**Comment by sikhub** [comment]
What would be the most neat/friendly way to remove image? I was thinking about using ajax and showing modal window to let user decide about further actions.

When you hover over image you get "toolbar" (at this moment only X to remove/delete image)
![hover](https://cloud.githubusercontent.com/assets/4103737/23628992/81d07ece-02b6-11e7-84e4-c5d5d9d71aab.png)

And when you will click on X, you get modal
![modal](https://cloud.githubusercontent.com/assets/4103737/23629009/92d99dd6-02b6-11e7-971b-f4d1e2b30dff.png)

1. Should be image removed (stays in media folder) or deleted (completely removed from server)?
2. What about option where both buttons are in modal. Remove and delete.

Feel free to comment and discuss.

CC: @marktopper

**Comment by marktopper** [comment]
Sorry for the delay, have been some real busy days.

@sikhub: I think that is a great improvement! To answer your questions, then my believe are the followings:

1. I think that the file should stay in media by default, since it's in my todo list to make it able to choose files for BREAD directly from the media library, therefor in future a file will be able to be used in multiple BREADs.
2. It could however as you mention yourself be a good idea to let the user have a choice whether or not to delete it from the media library in a modal.

I am open for both solutions with or without this modal.

**Comment by sikhub** [comment]
@marktopper No problem.

Cool. I will go with the first one then. We can still implement delete function in the future.

**Comment by marktopper** [comment]
Awesome!

**Comment by marktopper** [comment]
Fixed in #890

**Comment by sarath-c-sandwich** [comment]
Cheers,
