### ISSUE TITLE
Pagination with search

### ISSUE THREAD

**Issue by gavinj1999** [thedevdojo/voyager#928]
- Laravel Version: 5.4.13
- Voyager Version: #.#.#
- PHP Version: 5.6.3
- Database Driver & Version: Mysql 5.5.54

### Description:
I have a table with 3000 rows so chose server side pagination, however I want to use the search facility of none server side pagination. Of course the catch 22 is that the table takes a long time to load.

Can I have the best of both worlds?

**Comment by luismareze** [comment]
why is it closed?
is it solved?

**Comment by gavinj1999** [comment]
It's not an issue per se, perhaps should be tagged as a feature request.

**Comment by Frondor** [comment]
Not really. 
In that case, you may need to override the `bread/browse` view for that specific BREAD and implement your own UI, probably you'll need to provide your own controller as well.

Everything's in the docs: https://the-control-group.github.io/voyager/docs/0.11/#customization-overriding-views

**Comment by luismareze** [comment]
Well, the point is if I want to run a simple browse of data (100 records) and I dont want to use a serve side pagination. What Do I do?
Because the serve side in my point of view is unuseful without a 'search box' because is quite annoying find the specific data doing a click on next button.

I really like the way how this project going, but this is my point of view.

**Comment by Frondor** [comment]
@luismareze you can follow this PR #937
