### ISSUE TITLE
Can't clear the filled field.

### ISSUE THREAD

**Issue by dimsanchuk** [thedevdojo/voyager#946]
- Laravel Version: 5.4.12
- Voyager Version:  0.11.7
- PHP Version:  5.6
- Database Driver & Version: MySQL

### Description:
It is not possible to save a text field with an empty string, if there is already a record with this field filled.

### Steps To Reproduce:
1. In the context of the blog,  I have post with filled field "Post Content":
![image](https://cloud.githubusercontent.com/assets/13986110/23955440/8bbf774e-09a2-11e7-8174-2b4983a44dc2.png)
2. Now I am clearing the field "Post Content":
![image](https://cloud.githubusercontent.com/assets/13986110/23955510/c0e0e390-09a2-11e7-9996-b3582b642d72.png)
3. Click the button "Update Post" and I see again filled field "Post Content":
![image](https://cloud.githubusercontent.com/assets/13986110/23955697/587faaec-09a3-11e7-962e-7617e18e91b8.png)

**Comment by dimsanchuk** [comment]
There's someone here?

**Comment by dimsanchuk** [comment]
This happens not only when editing a record, but also on the edit page of the BREAD in the "Optional Details" field.

**Comment by marktopper** [comment]
I see. Can you please get the SQL query that is being ran when doing the change?

**Comment by dimsanchuk** [comment]
Saving with empty "Post Content":
![image](https://cloud.githubusercontent.com/assets/13986110/24157218/7367ac8e-0e61-11e7-991d-fb2eba528e01.png)
Saving with changed data in "Post Content":
![image](https://cloud.githubusercontent.com/assets/13986110/24157260/967a037a-0e61-11e7-976a-2dfacf27ee2f.png)
I also found a place in the code that prevents change:
https://github.com/the-control-group/voyager/blob/master/src/Http/Controllers/Controller.php#L76 (lines 76-78)

**Comment by marktopper** [comment]
Thanks, it seems like it does not even trigger the change in the controller just as you said.
Will have to figure out why those lines where added.

**Comment by marktopper** [comment]
Can you share the BREAD configuration for the `posts` table?

**Comment by dimsanchuk** [comment]
![image](https://cloud.githubusercontent.com/assets/13986110/24161048/0c4906c8-0e6c-11e7-91be-b8751383eabb.png)

**Comment by marktopper** [comment]
Can you test if #987 helps?

**Comment by dimsanchuk** [comment]
And nothing has changed. Only I believe that this is a significant issue?
This also applies to field "Optional Details" on BREAD edit page.

**Comment by webber-ch** [comment]
This also applies to the settings section.

**Comment by fletch3555** [comment]
Laravel 5.4 uses new middleware.  One of them converts empty strings to "null".  I believe there is code (not sure if in Laravel or Voyager) that checks for null values and removes them from the query.  Due to this, submitting empty strings through a form will be converted to null values, and then not updated in the DB.

You can try disabling that middleware in your install to see if that fixes it for you.  Please let us know if so, and we should be able to implement a workaround.

**Comment by mmickelson** [comment]
I found that I could work around the issue in Optional Details by leaving empty brackets, e.g. `{} `

**Comment by fletch3555** [comment]
This is not a `bug` with Voyager, or Laravel for that matter.  It's a `feature` added in Laravel 5.4, and something we have no control over.  If you want that feature removed, you will have to remove the middleware yourself.

**Comment by carlost89** [comment]
This is the code in TCG\Voyager\Http\Controllers\VoyagerSettingsController in line 92 that is causing that we can't save empty strings on Settings when we try to update:

`if ($content === null && isset($setting->value)) {
                $content = $setting->value;
            }`

Also, When I comment this code, I can't save the changes because "value" in settings table is not nullable.

I think this is not a Laravel Problem. If I want to empty a setting, I have to do it directly in DB.

**Comment by emptynick** [comment]
This is not about Settings, but about normal BREAD stuff.
Also this is nearly one year old.
