### ISSUE TITLE
less compatible error while overriding controller

### ISSUE THREAD

**Issue by ashishshah-github** [thedevdojo/voyager#951]
- Laravel Version: 5.3.*
- Voyager Version: 0.11.5
- PHP Version: 5.6.25
- Database Driver & Version: 5.7.14

### Description:

We are overriding Controllers for Voyager Package. we have follow steps mentioned in this below guideline. https://the-control-group.github.io/voyager/docs/0.11/#customization-overriding-routes

when we are defining methods from BREAD controller in this override controller then it is throwing error exception of "Declaration of method less compatible with".

can anyone tell correct way to doing so ?

Thanks in Advance.

**Comment by abdgad** [comment]
This is a PHP error. See [this](http://stackoverflow.com/questions/3115388/declaration-of-methods-should-be-compatible-with-parent-methods-in-php).

**Comment by ashishshah-github** [comment]
Hello @abdgad 

Can't you tell what we are doing wrong with it ? we are just trying to override controllers as mentioned in voyager docs.

Thanks!

**Comment by abdgad** [comment]
@ashishshah-github the error you're getting is related to PHP. It's because you are overriding a method but you are declaring it in an "incompatible" way. For example, let's say in the parent class, there is this method:
```php
public function show(Request $request, $id) // This is the method declaration
{
// parent code here....
}
```
If you want to override that method, in your extended class you should do this:
```php
public function show(Request $request, $id) // Notice this declaration is the same as the parent one
{
// override code here...
}
```
You can look at the source to learn more information about the various methods available: https://github.com/the-control-group/voyager/tree/master/src/Http/Controllers
